window.sru=window.sru||{};window.sru.userData=window.sru.userData||{};
(function(C){function F(d,a,p){var e=[],h=[],f=[],l=[],r,c,b,g,q,k,n;for(n in d)d.hasOwnProperty(n)&&(b=g=q=k=!1,r=d[n],c=r.local,r=r.remote,c?c.__dapiInfo?!p&&c.__dapiInfo?c.deleted?k=!0:c.modifiedDate>c.__dapiInfo.modifiedDate&&(g=!0):p&&c.__dapiInfo&&(r?c.deleted?k=!0:c.modifiedDate>r.modifiedDate?g=!0:c.__dapiInfo.version<r.version&&(b=!0):q=!0):c.deleted?q=!0:g=!0:r&&(b=!0),q?f.push(x(n,c,a)):k?l.push(x(n,c,a)):b?e.push({uuid:r.uuid}):g&&h.push(x(n,c,a,!0)));return{toDownload:0<e.length?e:null,
toUpload:0<h.length?h:null,toDeleteRemote:0<l.length?l:null,toDeleteLocal:0<f.length?f:null}}function x(d,a,p,e){var h=null;p==u.Directory||p==u.Outline?(h={uuid:d},e&&(h.parentUuid=a.parentUuid,h.title=a.title,h.creationDate=a.creationDate,h.modifiedDate=a.modifiedDate)):p==u.Topic?(h={uuid:d},e&&(h.parentUuid=a.parentUuid,h.outlineUuid=a.outlineUuid,h.body=a.body,h.location=a.location,h.creationDate=a.creationDate,h.modifiedDate=a.modifiedDate)):p==u.Source&&(h={uuid:d},e&&(a.data.boundToOutline=
a.boundToOutline,a.data.fromHighlight=a.fromHighlight,h.outlineUuid=a.outlineUuid,h.data=JSON.stringify(a.data),h.creationDate=a.creationDate,h.modifiedDate=a.modifiedDate,delete a.data.boundToOutline,delete a.data.fromHighlight));return h}function y(d,a,p){a=a||{};d.hasOwnProperty("uuid")&&!a.hasOwnProperty("uuid")&&(a.uuid=d.uuid);d.hasOwnProperty("creationDate")&&!a.hasOwnProperty("creationDate")&&(a.creationDate=d.creationDate);d.hasOwnProperty("modifiedDate")&&(a.modifiedDate=d.modifiedDate);
if(p==u.Directory||p==u.Outline)d.hasOwnProperty("title")&&(a.title=d.title),d.hasOwnProperty("parentUuid")&&(a.parentUuid=d.parentUuid);else if(p==u.Topic)d.hasOwnProperty("parentUuid")&&(a.parentUuid=d.parentUuid),d.hasOwnProperty("outlineUuid")&&(a.outlineUuid=d.outlineUuid),d.hasOwnProperty("location")&&(a.location=d.location),d.hasOwnProperty("body")&&(a.body=d.body),a.linkedSources=a.linkedSources||{};else if(p==u.Source){d.hasOwnProperty("outlineUuid")&&(a.outlineUuid=d.outlineUuid);if(d.hasOwnProperty("data"))try{var e=
JSON.parse(d.data);e&&(e.hasOwnProperty("boundToOutline")&&(a.boundToOutline=e.boundToOutline,delete e.boundToOutline),e.hasOwnProperty("fromHighlight")&&(a.fromHighlight=e.fromHighlight,delete e.fromHighlight),a.data=e)}catch(h){dji.logger.error(h)}a.boundToOutline=a.boundToOutline||!1;a.fromHighlight=a.fromHighlight||!1}a.__dapiInfo=a.__dapiInfo||{};d.hasOwnProperty("modifiedDate")&&(a.__dapiInfo.modifiedDate=d.modifiedDate);d.hasOwnProperty("version")&&(a.__dapiInfo.version=d.version);return a}
function Q(d,a,p){var e={},h={},f={},l={},r={},c,b,g,q,k,n,m,v,u,t=function(a,d,e){if(a&&d&&e)for(c=0;c<a.length;c++)g=a[c],b=g.uuid,d.hasOwnProperty(b)||(d[b]={}),d[b][e]=g},z=function(a,b,d){if(a&&b&&d)for(c=0;c<a.length;c++)if(k=a[c].topicUuid,v=a[c].sourcesUuids,m=b[k]=b[k]||{},v)for(var e=0;e<v.length;e++)n=v[e],u=m[n]=m[n]||{},u[d]={modifiedDate:-1}};for(b in d.directories)e[b]={local:d.directories[b]};for(b in d.outlines)h[b]={local:d.outlines[b]};for(b in d.topics){q=d.topics[b];f[b]={local:q};
m={isEmpty:!0};for(n in q.linkedSources)m[n]={local:q.linkedSources[n]},m.isEmpty=!1;m.isEmpty||(delete m.isEmpty,r[b]=m)}for(b in d.sources)l[b]={local:d.sources[b]};p?(t(a.directories,e,"remote"),t(a.outlines,h,"remote"),t(a.topics,f,"remote"),t(a.sources,l,"remote")):(a.download&&(t(a.download.directories,e,"download"),t(a.download.outlines,h,"download"),t(a.download.topics,f,"download"),t(a.download.sources,l,"download")),a.update&&(t(a.update.directories,e,"update"),t(a.update.outlines,h,"update"),
t(a.update.topics,f,"update"),t(a.update.sources,l,"update"),z(a.update.topicsSources,r,"update")),a["delete"]&&(t(a["delete"].directories,e,"delete"),t(a["delete"].outlines,h,"delete"),t(a["delete"].topics,f,"delete"),t(a["delete"].sources,l,"delete"),z(a["delete"].topicsSources,r,"delete")));return{directories:e,outlines:h,topics:f,sources:l,topicsSources:r}}var u={Directory:1,Outline:2,Topic:3,Source:4,TopicsSources:5};C.syncPrepareOutlinesUpdate=function(d,a,p){var e,h,f;if(!a)return null;try{var l,
r=!1,c,b={},g={directories:[],outlines:[],topics:[],sources:[],topicsSources:[]},q=Q(d,a,!0),k=F(q.directories,u.Directory,p),n=F(q.outlines,u.Outline,p),m=F(q.topics,u.Topic,p),v=F(q.sources,u.Source,p),D=q.topics,t=q.topicsSources;a=[];p=[];var q=[],z=[],y,E,x,J,K,L,M,A,N,w,O,B,C;for(A in t)if(t.hasOwnProperty(A))for(N in x=t[A],C=D[A],x)J=K=L=M=!1,w=null,O=x[N],E=O.local,y=O.remote,E?E.__dapiInfo?E.deleted&&(M=!0):E.deleted?L=!0:C.local.deleted||(K=!0):y&&(J=!0),L?w=q:M?w=z:J?w=a:K&&(w=p),w&&(B=
0<w.length?w[w.length-1]:null,B&&B.topicUuid==A||(B={topicUuid:A,sourcesUuids:[]},w.push(B)),B.sourcesUuids.push(N));e=0<p.length?p:null;h=0<z.length?z:null;f=0<q.length?q:null;if(k.toDeleteLocal&&0<k.toDeleteLocal.length)for(r=!0,l=0;l<k.toDeleteLocal.length;l++)c=k.toDeleteLocal[l].uuid,d.directories[c]&&!d.directories[c].deleted&&g.directories.push(c),delete d.directories[c];if(n.toDeleteLocal&&0<n.toDeleteLocal.length)for(r=!0,l=0;l<n.toDeleteLocal.length;l++)c=n.toDeleteLocal[l].uuid,d.outlines[c]&&
!d.outlines[c].deleted&&g.outlines.push(c),delete d.outlines[c];if(m.toDeleteLocal&&0<m.toDeleteLocal.length)for(r=!0,l=0;l<m.toDeleteLocal.length;l++)c=m.toDeleteLocal[l].uuid,d.topics[c]&&!d.topics[c].deleted&&g.topics.push(c),delete d.topics[c];if(v.toDeleteLocal&&0<v.toDeleteLocal.length)for(r=!0,l=0;l<v.toDeleteLocal.length;l++)c=v.toDeleteLocal[l].uuid,d.sources[c]&&!d.sources[c].deleted&&g.sources.push(c),delete d.sources[c];if(f&&0<f.length){var G,H,I,P,r=!0;for(l=0;l<f.length;l++)if(G=f[l],
H=d.topics[G.topicUuid])for(P=G.sourcesUuids,I=0;I<P.length;I++)D=[],c=P[I],H.linkedSources[c]&&!H.linkedSources[c].deleted&&D.push(c),0<D.length&&g.topicsSources.push({topicUuid:G.topicUuid,sourcesUuids:D}),delete H.linkedSources[c]}k.toUpload&&(b.update=b.update||{},b.update.directories=k.toUpload);n.toUpload&&(b.update=b.update||{},b.update.outlines=n.toUpload);m.toUpload&&(b.update=b.update||{},b.update.topics=m.toUpload);v.toUpload&&(b.update=b.update||{},b.update.sources=v.toUpload);e&&(b.update=
b.update||{},b.update.topicsSources=e);k.toDeleteRemote&&(b["delete"]=b["delete"]||{},b["delete"].directories=k.toDeleteRemote);n.toDeleteRemote&&(b["delete"]=b["delete"]||{},b["delete"].outlines=n.toDeleteRemote);m.toDeleteRemote&&(b["delete"]=b["delete"]||{},b["delete"].topics=m.toDeleteRemote);v.toDeleteRemote&&(b["delete"]=b["delete"]||{},b["delete"].sources=v.toDeleteRemote);h&&(b["delete"]=b["delete"]||{},b["delete"].topicsSources=h);k.toDownload&&(b.download=b.download||{},b.download.directories=
k.toDownload);n.toDownload&&(b.download=b.download||{},b.download.outlines=n.toDownload);m.toDownload&&(b.download=b.download||{},b.download.topics=m.toDownload);v.toDownload&&(b.download=b.download||{},b.download.sources=v.toDownload);b.update||b["delete"]||b.download||(b=null);r&&(r=!0);0==g.directories.length&&delete g.directories;0==g.outlines.length&&delete g.outlines;0==g.topics.length&&delete g.topics;0==g.sources.length&&delete g.sources;g.directories||g.outlines||g.topics||g.sources||(g=
null);return{save:r,data:b,deleted:g}}catch(R){dji.logger.error(R)}};C.syncPrepareOutlinesSave=function(d,a){if(!a)return null;try{var p,e,h,f,l,r,c,b,g,q=!1,k={directories:[],outlines:[],topics:[],sources:[]},n={topicsSources:[]},m=Q(d,a,!1);for(e in m.sources)m.sources.hasOwnProperty(e)&&(f=m.sources[e],b=f.download||f.update)&&(c=y(b,f.local,u.Source),f.local=c,d.sources[c.uuid]=c,f.download&&k.sources.push(c),q=!0);for(e in m.topics)if(m.topics.hasOwnProperty(e)&&(f=m.topics[e],b=f.download||
f.update)&&(c=y(b,f.local,u.Topic),f.local=c,d.topics[c.uuid]=c,q=!0,f.download)){var v=[];b.sourcesUuids=b.sourcesUuids||[];for(p=0;p<b.sourcesUuids.length;p++)g=b.sourcesUuids[p],h=c.linkedSources[g]||{},h.modifiedDate=c.modifiedDate,h.__dapiInfo={modifiedDate:c.modifiedDate},c.linkedSources[g]=h;for(g in c.linkedSources)!c.linkedSources[g].deleted&&c.linkedSources[g].__dapiInfo&&-1==b.sourcesUuids.indexOf(g)&&(v.push(g),delete c.linkedSources[g]);0<v.length&&n.topicsSources.push({topicUuid:e,sourcesUuids:v});
k.topics.push(c)}for(e in m.topicsSources)if(m.topics.hasOwnProperty(e)&&(l=m.topicsSources[e],(r=d.topics[e])&&l))for(g in l)if(f=l[g],c=f.local)f["delete"]?(delete r.linkedSources[g],q=!0):f.update&&(c.__dapiInfo=c.__dapiInfo||{},c.__dapiInfo.modifiedDate=c.modifiedDate,q=!0);for(e in m.outlines)m.outlines.hasOwnProperty(e)&&(f=m.outlines[e],b=f.download||f.update)&&(c=y(b,f.local,u.Outline),f.local=c,d.outlines[c.uuid]=c,f.download&&k.outlines.push(c),q=!0);for(e in m.directories)m.directories.hasOwnProperty(e)&&
(f=m.directories[e],b=f.download||f.update)&&(c=y(b,f.local,u.Directory),f.local=c,d.directories[c.uuid]=c,f.download&&k.directories.push(c),q=!0);0==k.directories.length&&delete k.directories;0==k.outlines.length&&delete k.outlines;0==k.topics.length&&delete k.topics;0==k.sources.length&&delete k.sources;k.directories||k.outlines||k.topics||k.sources||(k=null);0==n.topicsSources.length&&(n=null);return{save:q,downloaded:k,deleted:n}}catch(x){dji.logger.error(x)}}})(window.sru.userData.helper=window.sru.userData.helper||
{});
