window.sru=window.sru||{};
(function(h){function M(){sru.nacl.load(function(a){setTimeout(N,10)})}function N(){dji.fileSystem.initialize(function(a){dji.fileSystem.temporary.removeDirectory("/ocr",function(){dji.fileSystem.temporary.removeDirectory("/rewordify",function(){setTimeout(O,10)})})})}function O(){B(function(){setTimeout(P,10)})}function P(){dji.tts.initialize(function(a){setTimeout(Q,10)})}function C(a){if(sru.nacl.isInitialized())return a(!0);chrome.browserAction.setIcon({path:l.loading});sru.nacl.initialize(function(b){b&&
(sru.nacl.addEventListener("ocrfinished",R),sru.nacl.addEventListener("rewordifyfinished",S));chrome.browserAction.setIcon({path:l.inactive});a(b)})}function Q(){D(function(a){dji.login.silentAuth(function(b){b&&500!=b.code?0==b.code?a&&a.checksum!==b.user.checksum?E(a,function(){q(function(){setTimeout(u,10)})}):v(function(){q(function(){setTimeout(u,10)})}):E(a,function(){q(function(){setTimeout(u,10)})}):q(function(){setTimeout(u,10)})})})}function u(){dji.tabsManager.initialize(function(){dji.tabsManager.addTabCreatedListener(T);
dji.tabsManager.addTabChangedListener(U);dji.tabsManager.addTabUpdatedListener(V);dji.tabsManager.addTabRemovedListener(W);dji.tabsManager.addTabMessageListener(X);setTimeout(Y,10)})}function Y(){n.start=Z;n.progress=aa;n.stop=ba;n.error=ca;n.wait=da;sru.sync.setDelegate("checkSettingsUpdate",sru.userData.syncCheckSettingsUpdate);sru.sync.setDelegate("needSettingsData",sru.userData.syncNeedSettingsData);sru.sync.setDelegate("checkOutlinesUpdate",ea);sru.sync.setDelegate("needMeasurementsData",sru.userData.syncNeedMeasurementsData);
sru.sync.setDelegate("privacyModeAvailable",sru.userData.syncUpdatePrivacyMode);sru.sync.addEventListener("checkForUpdatesFinished",fa);sru.sync.addEventListener("settingsUpdateAvailable",sru.userData.syncSaveSettingsData);sru.sync.addEventListener("settingsUpdateAvailable",ga);sru.sync.addEventListener("outlinesUpdateAvailable",ha);sru.sync.addEventListener("measurementsSyncFinished",sru.userData.syncMeasurementsFinished);h.isLoggedIn()?(chrome.browserAction.setIcon({path:l.inactive}),sru.sync.start()):
chrome.browserAction.setIcon({path:l.notLoggedIn});chrome.browserAction.onClicked.addListener(ia);dji.logger.groupEnd();dji.logger.log('Background manager initialized for "'+chrome.runtime.getManifest().name+'" ('+chrome.runtime.id+")");e.loaded=!0;dji.tabsManager.broadcastTabMessage("com.donjohnston.sru.backgroundReady");dji.login.monitor({authRequired:F,signoutRequired:A});dji.proxy.init({onNotification:ja})}function ja(a){if(a){var b=dji.config.loginUrlSignature();"auth"===a.category&&(!a.hasOwnProperty("version")||
a.hasOwnProperty("version")&&2===a.version&&a.signature===b)&&("auth"===a.reason?F():"signout"===a.reason&&A())}}function F(){k||(k=!0,dji.login.userInfo(),dji.login.silentAuth(function(a){a&&500!=a.code?0==a.code?v(function(){q(function(){h.isLoggedIn()?(chrome.browserAction.setIcon({path:l.inactive}),sru.sync.start()):chrome.browserAction.setIcon({path:l.notLoggedIn});k=!1})}):(k=!1,dji.notifications.showByAuthCode(a.code)):(k=!1,dji.notifications.showByAuthCode(a?a.code:null))}))}function A(a){chrome.tabs.query({url:r.optionsPattern},
function(b){if(b&&0<b.length){for(var c=[],d=0;d<b.length;d++)c.push(b[d].id);chrome.tabs.remove(c,function(){h.signOut(a)})}else h.signOut(a)})}function G(a){dji.logger.log("Reload related websites:",a,dji.config.relatedUris());dji.proxy.broadcastNotification({category:"auth",version:2,reason:a?"auth":"signout",signature:dji.config.loginUrlSignature()});chrome.tabs.query({url:dji.config.relatedUris()},function(a){chrome.runtime.lastError&&dji.logger.error(chrome.runtime.lastError.message);if(a)for(var c=
0;c<a.length;c++){var d=a[c],g=new URL(d.url);chrome.tabs.update(d.id,{url:g.origin})}})}function H(){if(window.dji.tts.hasOnlineVoices()){var a=dji.login.isLoggedIn()?dji.login.userInfo():null;if(a&&a.checksum){var b=sru.userData.runtime.notification("new-voice");if(!b||!b.rejected&&b.displayed!=e.uuid){var c=sru.userData.settings.speechVoice(),d="";sru.userData.settings.translationEnabled()&&(d=sru.userData.settings.translationVoice()||"");var g=dji.tts.isGoogleVoice(c)&&dji.tts.isOnlineVoiceAllowed(),
m=dji.tts.isGoogleVoice(d)&&dji.tts.isOnlineVoiceAllowed(!0);if(g||m)b=b||{},b.displayed=e.uuid,sru.userData.runtime.notification("new-voice",b),dji.notifications.showNewVoices(function(){I()},function(){var a=g?window.dji.tts.onlineAlternativeForVoice(c):null,b=m?window.dji.tts.onlineAlternativeForVoice(d):null;a&&sru.userData.settings.speechVoice(a);b&&sru.userData.settings.translationVoice(b);(a||b)&&J()},function(){b=b||{};b.rejected=!0;sru.userData.runtime.notification("new-voice",b)})}}}}function ia(a){k||
(k=!0,dji.login.isLoggedIn()?e.on?(w(!e.on),k=!1):C(function(a){a&&w(!e.on);k=!1}):B(function(){dji.login.login(function(a){a?sru.userData.initialize(a.checksum,function(){sru.sync.start();v();x();C(function(a){a&&w(!0);k=!1;G(!0)})}):k=!1})}))}function w(a){e.on=a;e.on?(x(),y(null),chrome.browserAction.setIcon({path:l.active})):chrome.browserAction.setIcon({path:l.inactive});var b=dji.tabsManager.activeTab();t(b?b.tabId:-1);z(a)}function z(a,b,c){1==arguments.length&&"boolean"===typeof a&&(b=a,a=
null);if(b){var d=sru.userData.outlines.all();dji.tabsManager.sendTabMessage(a,"com.donjohnston.sru.syncUI",{outlinesVisible:p.outlinesVisible,outlines:d,outlinesUiPath:p.outlinesUiPath})}c||(d={active:b},b&&(d.outlineTemplates=sru.userData.outlineTemplates()),dji.tabsManager.sendTabMessage(a,"com.donjohnston.sru.activateExtension",d))}function I(){chrome.tabs.query({url:r.optionsPattern},function(a){if(a&&0<a.length){try{for(var b=0;b<a.length;b++)chrome.tabs.reload(a[b].id)}catch(c){dji.logger.error(c)}chrome.tabs.update(a[0].id,
{active:!0})}else chrome.tabs.create({url:r.options,active:!0})})}function t(a){chrome.tabs.get(a,function(b){var c="";e.on&&!sru.userData.privacyMode()&&sru.userData.settings.showReadability()&&f.hasOwnProperty(a)&&b&&b.url&&b.url!==r.optionsPattern&&0!==b.url.indexOf("chrome://")&&(f[a].measurements&&f[a].measurements.hasOwnProperty("averageGradeLevel")?(b=f[a].measurements.averageGradeLevel,c=1>b?"<1":Math.round(b)+""):c="...");dji.logger.log("Set badge text: ",a,", on:",e.on,", text: ",c);chrome.browserAction.setBadgeText({text:c})})}
function T(a){f[a]={session:dji.utils.generateUUID()}}function U(a,b){dji.tts.stop();b&&z(b,!1);e.on&&(z(a,!0),y(a));t(a)}function V(a,b,c){dji.tts.stop()}function W(a){delete f[a]}function X(a,b,c){dji.logger.log("Tab Message: tab id=",a,", Message=",b,", Params=",c);"com.donjohnston.sru.contentScriptReady"===b?ka(a,c):"com.donjohnston.sru.measure"===b?la(a,c):"com.donjohnston.sru.speak"===b?ma(a,c):"com.donjohnston.sru.stopSpeak"===b?dji.tts.stop():"com.donjohnston.sru.ocr"===b?na(a,c):"com.donjohnston.sru.rewordify"===
b?oa(a,c):"com.donjohnston.sru.translate"===b?K(a,c,!1):"com.donjohnston.sru.translateFromToolbar"===b?K(a,c,!0):"com.donjohnston.sru.searchCitations"===b?pa(a,c.searchData):"com.donjohnston.sru.outlines.dataUpdated"===b?sru.userData.outlines.updateDataFromUI(c):"com.donjohnston.sru.outlines.uiPathUpdated"===b?p.outlinesUiPath=c:"com.donjohnston.sru.ui.outlinesVisible"===b?p.outlinesVisible=c.outlinesVisible:"com.donjohnston.sru.options"===b?I():"com.donjohnston.sru.signOut"===b&&A(function(){})}
function ka(a,b){f[a]={session:dji.utils.generateUUID()};dji.tabsManager.setUserDataForTab(a,{uuid:b.uuid});e.on&&(y(a),z(a,!0));var c=dji.tabsManager.activeTab();c&&c.tabId===a&&t(a)}function la(a,b){var c=(f[a]||{}).session;sru.measurements.update({scope:sru.measurements.Scope.Page,uuid:b.uuid,timeSpent:b.timeSpent,text:b.text,isNew:b.isNew},null,function(b){if(b&&b.measurements&&f.hasOwnProperty(a)&&c===f[a].session){var g=f[a].measurements=f[a].measurements||{},m;for(m in b.measurements)b.measurements.hasOwnProperty(m)&&
(g[m]=b.measurements[m]);g=dji.tabsManager.activeTab();b.measurements.hasOwnProperty("averageGradeLevel")&&g&&g.tabId===a&&t(a)}})}function ma(a,b){var c="";if(b.hasOwnProperty("text"))c=text;else if(b.hasOwnProperty("parts"))for(var d=0;d<b.parts.length;d++)c+=" "+b.parts[d].text;if(!c||0>=c.length)return dji.tabsManager.sendPortMessage(a,"com.donjohnston.sru.tts.stop");sru.measurements.update({scope:sru.measurements.Scope.TTS,pageUuid:b.uuid,text:c,isNew:!0},function(c){dji.tts.speak(b.text||b.parts,
{tabId:a,ttsUuid:c,pageUuid:b.uuid},n)})}function Z(a){dji.tabsManager.sendPortMessage(a.tabId,"com.donjohnston.sru.tts.start")}function da(a){dji.tabsManager.sendPortMessage(a.tabId,"com.donjohnston.sru.tts.wait")}function aa(a,b){dji.tabsManager.sendPortMessage(b.tabId,"com.donjohnston.sru.tts.progress",{charIndex:a})}function ba(a,b){a.ttsUuid&&0<b?sru.measurements.update({scope:sru.measurements.Scope.TTS,uuid:a.ttsUuid,pageUuid:a.pageUuid,timeSpent:b},function(){dji.tabsManager.sendPortMessage(a.tabId,
"com.donjohnston.sru.tts.stop")}):dji.tabsManager.sendPortMessage(a.tabId,"com.donjohnston.sru.tts.stop")}function ca(a,b){dji.tabsManager.sendPortMessage(a.tabId,"com.donjohnston.sru.tts.error",{err:b.toString()})}function na(a,b){var c="/ocr/"+b.token+".png",d=c+".txt";dji.fileSystem.temporary.createDirectory("/ocr",function(){dji.screenshot.takeScreenshot({rect:b.rect,imageFormat:dji.screenshot.ImageFormats.PNG,fileSystem:dji.fileSystem.temporary,fileName:c},function(g,m,e){if(!g)return dji.tabsManager.sendPortMessage(a,
"com.donjohnston.sru.ocr",{token:b.token,data:null});c="/temporary"+c;d="/temporary"+d;dji.logger.log("Sending image to OCR: ",e);sru.nacl.ocr(b.token,c,d,{tabId:a,rect:b.rect,imageUrl:e})})})}function R(a,b,c,d,g){d=d.replace("/temporary","");dji.fileSystem.temporary.readFileAsBinaryString(d,function(a){if(a)try{a=JSON.parse(a),a.rect=g.rect}catch(c){a=null,dji.logger.error(c)}dji.logger.log(g);dji.logger.log(a);return dji.tabsManager.sendPortMessage(g.tabId,"com.donjohnston.sru.ocr",{token:b,data:a})})}
function oa(a,b){var c="/rewordify/"+b.token+"-in.txt",d="/rewordify/"+b.token+"-out.txt";dji.fileSystem.temporary.createDirectory("/rewordify",function(){dji.fileSystem.temporary.writeFile(c,b.text,function(g,e){var f=e?e.toURL():"";c="/temporary"+c;d="/temporary"+d;dji.logger.log("Sending text to Rewordify: ",f);sru.nacl.rewordify(b.token,sru.userData.settings.rewordifyLevel(),c,d,{tabId:a,inputFileUrl:f})})})}function S(a,b,c,d,g){d=d.replace("/temporary","");dji.fileSystem.temporary.readFileAsBinaryString(d,
function(a){if(a)try{a=JSON.parse(a)}catch(c){a=null,dji.logger.error(c)}dji.logger.log(g);dji.logger.log(a);return dji.tabsManager.sendPortMessage(g.tabId,"com.donjohnston.sru.rewordify",{token:b,data:a})})}function K(a,b,c){var d="com.donjohnston.sru.translate"+(c?"FromToolbar":"");"en"===sru.userData.settings.translationLanguage().abbr?dji.tabsManager.sendPortMessage(a,d,{result:JSON.stringify({translated:!1})}):jsdapi.translate.translateText(b.text,sru.userData.settings.translationLanguage().abbr,
function(b){if(!b||b.error)b=null;dji.tabsManager.sendPortMessage(a,d,{result:b})})}function pa(a,b){jsdapi.citations.search(b,function(b){if(!b||b.error)b=null;dji.tabsManager.sendTabMessage(a,"com.donjohnston.sru.searchCitations",b)})}function y(a){var b={colors:sru.userData.settings.colors(),autoSpeak:sru.userData.settings.speechAuto(),translationLanguage:sru.userData.settings.translationLanguage()};dji.tabsManager.sendTabMessage(a,"com.donjohnston.sru.settings",b)}function B(a){dji.fileSystem.persistent.readFile("env.config",
function(b){if(b)try{var c=JSON.parse(b),d=c.configName;for(b=0;b<c.configs.length;b++){var e=c.configs[b];e.name===d&&dji.config.update(e)}}catch(f){dji.logger.error(f)}jsdapi.http.setup({headers:{"x-dji-app-product":"sru","x-dji-app-platform":"chrome-extension","x-dji-app-os":dji.utils.os().name}});jsdapi.setServerUrl({login:dji.config.loginUrl(!0),dapi:dji.config.dapiUrl()});jsdapi.setRefreshTokenDelegate(dji.login.silentRefreshToken);jsdapi.setClientId(dji.config.clientID());jsdapi.translate.setServerUrl(dji.config.translateUrl());
jsdapi.citations.setServerUrl(dji.config.citationsUrl());a()})}function qa(a){dji.fileSystem.persistent.removeFile("/info",function(){a&&a()})}function v(a){var b=dji.login.userInfo(),b=b?JSON.stringify(b):"",b=CryptoJS.AES.encrypt(b,"#@$2sdfs%4wdfsdfgfsdada#$#$@#Qw");dji.fileSystem.persistent.writeFile("/info",b,function(){a&&a()})}function q(a){dji.login.isLoggedIn()?L(dji.login.userInfo(),a):D(function(b){b&&dji.login.userInfo(b);dji.login.isLoggedIn()?L(dji.login.userInfo(),a):a&&a()})}function D(a){dji.fileSystem.persistent.readFileAsBinaryString("/info",
function(b){var c=null;if(b&&0<b.length)try{(b=CryptoJS.AES.decrypt(b,"#@$2sdfs%4wdfsdfgfsdada#$#$@#Qw"))&&0<b.sigBytes&&(c=JSON.parse(CryptoJS.enc.Utf8.stringify(b)))}catch(d){dji.logger.error(d)}a(c)})}function L(a,b){a?sru.userData.initialize(a.checksum,function(){x();b&&b()}):b&&b()}function E(a,b){a?sru.userData.uninitialize(a.checksum,function(){qa(b)}):b&&b()}function fa(a){a.settingsUpdates||H()}function ga(a,b){b&&(x(),y(null),H(),J())}function ea(a){a=sru.userData.syncCheckOutlinesUpdate(a);
e.on&&a&&a.deleted&&dji.tabsManager.sendTabMessage(null,"com.donjohnston.sru.outlines.dataUpdated",{outlines:{"delete":a.deleted},outlinesUiPath:p.outlinesUiPath});return a?a.data:null}function ha(a){a=sru.userData.syncSaveOutlinesData(a);e.on&&a&&(a.downloaded||a.deleted)&&dji.tabsManager.sendTabMessage(null,"com.donjohnston.sru.outlines.dataUpdated",{outlines:{update:a.downloaded?sru.userData.outlines.all(a.downloaded):null,"delete":a.deleted}})}function x(){dji.tts.settings(sru.userData.settings.speech());
dji.tts.settings(sru.userData.settings.translation())}function J(){chrome.tabs.query({url:r.optionsPattern},function(a){try{for(var b=0;b<a.length;b++)chrome.tabs.reload(a[b].id)}catch(c){dji.logger.error(c)}})}var r={pattern:"chrome-extension://"+chrome.runtime.id+"/*",optionsPattern:"chrome-extension://"+chrome.runtime.id+"/options/options.html",options:"/options/options.html"},l={loading:{19:"../resources/graphics/sruLoading_19.png",38:"../resources/graphics/sruLoading_38.png"},notLoggedIn:{19:"../resources/graphics/sruNotLoggedIn_19.png",
38:"../resources/graphics/sruNotLoggedIn_38.png"},active:{19:"../resources/graphics/sruActive_19.png",38:"../resources/graphics/sruActive_38.png"},inactive:{19:"../resources/graphics/sruInactive_19.png",38:"../resources/graphics/sruInactive_38.png"}},e={uuid:dji.utils.generateUUID(),loaded:!1,on:!1},p={outlinesVisible:!1,outlinesUiPath:[]},n={start:null,progress:null,stop:null},k=!1,f={};h.isLoaded=function(){return e.loaded};h.isLoggedIn=function(){return dji.login.isLoggedIn()};h.userInfo=function(){return dji.login.userInfo()};
h.allowChanges=function(){return["<all>"]};h.initialize=function(){dji.logger.groupCollapsed("Initialize background manager");chrome.browserAction.setIcon({path:l.loading});chrome.browserAction.setBadgeBackgroundColor({color:"#777777"});M()};h.getMe=function(a){jsdapi.account.me(a)};h.applyActivationCode=function(a,b){jsdapi.account.applyActivationCode({activationCode:a},b)};h.signOut=function(a){dji.notifications.clearAll();dji.tts.stop();dji.tts.settings(null);for(var b in f)f.hasOwnProperty(b)&&
(f[b]={session:dji.utils.generateUUID()});b=dji.tabsManager.activeTab();t(b?b.tabId:-1);e.uuid=dji.utils.generateUUID();e.on&&w(!1);dji.tabsManager.broadcastTabMessage("com.donjohnston.sru.signout",{});sru.measurements.reset();sru.sync.stop();dji.login.silentSignout(function(b){if(b){p={outlinesVisible:!1,outlinesUiPath:[]};sru.userData.uninitialize();jsdapi.setAuth(null);if(a)try{a(b)}catch(d){dji.logger.error(d)}v(function(){chrome.browserAction.setIcon({path:l.notLoggedIn})});a&&G(!1)}else if(sru.sync.start(),
a)try{a(b)}catch(d){dji.logger.error(d)}})};__djiPdfExtSetGreenlightHandler(function(a){return!(k||!dji.login.isLoggedIn())})})(window.sru.backgroundManager=window.sru.backgroundManager||{});
