window.dji=window.dji||{};
(function(f){function r(a){d&&d.id==a&&(d=null,setTimeout(E,0))}function F(){chrome.windows.create({url:window.dji.config.loginUrl(),width:1E3,height:700,type:"popup"},function(a){d=a;chrome.windows.onRemoved.addListener(r)})}function t(a){k=a.url;chrome.windows.remove(d.id)}function u(a){if(a=dji.utils.jsonFromUrlQueryAndHash(a.url))a=a.query;if(a){if(a.hasOwnProperty("code"))try{a.code=parseInt(a.code)}catch(b){}if(a.hasOwnProperty("expires_at"))try{a.expires_at=parseInt(a.expires_at)}catch(b){}}setTimeout(m,0,
a);return{redirectUrl:"javascript:"}}function v(a){400<=a.statusCode&&-1==a.tabId&&0<a.frameId&&setTimeout(m,0,{code:a.statusCode})}function w(a){-1==a.tabId&&0<a.frameId&&(dji.logger.error(a),setTimeout(m,0,null))}function x(a){if(a=dji.utils.jsonFromUrlQueryAndHash(a.url))a=a.query;if(a){if(a.hasOwnProperty("code"))try{a.code=parseInt(a.code)}catch(b){}if(a.hasOwnProperty("expires_at"))try{a.expires_at=parseInt(a.expires_at)}catch(b){}}setTimeout(n,0,a);return{redirectUrl:"javascript:"}}function y(a){400<=
a.statusCode&&-1==a.tabId&&0<a.frameId&&setTimeout(n,0,{code:a.statusCode})}function z(a){-1==a.tabId&&0<a.frameId&&(dji.logger.error(a),setTimeout(n,0,null))}function A(a){if(a=dji.utils.jsonFromUrlQueryAndHash(a.url))a=a.query;if(a&&a.hasOwnProperty("code"))try{a.code=parseInt(a.code)}catch(b){}setTimeout(p,0,a);return{redirectUrl:"javascript:"}}function B(a){400<=a.statusCode&&-1==a.tabId&&0<a.frameId&&setTimeout(p,0,{code:a.statusCode})}function C(a){-1==a.tabId&&0<a.frameId&&(dji.logger.error(a),
setTimeout(p,0,null))}var G="https://"+chrome.runtime.id+".chromiumapp.org",H="https://"+chrome.runtime.id+".chromiumapp.org/auth/callback",I="https://"+chrome.runtime.id+".chromiumapp.org/silent/auth/callback?*",J="https://"+chrome.runtime.id+".chromiumapp.org/silent/token/refresh/callback",K="https://"+chrome.runtime.id+".chromiumapp.org/silent/token/refresh/callback?*",L="https://"+chrome.runtime.id+".chromiumapp.org/silent/signout/callback?*",D=/[?&](auth|lauth|sauth|signout)_stamp=97eb647a233b(&|#|$)/i,
d=null,l=null,g=!1,k=null,e=null,h=dji.utils.generateUUID(),q=dji.utils.generateUUID();f.monitor=function(a){a&&chrome.webRequest.onBeforeRequest.addListener(function(b){if(!(0>b.tabId)){var c=null;(0==b.url.indexOf("https://")||0==b.url.indexOf("http://"))&&0>b.url.indexOf(G)&&0<b.url.indexOf("_stamp=97eb647a233b")&&(c=new URL(b.url));if(c&&c.search&&(b=c.search.match(D)))if(b=b[1].toUpperCase(),"AUTH"==b||"LAUTH"==b)f.isLoggedIn()||a.authRequired();else if("SIGNOUT"==b&&(b=c.search.match(D))){c=
500;try{c=parseInt(b[1])}catch(d){dji.logger.error(d)}500!=c&&a.signoutRequired()}}},{urls:["<all_urls>"]})};f.userInfo=function(a){if(a)e=a;else return e};f.isLoggedIn=function(){return!g&&null!=e&&void 0!=e};f.login=function(a){if(g)return d&&chrome.windows.update(d.id,{focused:!0}),!1;if(e)try{a(e)}catch(b){Logger.instance.error(b)}else return g=!0,l=a,k=null,chrome.webRequest.onBeforeRequest.addListener(t,{urls:[H]}),F(),!0};f.silentAuth=function(a){var b=document.getElementById(h);if(b)return a(null);
b=document.createElement("iframe");b.setAttribute("id",h);b.__calback=a;b.src=window.dji.config.silentAuthUrl();chrome.webRequest.onBeforeRequest.addListener(u,{urls:[I]},["blocking"]);chrome.webRequest.onHeadersReceived.addListener(v,{urls:[window.dji.config.silentAuthUrl()]},["blocking"]);chrome.webRequest.onErrorOccurred.addListener(w,{urls:[window.dji.config.silentAuthUrl()]});document.body.appendChild(b)};f.silentSignout=function(a){var b=document.getElementById(h);if(b)return a(null);b=document.createElement("iframe");
b.setAttribute("id",h);b.__calback=a;b.src=window.dji.config.silentSignoutUrl();chrome.webRequest.onBeforeRequest.addListener(A,{urls:[L]},["blocking"]);chrome.webRequest.onHeadersReceived.addListener(B,{urls:[window.dji.config.silentAuthUrl()]},["blocking"]);chrome.webRequest.onErrorOccurred.addListener(C,{urls:[window.dji.config.silentSignoutUrl()]});document.body.appendChild(b)};f.isPreparing=function(){return g&&!d};f.windowId=function(){return d?d.id:null};f.silentRefreshToken=function(a,b){var c=
document.getElementById(q);if(c)return b(null);var d=a.login_url+"/silent/token/refresh?client_id="+encodeURIComponent(a.client_id)+"&refresh_token="+encodeURIComponent(a.refresh_token)+"&redirect_uri="+encodeURIComponent(J),c=document.createElement("iframe");c.setAttribute("id",q);c.__calback=b;c.src=d;chrome.webRequest.onBeforeRequest.addListener(x,{urls:[K]},["blocking"]);chrome.webRequest.onHeadersReceived.addListener(y,{urls:[d]},["blocking"]);chrome.webRequest.onErrorOccurred.addListener(z,
{urls:[d]});document.body.appendChild(c)};var E=function(){chrome.windows.onRemoved.removeListener(r);chrome.webRequest.onBeforeRequest.removeListener(t);d&&(chrome.windows.remove(d.id),d=null);var a=dji.utils.jsonFromUrlQueryAndHash(k);if((a=a?a.hash:null)&&a.access_token&&a.expires_at)jsdapi.setAuth(a),jsdapi.account.me(function(a){if(a&&!a.error){e=a;try{l(e)}catch(c){dji.logger.error(c)}l=k=null;g=!1}});else{try{l(e)}catch(b){dji.logger.error(b)}l=k=null;g=!1}},m=function(a){chrome.webRequest.onBeforeRequest.removeListener(u);
chrome.webRequest.onHeadersReceived.removeListener(v);chrome.webRequest.onErrorOccurred.removeListener(w);var b=document.getElementById(h);if(!b)return dji.log.error("Invalid state for silent auth.");var c=b.__calback;document.body.removeChild(b);if(!a||500==a.code)return c(null);0==a.code?(jsdapi.setAuth(a),jsdapi.account.me(function(b){if(b)if(b.error)switch(b.error){case 401:a.code=800002}else e=b,a.user=b;c(a)})):c(a)},n=function(a){chrome.webRequest.onBeforeRequest.removeListener(x);chrome.webRequest.onHeadersReceived.removeListener(y);
chrome.webRequest.onErrorOccurred.removeListener(z);var b=document.getElementById(q);if(!b)return dji.log.error("Invalid state for silent refresh.");var c=b.__calback;document.body.removeChild(b);c(a)},p=function(a){chrome.webRequest.onBeforeRequest.removeListener(A);chrome.webRequest.onHeadersReceived.removeListener(B);chrome.webRequest.onErrorOccurred.removeListener(C);var b=document.getElementById(h);if(!b)return dji.log.error("Invalid state for silent signout.");var c=b.__calback;document.body.removeChild(b);
if(!a||500==a.code)return c(!1);e=null;try{c(!0)}catch(d){dji.logger.error(d)}}})(window.dji.login=window.dji.login||{});
