window.sru=window.sru||{};
(function(g){function m(){localStorage.__nacl_loading_reason="timeout";localStorage.__nacl_loading_lastTimeout=c.timeout;dji.logger.log("Loading NaCl timeout:",c.timeout,"seconds!");dji.logger.groupEnd();e=b.NotLoadedm_state=b.NotLoaded;window.location.reload()}function n(){c.timer&&(clearTimeout(c.timer),c.timer=null);dji.logger.log("NaCl loaded: ",arguments);dji.logger.groupEnd();e=b.InitializePending;dji.utils.callListeners(d,"load",!0);d.load=[]}function p(){c.timer&&(clearTimeout(c.timer),c.timer=
null);dji.logger.error("NaCl error: ",arguments);if(e!=b.Ready){document.body.removeChild(f);f=null;dji.logger.groupEnd();var a=e;e=b.NotInitialized;a==b.Loading?dji.utils.callListeners(d,"load",!1):a==b.Initializing&&dji.utils.callListeners(d,"initialize",!1);d.load=[];d.initialize=[]}}function q(){c.timer&&(clearTimeout(c.timer),c.timer=null);dji.logger.error("NaCl crashed: ",arguments);if(e!=b.Ready){document.body.removeChild(f);f=null;dji.logger.groupEnd();var a=e;e=b.NotInitialized;a==b.Loading?
dji.utils.callListeners(d,"load",!1):a==b.Initializing&&dji.utils.callListeners(d,"initialize",!1);d.load=[];d.initialize=[]}}function r(a){try{dji.logger.log(a.data),a=JSON.parse(a.data)}catch(c){return dji.logger.error(c)}dji.logger.log(a);var h=a.params;"com.donjohnston.sru.chrome.message.initialize"===a.message?(e=a.params.success?b.Ready:b.InitializePending,dji.logger.groupEnd(),dji.utils.callListeners(d,"initialize",a.params.success),d.initialize=[]):"com.donjohnston.sru.chrome.message.ocr"===
a.message?(a=k[h.token],delete k[h.token],dji.logger.log("OCR Finished! Timestamp=",Date.now(),", info=",a),dji.utils.callListeners(d,"ocrfinished",h.success,h.token,h.inputFileName,h.outputFileName,a.userData)):"com.donjohnston.sru.chrome.message.rewordify"===a.message&&(a=l[h.token],delete l[h.token],dji.logger.log("Rewordify Finished! Timestamp=",Date.now(),", info=",a),dji.utils.callListeners(d,"rewordifyfinished",h.success,h.token,h.inputFileName,h.outputFileName,a.userData))}var b={NotLoaded:0,
Loading:1,InitializePending:2,Initializing:3,Ready:4},e=b.NotLoaded,f=null,d={load:[],initialize:[],ocrfinished:[],rewordifyfinished:[]},c={reason:"clean",timeout:0,step:6E4,timer:null},k={},l={};try{c.reason=localStorage.__nacl_loading_reason||"clean",c.timeout=Math.max(0,void 0===localStorage.__nacl_loading_lastTimeout?0:parseInt(localStorage.__nacl_loading_lastTimeout))}catch(a){dji.logger.error(a)}c.timeout=Math.min(3E5,c.timeout+c.step);localStorage.__nacl_loading_reason="clean";localStorage.__nacl_loading_lastTimeout=
0;g.isLoaded=function(){return b.Loading<e};g.isInitialized=function(){return b.Initializing<e};g.load=function(a){if(e==b.Ready)return dji.utils.callMethod(a,!0);if(e!=b.NotLoaded)return dji.utils.callMethod(a,!1);dji.logger.group("Load OCR module (reason=",c.reason,", timeout=",c.timeout,")");e=b.Loading;g.addEventListener("load",a);f=document.createElement("embed");f.id="chrome-ocr";f.src="../NativeClient/DjiSru-Chrome.nmf";f.type="application/x-pnacl";f.width=0;f.height=0;f.addEventListener("load",
n,!0);f.addEventListener("error",p,!0);f.addEventListener("crash",q,!0);f.addEventListener("message",r,!0);document.body.appendChild(f);try{if(f)for(var h in f)"--just-an-workarround--"===h&&dji.logger.log("--just-an-workarround--")}catch(d){}c.timer=setTimeout(m,c.timeout)};g.initialize=function(a){if(e==b.Ready)return dji.utils.callMethod(a,!0);if(e==b.Initializing)return dji.utils.callMethod(a,!1,!0);if(e!=b.InitializePending)return dji.utils.callMethod(a,!1);dji.logger.group("Initialize OCR engine");
e=b.Initializing;g.addEventListener("initialize",a);a={message:"com.donjohnston.sru.chrome.message.initialize",params:{"config-nacl-dir":"../NativeClient","config-language":"eng"}};a=JSON.stringify(a);f.postMessage(a)};g.addEventListener=function(a,b){dji.utils.addEventListener(d,a,b)};g.removeEventListener=function(a,b){dji.utils.removeEventListener(d,a,b)};g.ocr=function(a,c,d,g){e==b.Ready&&(k[a]={timestamp:Date.now(),token:a,inputFileName:c,outputFileName:d,userData:g},a={message:"com.donjohnston.sru.chrome.message.ocr",
params:k[a]},a=JSON.stringify(a),f.postMessage(a))};g.rewordify=function(a,c,d,g,k){e==b.Ready&&(l[a]={timestamp:Date.now(),token:a,format:"json",level:c,inputFileName:d,outputFileName:g,userData:k},a={message:"com.donjohnston.sru.chrome.message.rewordify",params:l[a]},a=JSON.stringify(a),f.postMessage(a))}})(window.sru.nacl=window.sru.nacl||{});
