window.dji=window.dji||{};
(function(d){function n(a){l=a;chrome.tabs.query({active:!0,windowId:a},function(a){var c=-1;0<a.length&&(c=a[0].id);g!==c&&(a=0>g?null:g,g=c,m(g,a))})}function p(a){e[a.id]={tabId:a.id,windowId:a.windowId,port:null,userData:null};a=a.id;for(var f=0;f<b.tabCreated.length;f++)h(b.tabCreated[f],a)}function q(a,f,c){if(a===g&&("loading"===f.status||"complete"===f.status))for(c=0;c<b.tabUpdated.length;c++)h(b.tabUpdated[c],a,f)}function r(a){if(g!==a.tabId){a.tabId in e?e[a.tabId].windowId=a.windowId:
e[a.tabId]={tabId:a.tabId,windowId:a.windowId,port:null,userData:null};var f=0>g?null:g;g=a.tabId;g!==f&&m(g,f)}}function t(a,f){if(a in e){var c=e[a].port;c in k&&delete k[c];delete e[a]}for(c=0;c<b.tabRemoved.length;c++)h(b.tabRemoved[c],a)}function u(a){if("__dji__sru_port"===a.name&&a.sender&&a.sender.tab){var f=a.sender.tab.id;f in e||(e[f]={tabId:f,windowId:a.sender.tab.windowId,port:null,userData:null});e[f].port=a;k[a]=f;a.onDisconnect.addListener(function(){f in e&&(e[f].port=null);a in k&&
delete k[a]});a.onMessage.addListener(function(a){var e=a.message;a=a.params;for(var d=0;d<b.tabMessage.length;d++)h(b.tabMessage[d],f,e,a)})}}function m(a,f){for(var c=0;c<b.tabChanged.length;c++)h(b.tabChanged[c],a,f)}function h(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(f){dji.logger.error(f)}}var e={},k={},l=-1,g=-1,b={tabCreated:[],tabChanged:[],tabUpdated:[],tabRemoved:[],tabMessage:[]};d.initialize=function(a){chrome.tabs.query({},function(f){chrome.windows.getCurrent(null,
function(c){if(c)for(l=c.id,c=0;c<f.length;c++){var b=f[c];e[b.id]={tabId:b.id,windowId:b.windowId,port:null,userData:null};b.active&&b.windowId===l&&(g=b.id)}chrome.windows.onFocusChanged.addListener(n);chrome.tabs.onCreated.addListener(p);chrome.tabs.onUpdated.addListener(q);chrome.tabs.onActivated.addListener(r);chrome.tabs.onRemoved.addListener(t);chrome.runtime.onConnect.addListener(u);setTimeout(a,0)})})};d.activeTab=function(){return 0>g?null:e[g]};d.activeTabId=function(){return 0>g?null:
g};d.userDataForTab=function(a){return e.hasOwnProperty(a)?e[a].userData:null};d.setUserDataForTab=function(a,b){e.hasOwnProperty(a)&&(e[a].userData=b)};d.sendTabMessage=function(a,b,c){a=a||g;0<=a&&chrome.tabs.sendMessage(a,{message:{message:b,params:c}})};d.broadcastTabMessage=function(a,b){chrome.tabs.query({},function(c){for(var d=0;d<c.length;d++)chrome.tabs.sendMessage(c[d].id,{message:{message:a,params:b}})})};d.broadcastTabMessageEx=function(a,b,c){chrome.tabs.query({},function(d){for(var e=
0;e<d.length;e++)e!==a&&chrome.tabs.sendMessage(d[e].id,{message:{message:b,params:c}})})};d.sendPortMessage=function(a,b,c){a=a||g;0<=a&&e.hasOwnProperty(a)&&e[a].port&&e[a].port.postMessage({message:b,params:c})};d.addTabCreatedListener=function(a){a&&"function"===typeof a&&-1===b.tabCreated.indexOf(a)&&b.tabCreated.push(a)};d.removeTabCreatedListener=function(a){a&&"function"===typeof a&&(a=b.tabCreated.indexOf(a),-1!==a&&b.tabCreated.splice(a,1))};d.addTabChangedListener=function(a){a&&"function"===
typeof a&&-1===b.tabChanged.indexOf(a)&&b.tabChanged.push(a)};d.removeTabChangedListener=function(a){a&&"function"===typeof a&&(a=b.tabChanged.indexOf(a),-1!==a&&b.tabChanged.splice(a,1))};d.addTabUpdatedListener=function(a){a&&"function"===typeof a&&-1===b.tabUpdated.indexOf(a)&&b.tabUpdated.push(a)};d.removeTabUpdatedListener=function(a){a&&"function"===typeof a&&(a=b.tabUpdated.indexOf(a),-1!==a&&b.tabUpdated.splice(a,1))};d.addTabRemovedListener=function(a){a&&"function"===typeof a&&-1===b.tabRemoved.indexOf(a)&&
b.tabRemoved.push(a)};d.removeTabRemovedListener=function(a){a&&"function"===typeof a&&(a=b.tabRemoved.indexOf(a),-1!==a&&b.tabRemoved.splice(a,1))};d.addTabMessageListener=function(a){a&&"function"===typeof a&&-1===b.tabMessage.indexOf(a)&&b.tabMessage.push(a)};d.removeTabMessageListener=function(a){a&&"function"===typeof a&&(a=b.tabMessage.indexOf(a),-1!==a&&b.tabMessage.splice(a,1))}})(window.dji.tabsManager=window.dji.tabsManager||{});
