window.dji=window.dji||{};window.dji.textStatistics=window.dji.textStatistics||{};
(function(f){function h(){return Math.round(10*(b/e*.39+c/b*11.8-15.59))/10}function l(){return Math.round(10*(d/b*5.89-e/b*.3-15.8))/10}function m(){return Math.round(10*(d/b*4.71+b/e*.5-21.43))/10}function n(a){a=a.trim();a=decodeURIComponent(encodeURI(a));a=a.replace("\u00e2\u0080\u0098","'").replace("\u00e2\u0080\u0099","'").replace("\u00e2\u0080\u009c",'"').replace("\u00e2\u0080\u009d",'"').replace("\u00e2\u0080\u0093","-").replace("\u00e2\u0080\u0094","--").replace("\u00e2\u0080\u00a6","...");
a=a.replace(String.fromCharCode(145),"'").replace(String.fromCharCode(146),"'").replace(String.fromCharCode(147),'"').replace(String.fromCharCode(148),'"').replace(String.fromCharCode(150),"-").replace(String.fromCharCode(151),"--").replace(String.fromCharCode(133),"...");a=a.replace(/([^0-9][0-9]+)\.([0-9]+[^0-9])/mig,"$10$2");a=a.replace(/<script(.*?)>(.*?)<\/script>/gi,"").replace(/<\/(address|blockquote|center|dir|div|dl|dd|dt|fieldset|form|h1|h2|h3|h4|h5|h6|menu|noscript|ol|p|pre|table|ul|li)?[^>]*>/gi,
".");a=a.replace(/<[^>]+>/g,"");a=a.replace(/&quot;/gi,'"').replace(/&#039;/gi,"'").replace(/&gt;/gi,">").replace(/&lt;/gi,"<").replace(/&amp;/gi,"&");a=a.replace(/(\r\n|\n\r)/gi,"\n").replace(/(\r|\n){2,}/gi,".\n\n").replace(/[ ]*(\n|\r\n|\r)[ ]*/gi," ");a=a.replace(/[",:;()\/\\`-]/g," ");"."!=a[a.length-1]&&"!"!=a[a.length-1]&&"?"!=a[a.length-1]&&(a+=".");a=a.replace(/[\.!?]/g,".").replace(/([\.\s]*\.[\.\s]*)/mg,". ").replace(/[ ]+/g," ").replace(/([\.])[\. ]+/g,"$1").replace(/[ ]*([\.])/g,"$1 ");
a=a.trim();a=a.replace(/\. [^\. ]/g,function(a){return a.toLowerCase()});return a.trim()}function k(a,b){var c=0;b=!1===b?!1:!0;a.split(/\s+/).forEach(function(a){(!a.match(/^[A-Z]/)||b)&&2<window.dji.textStatistics.syllables.count(a)&&c++});return c}var g="",b=null,c=null,e=null,d=null,p=null,r=null,t=null;f.analyzeText=function(a){g=n(a);0==g.trim().length?b=0:(a=g.match(/n't/g),b=(a?a.length:0)+1+g.replace(/[^ ]/g,"").length);a=0;for(var f=g.split(/\s+/),q=0;q<f.length;q++)a+=window.dji.textStatistics.syllables.count(f[q]);
c=a;e=0==g.trim().length?0:g.replace(/[^\.!?]/g,"").length||1;d=g.replace(/[^a-z]+/ig,"").length;p=k(g,!1);r=Math.round(b/e*10)/10;t=p/b*100;return{fleschKincaidReadingEase:Math.round(10*(206.835-b/e*1.015-c/b*84.6))/10,fleschKincaidGradeLevel:h(),gunningFogScore:Math.round(4*(r+t))/10,colemanLiauIndex:l(),smogIndex:Math.round(10.43*Math.sqrt(30/e*p+3.1291))/10,automatedReadabilityIndex:m(),averageGradeLevel:Math.round((h()+Math.round(4*(r+t))/10+l()+Math.round(10.43*Math.sqrt(30/e*p+3.1291))/10+
m())/5*10)/10,letterCount:d,sentenceCount:e,wordCount:b,totalSyllables:c,averageLettersPerWord:Math.round(d/b*10)/10,averageSyllablesPerWord:Math.round(c/b*10)/10,averageWordsPerSentence:Math.round(b/e*10)/10}}})(window.dji.textStatistics=window.dji.textStatistics||{});
(function(f){f.count=function(b){b=b.trim();if(0==b.length)return 0;b=b.replace(/[^A-Za-z']/g,"").toLowerCase();if(h.hasOwnProperty(b))return h[b];var c=window.dji.textStatistics.pluralise.getSingular(b);if(c!=b&&h.hasOwnProperty(c))return h[c];for(var e=0,d,c=0;c<n.length;c++)d=n[c],b.match(d)&&(b=b.replace(d,""),e++);for(c=0;c<k.length;c++)d=k[c],b.match(d)&&(b=b.replace(d,""),e+=2);for(c=0;c<g.length;c++)d=g[c],b.match(d)&&(b=b.replace(d,""),e+=3);if(h.hasOwnProperty(b))return h[b];c=window.dji.textStatistics.pluralise.getSingular(b);
if(c!=b&&h.hasOwnProperty(c))return h[c];d=0;for(var f=b.split(/[^aeiouy]+/ig),c=0;c<f.length;c++)""!=f[c]&&d++;d+=e;for(c=0;c<l.length;c++)e=l[c],b.match(e)&&d--;for(c=0;c<m.length;c++)e=m[c],b.match(e)&&d++;return d||1};var h={abalone:4,abare:3,abed:2,abruzzese:4,abbruzzese:4,aborigine:5,acreage:3,adame:3,adieu:2,adobe:3,anemone:4,apache:3,aphrodite:4,apostrophe:4,ariadne:4,cafe:2,calliope:4,catastrophe:4,chile:2,chloe:2,circe:2,colonel:2,colonelcy:3,coyote:3,daphne:2,epitome:4,eurydice:4,euterpe:3,
forever:3,gethsemane:4,guacamole:4,hyperbole:4,jesse:2,jukebox:2,hermione:4,karate:3,machete:3,maybe:2,people:2,penelope:4,persephone:4,phoebe:2,recipe:3,sesame:3,shoreline:2,simile:3,syncope:3,tamale:3,wednesday:2,yosemite:4,zoe:2},l=[/cia(l|$)/,/tia/,/cius/,/cious/,/[^aeiou]giu/,/[aeiouy][^(aeiouy|s|sh|t)]ion/,/iou/,/eous$/,/sia$/,/[aio]gue$/,/.[^aeiuoycgltdb]{2,}ed$/,/.ely$/,/^jua/,/uai/,/eau/,/([^aeiouy]|^)[aeiouy](b|c|ch|d|dg|f|g|gh|gn|k|l|ll|lv|m|mm|n|nc|ng|nn|p|r|rc|rg|rn|rs|rv|s|sc|sk|sl|squ|ss|st|t|th|v|y|z)e$/,
/([^aeiouy]|^)[aeiouy](b|c|ch|dg|f|g|gh|gn|k|l|lch|ll|lv|m|mm|n|nc|ng|nch|nn|p|r|rc|rg|rn|rs|rv|s|sc|sk|sl|squ|ss|th|v|y|z)ed$/,/([^aeiouy]|^)[aeiouy](b|ch|d|f|gh|gn|k|l|lch|ll|lv|m|mm|n|nch|nn|p|r|rn|rs|rv|s|sc|sk|sl|squ|st|t|th|v|y)es$/,/^busi$/,/que(tte)?$/,/[aeiouy]ise$/,/[aeiou]ppes?$/],m=[/([^s]|^)ia/,/riet/,/dien/,/diev/,/iu/,/([^(s|sh|t)]|^)io/,/eo($|[b-df-hj-np-tv-z])/,/ii/,/[ou]a$/,/[aeiouym]bl$/,/[aeiou]{3}/,/[aeiou]y[aeiou]/,/^mc/,/ism$/,/asm$/,/thm$/,/([^aeiouy])\1l$/,/[^l]lien/,/^coa[dglx]./,
/[^gq]ua[^auieo]/,/dnt$/,/uity$/,/[^aeiouy]ie(r|st|t)$/,/[^aeiouy](e|u)ings?$/,/[aeiouy]sh?e[rs]$/,/iell/,/dea$/,/real/,/[^aeiou]y[ae]/,/gean$/,/[^q]ue(n|st)/,/n't$/],n=[/^un/,/^fore/,/^ware/,/^none?/,/^out/,/^post/,/^sub/,/^pre/,/^pro/,/^dis/,/^side/,/ly$/,/less$/,/some$/,/ful$/,/ers?$/,/ness$/,/cians?$/,/ments?$/,/[^(qu)]ettes?$/,/villes?$/,/ships?$/,/sides?$/,/ports?$/,/shires?$/,/tion(ed|s)?$/,/ics?$/,/ists?$/],k=[/^above/,/^ant[ie]/,/^counter/,/^hyper/,/^afore/,/^agri/,/^in[ft]ra/,/^inter/,/^over/,
/^semi/,/^ultra/,/^under/,/^extra/,/^dia/,/^micro/,/^mega/,/^kilo/,/^pico/,/^nano/,/^macro/,/berry$/,/woman$/,/women$/],g=[/ology$/,/ologist$/,/onomy$/,/onomist$/]})(window.dji.textStatistics.syllables=window.dji.textStatistics.syllables||{});
(function(f){f.getSingular=function(f){var k,g=f.toLowerCase();if(-1<m.indexOf(g)||l.hasOwnProperty(g))return f;for(k in l)if(l.hasOwnProperty(k)&&g==l[k])return f;for(k in h)if(h.hasOwnProperty(k)&&(f=new RegExp(k,"i"),g.match(f)))return g.replace(f,h[k])};var h={"(quiz)zes$":"$1","(matr)ices$":"$1ix","(vert|ind)ices$":"$1ex","^(ox)en$":"$1","(alias)es$":"$1","(octop|vir)i$":"$1us","(cris|ax|test)es$":"$1is","(shoe)s$":"$1","(o)es$":"$1","(bus)es$":"$1","([m|l])ice$":"$1ouse","(x|ch|ss|sh)es$":"$1",
"(m)ovies$":"$1ovie","(s)eries$":"$1eries","([^aeiouy]|qu)ies$":"$1y","([lr])ves$":"$1f","(tive)s$":"$1","(hive)s$":"$1","(li|wi|kni)ves$":"$1fe","(shea|loa|lea|thie)ves$":"$1f","(^analy)ses$":"$1sis","((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$":"$1$2sis","([ti])a$":"$1um","(n)ews$":"$1ews","(h|bl)ouses$":"$1ouse","(corpse)s$":"$1","(us)es$":"$1",s$:""},l={child:"children",foot:"feet",goose:"geese",man:"men",mouse:"mice",move:"moves",person:"people",sex:"sexes",tooth:"teeth"},m=
"beef bison buffalo carbon chemistry copper geometry gold cs css deer equipment fish furniture information mathematics money moose nitrogen oxygen rice series sheep species surgery traffic water".split(" ")})(window.dji.textStatistics.pluralise=window.dji.textStatistics.pluralise||{});
