window.dji=window.dji||{};
(function(g){function H(a,b){chrome.tts.getVoices(function(d){dji.logger.log("try to detect voices: ",a);if(l.chrome&&(null===d||0>=d.length))setTimeout(function(){chrome.tts.speak("",{onEvent:function(c){"end"!==c.type&&"error"!==c.type||setTimeout(function(){H(a+1,b)},"end"===c.type?10:1E4)}},null)},10);else{for(var c="Heather Ryan Graham Lucy SOLO Flite Acapela".split(" "),e=!1,f=[],D=0;D<d.length;D++){for(var h=d[D],t=!1,m=0;m<c.length;m++)if(-1<h.voiceName.indexOf(c[m])){t=!0;break}t||(0>h.voiceName.indexOf("Google")&&
h.extensionId&&(e=!0),f.push(h))}if(e)if(l.chrome)for(d=0;d<f.length;d++)0>f[d].voiceName.indexOf("Google")&&k.push(f[d]);else k=f.slice(0);else k=f.slice(0);for(f=0;f<k.length;f++)I(k[f],!1);g.cacheOnlineVoices(function(){for(var a=0;a<k.length;a++){var c=k[a],d=c.extras,f=x[d.lang]=x[d.lang]||{},f=f[d.culture]=f[d.culture]||{};(f[d.gender]=f[d.gender]||[]).push(c)}setTimeout(function(){dji.logger.groupEnd();z(b,!0)},0)})}})}function J(){h.voice=g.defaultVoice();h.translationVoice=null;h.rate=h.pitch=
h.volume=1}function r(a){for(var b=0;b<k.length;b++)if(k[b].voiceName===a)return k[b];return null}function E(a){a=r(a);return!!a}function I(a,b){var d=(a.lang||"neutral").split("-"),c=(2<=d.length?d[1]:"").toUpperCase(),e=(a.gender||"neutral").toLowerCase();a.extras={langInfo:dji.languages.languageInfo(d[0]),lang:(d[0]||"").toLowerCase(),culture:c,gender:e,isGoogle:g.isGoogleVoice(a.voiceName),isMicrosoft:g.isMicrosoftVoice(a.voiceName),isOnline:!!b}}function K(a,b,d,c,e){for(var f=null,g=null,h=
null,t=0;t<b.length;t++){var m=b[t];m===a||!d&&m.extras.isOnline||!c&&!m.extras.isOnline||(d&&!f&&m.extras.isOnline&&(f=m),!c||g||m.extras.isOnline||m.extras.isGoogle||(g=m),e&&!h&&m.extras.isGoogle&&(h=m))}return g||h||f||null}function A(a,b,d,c,e){var f=b[a.extras.gender]||[],f=K(a,f,d,c,e);if(!f)for(var g in b)if(g!==a.extras.gender&&b.hasOwnProperty(g)&&(f=b[g]||[],f=K(a,f,d,c,e)))break;return f||null}function F(a){if((a=r(a))&&!a.extras.isOnline)return a.voiceName;if(!a||"en"===a.extras.lang)return g.defaultVoice(!0);
var b=a.extras,d=x[b.lang]||{},c=d[b.culture]||{},c=A(a,c,!1,!0,!0);if(!c)for(var e in d)if(e!==b.culture&&d.hasOwnProperty(e)&&(c=d[e]||{},c=A(a,c,!1,!0,!0)))break;return c?c.voiceName:g.defaultVoice(!0)}function G(){null!==B&&(clearTimeout(B),B=null)}function L(a){if(void 0===a||null===a||1>a.length||0===a.trim().length)return!1;for(var b=!1,d=0;d<a.length;d++){var c=a.charAt(d);if(!dji.charSet.wordSeparator.characterIsMember(c)){b=!0;break}}return b}function M(a,b,d,c){var e,f,g=[];f=b||0;for(b=
0;b<a.length;b++){e=a[b].text;var h=!!a[b].isTranslated,t=[],m;m=(m=a[b].isTranslated?c:d)?m.extras.isGoogle?200:2E4:-1;f=f||0;if(0>m)t.push({offset:f,text:e,isTranslated:h});else{var k=0,p=0,l=0,n=null;do{p=e;l=k;n=m;if(0>n||6*(p.length-l)<=n)p=Math.max(0,p.length-1);else{for(var q=p.length,v=0,r=0,u=0,w=l;l<q&&v<n;l++){u=p.charCodeAt(l);if(127>=u)r=1;else if(2047>=u)r=2;else if(65535>=u)r=3;else for(r=4;u>>6*r;)r++;if(n<v+r)break;v+=r;w=l}p=w}p=l=p;if(p<e.length-1)for(p=l;k<=p&&(n=e.charAt(p),!dji.charSet.wordSeparator.characterIsMember(n));p--);
p<=k&&(p=l);t.push({offset:f+k,text:e.substring(k,p+1),isTranslated:h});k=p+1}while(k<e.length)}0<t.length&&(f=t[t.length-1].offset+t[t.length-1].text.length);e=t;g=g.concat(e)}return g}function N(a,b,d,c){c=r(h.voice);var e=r(h.translationVoice);a={chunks:M(a,0,c,e),isSpoken:!1,cancel:!1,userData:b,listener:d,settings:JSON.parse(JSON.stringify(h))};n.push(a);w&&1!==n.length||(a.isSpoken=C(a))}function C(a){var b=!w;w||(w=!0);if(0>=a.chunks.length||0>=a.settings.volume)return a.cancel=!0,setTimeout(y,
0,a),!0;a.startTime=Date.now();var d=a.chunks[0],c=d.isTranslated?a.settings.translationVoice:a.settings.voice,e=window.dji.tts_service.isOnlineVoice(c);b&&(u(a.listener,"wait",a.userData),e||u(a.listener,"start",a.userData));if(!L(d.text)||!c||"No Voice"===c)return setTimeout(y,0,a),!0;dji.logger.log("__doSpeak using voice:",c," (translated:",d.isTranslated,") / settings:",JSON.stringify(a.settings,!0,2));e?O(a,d,c):chrome.tts.speak(d.text,{voiceName:c,rate:a.settings.rate,pitch:a.settings.pitch,
volume:a.settings.volume,onEvent:function(b){"interrupted"===b.type||"cancelled"===b.type||"error"===b.type?(a.cancel=!0,y(a)):"end"===b.type?y(a):"start"!==b.type&&"word"!==b.type||u(a.listener,"progress",b.charIndex+a.chunks[0].offset,-1,a.userData)}});return!0}function O(a,b,d){var c=!1,e=0;window.dji.tts_service.onStart=function(){u(a.listener,"start",a.userData);u(a.listener,"progress",b.offset,-1,a.userData)};window.dji.tts_service.onProgress=function(c,d){e=d;u(a.listener,"progress",c+b.offset,
d+b.offset,a.userData)};window.dji.tts_service.onStop=function(){if(!c||0>=b.text.substring(e).trim().length)return setTimeout(y,10,a);var d=a.settings.voice,g=a.settings.translationVoice,h=e,k=F(a.settings.voice),m=F(a.settings.translationVoice),l=r(k),p=r(m);a.settings.voice=k;a.settings.translationVoice=m;a.chunks[0].text=a.chunks[0].text.substring(h);a.chunks=M(a.chunks,h,l,p);dji.logger.warning("Switching from Online to Local voice: ["+d+", "+g+"] -> ["+a.settings.voice+", "+a.settings.translationVoice+
"]");setTimeout(C,0,a)};window.dji.tts_service.onError=function(b){c=!0;u(a.listener,"error",a.userData,b)};window.dji.tts_service.play(b.text,d,{pitch:Math.max(0,100*h.pitch-50),rate:Math.max(0,100*h.rate-50),volume:100*h.volume})}function y(a){if(a&&!a.cancel&&1<a.chunks.length)return a.chunks.splice(0,1),C(a);w=!1;if(a&&-1!==n.indexOf(a)&&(n.splice(0,1),0===n.length)){var b=Date.now()-a.startTime;u(a.listener,"stop",a.userData,b)}for(;0<n.length&&(a=n[0],!a.isSpoken)&&(a.isSpoken=C(a),!a.isSpoken);)n.splice(0,
1),u(a.listener,"stop",a.userData,0)}function z(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){dji.logger.error(b)}}function u(a,b){if(a&&a[b])try{a[b].apply(a,[].slice.call(arguments).splice(2))}catch(d){dji.logger.error(d)}}var l=dji.utils.os(),h={voice:null,translationVoice:null,rate:1,pitch:1,volume:1},k=[],v=[],x={},B=null,w=!1,n=[];g.initialize=function(a){if(0<k.length)return z(a,!0);J();dji.logger.group("Initialize TTS");H(1,a)};g.settings=function(a){if(void 0===a)return{voice:h.voice,
translationVoice:h.translationVoice,rate:100*h.rate,pitch:100*h.pitch,volume:100*h.volume};if(null===a)J();else if(!a.voice||E(a.voice))a.voice&&(h.voice=a.voice),a.translationVoice&&(h.translationVoice=a.translationVoice),void 0!==a.rate&&null!==a.rate&&(h.rate=a.rate/100),void 0!==a.pitch&&null!==a.pitch&&(h.pitch=a.pitch/100),void 0!==a.volume&&null!==a.volume&&(h.volume=a.volume/100)};g.voices=function(a){if(a)return k;for(var b=[],d=g.isOnlineVoiceAllowed(a),c=0;c<k.length;c++)a=k[c],!d&&a.extras.isOnline||
b.push(a);return b};g.voicesMap=function(){return x};g.hasVoice=E;g.defaultVoice=function(a){if(l.mac)return"Alex";if(!l.windows&&!a&&g.onlineServiceAllowed()){if(E("Michael (Online)"))return"Michael (Online)";if(0<v.length)return v[0].voiceName}for(var b=null,d=null,c=null,e=null,f=null,h=null,n=null,t=null,m=null,r=null,p=null,u=null,w=0;w<k.length;w++){var q=k[w];if(!a||!q.extras.isOnline){var x=(q.lang||"").toUpperCase();"EN-US"===x?(b||(b=q.voiceName),!n&&q.extras.isMicrosoft&&l.windows&&(n=
q.voiceName)):"EN-GB"===x?(d||(d=q.voiceName),!t&&q.extras.isMicrosoft&&l.windows&&(t=q.voiceName)):"EN-CA"===x&&(c||(c=q.voiceName),!m&&q.extras.isMicrosoft&&l.windows&&(m=q.voiceName));0<=q.voiceName.indexOf("English")&&(h||(h=q.voiceName),!u&&q.extras.isMicrosoft&&l.windows&&(u=q.voiceName),0<=q.voiceName.indexOf("US")?(e||(e=q.voiceName),!r&&q.extras.isMicrosoft&&l.windows&&(r=q.voiceName)):0<=q.voiceName.indexOf("UK")&&(f||(f=q.voiceName),!p&&q.extras.isMicrosoft&&l.windows&&(p=q.voiceName)))}}return l.windows?
r?r:n?n:p?p:t?t:m?m:u||"native":e?e:b?b:f?f:d?d:c?c:h||""};g.defaultVoiceForLanguage=function(a){a=(dji.languages.languageCode_639_1(a)||"").toUpperCase();if(0>=a.length||"EN"===a)return g.defaultVoice();var b,d,c;for(c=0;c<k.length;c++)if(b=k[c],!b.extras.isOnline&&!b.extras.isGoogle&&(d=(b.lang||"").toUpperCase(),0===d.indexOf(a)))return b.voiceName;if(g.onlineServiceAllowed())for(c=0;c<v.length;c++)if(b=v[c],d=(b.lang||"").toUpperCase(),0===d.indexOf(a))return b.voiceName;var e=null,f=null;for(c=
0;c<k.length;c++)b=k[c],d=(b.lang||"").toUpperCase(),0===d.indexOf(a)&&(e||(e=b.voiceName),!f&&b.extras.isGoogle&&(f=b.voiceName));return f?f:e||""};g.isGoogleVoice=function(a){if(!a)return!1;a=a.toUpperCase();return 0<=a.indexOf("GOOGLE")||0<=a.indexOf("CHROME")};g.isMicrosoftVoice=function(a){if(!a)return!1;a=a.toUpperCase();return 0<=a.indexOf("MICROSOFT")};g.isOnlineVoice=function(a){a=r(a);return!(!a||!a.extras.isOnline)};g.onlineServiceAllowed=function(){return!!(window.dji.config.env().permissive||
l.windows||l.chrome)};g.hasOnlineVoices=function(){return g.onlineServiceAllowed()&&0<v.length};g.cacheOnlineVoices=function(a){0>=v.length&&g.onlineServiceAllowed()?window.dji.tts_service.loadVoices(function(b){if(0>=v.length&&(v=b||[],0<v.length)){for(b=0;b<v.length;b++)I(v[b],!0);k=k.concat(v)}z(a,0<v.length)}):z(a,0<v.length)};g.isOnlineVoiceAllowed=function(a){return g.onlineServiceAllowed()?l.chrome||l.windows&&a?!0:!!window.dji.config.env().permissive:!1};g.voicesForLanguage=function(a,b){for(var d=
[],c=g.voices(b),e=0;e<c.length;e++){var f=c[e];f.lang&&0===f.lang.indexOf(a)&&d.push(f)}return d};g.localAlternativeForVoice=F;g.onlineAlternativeForVoice=function(a){var b=r(a);if(b&&b.extras.isOnline)return b.voiceName;if(!b||"en"===b.extras.lang)return g.defaultVoice(!1);var d=b.extras,c=x[d.lang]||{},e=c[d.culture]||{},e=A(b,e,!0,!1,!1);if(!e)for(var f in c)if(f!==d.culture&&c.hasOwnProperty(f)&&(e=c[f]||{},e=A(b,e,!0,!1,!1)))break;return e?e.voiceName:a};g.voiceSupportsSettings=function(a){a=
r(a);return!(!a||a.extras.isOnline&&!a.adjustable)};g.speak=function(a,b,d,c){(c=!!c)||g.stop();G();"string"===typeof a?a=[{text:a,isTranslated:!1}]:a instanceof Array||(a=null);a&&0<a.length&&N(a,b,d,c)};g.scheduleSpeak=function(a,b,d,c,e){L(a)&&(b?g.stop():G(),B=setTimeout(function(){N([{text:a,isTranslated:!1}],c,e)},d||200))};g.stop=function(){G();0<n.length&&(w?(n.splice(1,n.length-1),n[0].cancel=!0,chrome.tts.stop(),window.dji.tts_service.stop()):n.splice(0,n.length))}})(window.dji.tts=window.dji.tts||
{});
