window.sru=window.sru||{};
(function(e){var t,u;function x(a,b,c){if(a&&0!=a.length)for(var d,k=b?m.directories:m.outlines,f=0;f<a.length;f++)b=a[f],d=k[b.uuid],c?d&&(d.deleted=!0):(d||(d={uuid:b.uuid,creationDate:b.creationDate},k[b.uuid]=d),d.parentUuid=b.parentUuid,d.title=b.title||"Untitled",d.modifiedDate=b.modifiedDate)}function D(a,b){if(a&&0!=a.length)for(var c,d,k=m.topics,f=0;f<a.length;f++)c=a[f],d=k[c.uuid],b?d&&(d.deleted=!0):(d||(d={uuid:c.uuid,outlineUuid:c.outlineUuid,creationDate:c.creationDate,linkedSources:{}},
k[c.uuid]=d),d.parentUuid=c.parentUuid,d.location=c.location,d.body=c.body,d.modifiedDate=c.modifiedDate)}function E(a,b){if(a&&0!=a.length)for(var c,d,k=m.sources,f=0;f<a.length;f++)c=a[f],d=k[c.uuid],b?d&&(d.deleted=!0):(d||(d={uuid:c.uuid,outlineUuid:c.outlineUuid,creationDate:c.creationDate,boundToOutline:c.boundToOutline,fromHighlight:c.fromHighlight},k[c.uuid]=d),d.data=c.data,d.modifiedDate=c.modifiedDate)}function F(a,b){if(a&&0!=a.length)for(var c,d,k,f,e=m.topics,g=0;g<a.length;g++){c=a[g];
k=c.sourcesUuids;c=e[c.topicUuid];d=c.linkedSources;for(var l=0;l<k.length;l++)if(b){if(f=d[k[l]])f.deleted=!0}else f=d[k[l]]||{},f.modifiedDate=c.modifiedDate,delete f.deleted,d[k[l]]=f}}function G(){b={color:{text:"#000000",sentenceHighlight:"#FF0000",wordHighlight:"#00FF00"},speech:{voice:dji.tts.defaultVoice(),autoSpeak:1,volume:100,rate:100,pitch:100},rewordify:{level:"1"},measurements:{showReadability:!1},translation:{language:{name:"English",abbr:"en"},translationVoice:""},__fileInfo:{},__data:{}};
b.__fileInfo.creationDate=b.__fileInfo.modifiedDate=Date.now();b.__fileInfo.modifiedUuid=dji.utils.generateUUID();b.__fileInfo.version=0;z();g={current:{},history:{}};m={version:1,directories:{},outlines:{},topics:{},sources:{}};t=null;u={}}function p(a){var n=v;a||(A(),b.__fileInfo.modifiedDate=Date.now(),b.__fileInfo.modifiedUuid=dji.utils.generateUUID());dji.fileSystem.persistent.writeFile(h.settingsFileName,JSON.stringify(b,null,"  "),function(){a||n!==v||(A(),q.settings.timer=setTimeout(L,q.settings.timeout))})}
function B(a){dji.fileSystem.persistent.writeFile(h.measurementsFileName,JSON.stringify(g),a)}function y(a){var b=v;a||w();var c=JSON.stringify(m,null,"  ");dji.fileSystem.persistent.writeFileAsText(h.outlinesFileName,c,function(){a||b!==v||(w(),q.outlines.timer=setTimeout(M,q.outlines.timeout))})}function N(a){dji.fileSystem.persistent.readFile(h.settingsFileName,function(n){if(n&&0<n.length){try{b=JSON.parse(n);if(null===b.translation||void 0===b.translation)b.translation={language:{name:"English",
abbr:"en"},translationVoice:""};b.__data&&b.__data.common&&b.__data.common.translation&&delete b.__data.common.translation;b.measurements||(b.measurements={showReadability:!1})}catch(c){dji.logger.error(c)}z()}b.hasOwnProperty("__privacyMode")||(b.__privacyMode=!1);b.__privacyMode?dji.fileSystem.persistent.readFile(h.measurementsFileName,function(b){if(b&&0<b.length)try{g=JSON.parse(b),H()}catch(d){dji.logger.error(d)}I(a)}):I(a)})}function I(a){dji.fileSystem.persistent.readFile(h.outlinesFileName,
function(b){if(b&&0<b.length)try{b=JSON.parse(b);b.hasOwnProperty("version")&&(m=b);var c=b.outlines;if(c)for(var d in c)if(c.hasOwnProperty(d)){var k=c[d];k.title||(k.title="Untitled")}var f=b.topics;if(f)for(var e in f)if(f.hasOwnProperty(e)){var g=f[e].linkedSources;if(g)for(var l in g)g.hasOwnProperty(l)&&(b.sources&&b.sources.hasOwnProperty(l)||delete g[l])}}catch(h){dji.logger.error(h)}r(a)})}function z(){dji.tts.hasVoice(b.speech.voice)||(b.speech.voice=dji.tts.defaultVoice());e.settings.translationEnabled()&&
!dji.tts.hasVoice(b.translation.translationVoice)&&(b.translation.translationVoice=dji.tts.defaultVoiceForLanguage(b.translation.language.abbr))}function A(){q.settings.timer&&(clearTimeout(q.settings.timer),q.settings.timer=null)}function w(){q.outlines.timer&&(clearTimeout(q.outlines.timer),q.outlines.timer=null)}function J(){var a=null;b.__data?(a=JSON.parse(JSON.stringify(b.__data)),a.common=a.common||{},a.platform=a.platform||{},a.platform.chrome=a.platform.chrome||{}):a={common:{},platform:{chrome:{}}};
a.common.color=b.color;a.common.translationLanguage=b.translation.language;a.common.speech=a.common.speech||{};a.common.speech.autoSpeak=b.speech.autoSpeak;var n=a.common.rewordify||{};n.level=b.rewordify.level;a.common.rewordify=n;n=a.common.measurements||{};n.showReadability=!!b.measurements.showReadability;a.common.measurements=n;var n=a.platform.chrome[C.name]||{},c=n.speech||{};c.voice=b.speech.voice;c.volume=b.speech.volume;c.rate=b.speech.rate;c.pitch=b.speech.pitch;n.speech=c;n.translationVoice=
b.translation.translationVoice;a.platform.chrome[C.name]=n;return a=JSON.stringify(a)}function L(){var a=J();sru.sync.enqueueUserSettings(b.__fileInfo,a)}function H(){for(var a in g.history)if(g.history.hasOwnProperty(a)){var b=g.history[a],c=g.current[a];c||(c={},g.current[a]=c);for(var d in b){var e=b[d],f=c[d];if(f){e.timeSpent+=f.timeSpent;for(var h in f)"timeSpent"!==h&&f.hasOwnProperty(h)&&(e[h]=f[h])}c[d]=e}}g.history={}}function M(){w();var a=sru.userData.helper.syncPrepareOutlinesUpdate(m,
{},!1);a&&(a.save&&y(!0),a.data&&sru.sync.enqueueOutlinesData(a.data))}function r(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){dji.logger.error(b)}}var C=dji.utils.os(),v=dji.utils.generateUUID(),K={},b={color:{text:"#000000",sentenceHighlight:"#FF0000",wordHighlight:"#00FF00"},speech:{voice:"",autoSpeak:1,volume:100,rate:100,pitch:100},rewordify:{level:"1"},measurements:{showReadability:!1},translation:{language:{name:"English",abbr:"en"},translationVoice:""},__fileInfo:{},
__data:{},__privacyMode:!1},g={current:{},history:{}},m={version:1,directories:{},outlines:{},topics:{},sources:{}};t=null;u={};var h={userDir:"/Users/Demo",settingsFileName:"/Users/Demo/settings.txt",measurementsFileName:"/Users/Demo/measurements.txt",outlinesFileName:"/Users/Demo/outlines.txt"},q={settings:{timeout:300,timer:null},outlines:{timeout:1E3,timer:null}};e.initialize=function(a,b){v=dji.utils.generateUUID();h.userDir=a?"/Users/"+a:null;h.settingsFileName=a?h.userDir+"/settings.txt":null;
h.measurementsFileName=a?h.userDir+"/measurements.txt":null;h.outlinesFileName=a?h.userDir+"/outlines.txt":null;G();t="notification-"+a;try{var c=localStorage[t];c&&(c=JSON.parse(localStorage[t]))&&(u=c)}catch(d){}a?dji.fileSystem.persistent.createDirectory(h.userDir,function(a){N(b)}):r(b)};e.uninitialize=function(a,b){var c=a?"/Users/"+a:h.userDir;a||(A(),w(),h.userDir=null,h.settingsFileName=null,v=dji.utils.generateUUID(),G());c?dji.fileSystem.persistent.removeDirectory(c,b):b&&r(b)};e.dump=function(){dji.logger.dump("****************** _data.dump BEGIN ************************\n"+
JSON.stringify(m,null,"    ")+"****************** _data.dump END ************************\n")};e.runtime={};e.runtime.notification=function(a,b){if(a)if(b)u[a]=b,localStorage[t]=JSON.stringify(u);else return u[a]};e.settings={};e.settings.colors=function(){return b.color};e.settings.textColor=function(a){if(a)b.color.text!=a&&(b.color.text=a,p());else return b.color.text};e.settings.sentenceHighlightColor=function(a){if(a)b.color.sentenceHighlight!=a&&(b.color.sentenceHighlight=a,p());else return b.color.sentenceHighlight};
e.settings.wordHighlightColor=function(a){if(a)b.color.wordHighlight!=a&&(b.color.wordHighlight=a,p());else return b.color.wordHighlight};e.settings.speechVoice=function(a){if(a)b.speech.voice!=a&&(b.speech.voice=a,p());else return b.speech.voice};e.settings.speechAuto=function(a){if(null!==a&&void 0!==a)b.speech.autoSpeak!=a&&(b.speech.autoSpeak=a,p());else return b.speech.autoSpeak};e.settings.speechVolume=function(a){if(null!==a&&void 0!==a)b.speech.volume!=a&&(b.speech.volume=a,p());else return b.speech.volume};
e.settings.speechRate=function(a){if(null!==a&&void 0!==a)b.speech.rate!=a&&(b.speech.rate=a,p());else return b.speech.rate};e.settings.speechPitch=function(a){if(null!==a&&void 0!==a)b.speech.pitch!=a&&(b.speech.pitch=a,p());else return b.speech.pitch};e.settings.speech=function(){return b.speech};e.settings.rewordifyLevel=function(a){if(null!==a&&void 0!==a)b.rewordify.level!=a&&(b.rewordify.level=a,p());else return b.rewordify.level};e.settings.showReadability=function(a){if(null!==a&&void 0!==
a)b.measurements.showReadability!==a&&(b.measurements.showReadability=!!a,p());else return!!b.measurements.showReadability};e.settings.translationEnabled=function(){return!(!b.translation.language||!b.translation.language.name||"ENGLISH"==b.translation.language.name.toUpperCase())};e.settings.translationLanguage=function(a){if(null!==a&&void 0!==a)b.translation.language!=a&&(b.translation.language=a,p());else return b.translation.language};e.settings.translationVoice=function(a){if(a)b.translation.translationVoice!=
a&&(b.translation.translationVoice=a,p());else return b.translation.translationVoice};e.settings.translation=function(){return b.translation};e.privacyMode=function(){return b.__privacyMode};e.measurements={};e.measurements.update=function(a,e,c,d){if(b.__privacyMode)return r(d,null);e=e||dji.utils.generateUUID();var k=g.current[a];k||(k={},g.current[a]=k);if(a=k[e]){a.timeSpent+=c.timeSpent;for(var f in c)"timeSpent"!==f&&c.hasOwnProperty(f)&&(a[f]=c[f])}else k[e]=c;B(function(){r(d,e)})};e.outlines=
{};e.outlines.all=function(a){var b={directories:[],outlines:[],topics:[],sources:[]},c,d,e,f,g,h,l;a=a||m;e=b.directories;c=a.directories;for(g in c)d=c[g],d.deleted||(f={uuid:d.uuid,parentUuid:d.parentUuid,title:d.title,creationDate:d.creationDate,modifiedDate:d.modifiedDate},e.push(f));e=b.outlines;c=a.outlines;for(g in c)d=c[g],d.deleted||(f={uuid:d.uuid,parentUuid:d.parentUuid,title:d.title,creationDate:d.creationDate,modifiedDate:d.modifiedDate},e.push(f));e=b.topics;c=a.topics;for(g in c)if(d=
c[g],!d.deleted){f={uuid:d.uuid,outlineUuid:d.outlineUuid,parentUuid:d.parentUuid,location:d.location,body:d.body,creationDate:d.creationDate,modifiedDate:d.modifiedDate,sourcesUuids:[]};for(h in d.linkedSources)l=d.linkedSources[h],l.deleted||f.sourcesUuids.push(h);e.push(f)}e=b.sources;c=a.sources;for(g in c)d=c[g],d.deleted||(f={uuid:d.uuid,outlineUuid:d.outlineUuid,boundToOutline:d.boundToOutline,fromHighlight:d.fromHighlight,data:d.data,creationDate:d.creationDate,modifiedDate:d.modifiedDate},
e.push(f));return b};e.outlines.updateDataFromUI=function(a){a.update&&(x(a.update.directories,!0,!1),x(a.update.outlines,!1,!1),D(a.update.topics,!1),E(a.update.sources,!1),F(a.update.topicsSources,!1));a["delete"]&&(x(a["delete"].directories,!0,!0),x(a["delete"].outlines,!1,!0),D(a["delete"].topics,!0),E(a["delete"].sources,!0),F(a["delete"].topicsSources,!0));(a.update||a["delete"])&&y(!1)};e.syncUpdatePrivacyMode=function(a){return b.__privacyMode!==a?(dji.logger.log("__syncUpdatePrivacyMode",
a,"has changed"),(b.__privacyMode=a)&&(g={current:{},history:{}}),p(!0),!0):!1};e.syncCheckSettingsUpdate=function(a){return a?b.__fileInfo.version<a.version?sru.sync.ActionType.Download:a.modifiedDate<b.__fileInfo.modifiedDate?sru.sync.ActionType.Upload:sru.sync.ActionType.None:sru.sync.ActionType.Upload};e.syncNeedSettingsData=function(){return{fileInfo:JSON.parse(JSON.stringify(b.__fileInfo)),data:J()}};e.syncSaveSettingsData=function(a,e){if(a||e){a&&(b.__fileInfo.creationDate=a.creationDate,
b.__fileInfo.modifiedDate=a.modifiedDate,b.__fileInfo.modifiedUuid=a.modifiedUuid,b.__fileInfo.version=a.version);if(e){var c=e.common||{},d=c.color||{},g=c.rewordify||{},f=c.measurements||{},h=c.speech||{},m,l;c.translationLanguage&&(m=c.translationLanguage);c=e.platform||{};c=c.chrome||{};c=c[C.name]||{};c.translationVoice&&(l=c.translationVoice);c=c.speech||{};b.color.text=d.text||b.color.text;b.color.sentenceHighlight=d.sentenceHighlight||b.color.sentenceHighlight;b.color.wordHighlight=d.wordHighlight||
b.color.wordHighlight;null!==h.autoSpeak&&void 0!==h.autoSpeak&&(b.speech.autoSpeak=h.autoSpeak);b.speech.voice=c.voice||b.speech.voice;null!==c.volume&&void 0!==c.volume&&(b.speech.volume=c.volume);null!==c.rate&&void 0!==c.rate&&(b.speech.rate=c.rate);null!==c.pitch&&void 0!==c.pitch&&(b.speech.pitch=c.pitch);null!==g.level&&void 0!==g.level&&(b.rewordify.level=g.level);null!==f.showReadability&&void 0!==f.showReadability&&(b.measurements.showReadability=f.showReadability);l&&50<l?(b.translation=
{language:{name:"English",abbr:"en"},translationVoice:""},dji.logger.warn("syncSaveUserSettings: reset translation because of invalid translate voice!")):(null!==m&&void 0!==m&&(b.translation.language=m),null!==l&&void 0!==l&&(b.translation.translationVoice=l));e.common&&e.common.translation&&delete e.common.translation;z();b.__data=e}p(!0)}};e.syncNeedMeasurementsData=function(a){var e=!1;if(!b.__privacyMode)for(var c in g.current)if(g.current.hasOwnProperty(c)){e=!0;break}if(e){var d=g.history=
g.current;g.current={};B(function(){r(a,d)})}else r(a,null)};e.syncMeasurementsFinished=function(a,b){a?g.history={}:H();B(b)};e.syncCheckOutlinesUpdate=function(a){w();return(a=sru.userData.helper.syncPrepareOutlinesUpdate(m,a,!0))?(a.save&&y(!0),a):null};e.syncSaveOutlinesData=function(a){return(a=sru.userData.helper.syncPrepareOutlinesSave(m,a))?(a.save&&y(!0),a):null};(function(){var a=new XMLHttpRequest;a.open("GET",chrome.extension.getURL("resources/data/outline-template.json"),!0);a.onreadystatechange=
function(){if(a.readyState==XMLHttpRequest.DONE&&200==a.status){var b=a.responseText;try{K=JSON.parse(b)}catch(c){dji.logger.error("Error: ",c)}}};a.send()})();e.outlineTemplates=function(){return K}})(window.sru.userData=window.sru.userData||{});
