window.sru=window.sru||{};
(function(Y){function h(){window!==window.top||dji.utils.isLoginApp()||(window.dji.ui.effects.initialize(),sru.mainContainer.initialize(t))}function t(){sru.toolbar.initialize();sru.toolbar.addEventListener("speak",u);sru.toolbar.addEventListener("screenshot",v);sru.toolbar.addEventListener("rewordify",w);sru.toolbar.addEventListener("translate",x);sru.toolbar.addEventListener("showOutlines",y);sru.toolbar.addEventListener("highlight",z);sru.outlines.initialize();sru.outlines.addEventListener("searchSources",A);
sru.outlines.addEventListener("options",B);sru.outlines.addEventListener("signOut",C);sru.outlinesDataManager.addEventListener("dataUpdated",D);sru.outlinesDataManager.addEventListener("uiPathUpdated",E);sru.speech.initialize();sru.speech.addEventListener("activate",F);sru.speech.addEventListener("start",G);sru.speech.addEventListener("stop",H);sru.screenSelection.initialize();sru.screenSelection.addEventListener("activate",I);sru.screenSelection.addEventListener("deactivate",J);sru.screenSelection.addEventListener("selectionDone",
K);sru.screenSelection.addEventListener("resultsProcessed",L);dji.rewordify.initialize();dji.rewordify.addEventListener("process",M);dji.rewordify.addEventListener("activate",N);dji.rewordify.addEventListener("deactivate",O);dji.rewordify.addEventListener("resultsProcessed",P);dji.rewordify.addEventListener("translateText",Q);f.isPdf&&sru.helpers.pdfViewer.addEventListener("newTextAvailable",R);dji.translate.initialize();dji.translate.addEventListener("translateFromToolbar",S);dji.translate.addEventListener("translateDone",
T);dji.translate.addEventListener("deactivate",U);document.addEventListener("load",V,!0);chrome.runtime.onMessage.addListener(W);n(!0);d("com.donjohnston.sru.contentScriptReady",{uuid:e})}function W(a,b,c){a.message?p(a.message):dji.logger.log("Request: "+JSON.stringify(a))}function p(a){if("com.donjohnston.sru.log"===a.message)dji.logger.warning("BM_LOG:",a.params.message);else if("com.donjohnston.sru.backgroundReady"===a.message)n(!0),g.postMessage({message:"com.donjohnston.sru.contentScriptReady",
params:{uuid:e}});else if("com.donjohnston.sru.signout"===a.message)q();else if("com.donjohnston.sru.activateExtension"===a.message){if(a.params.active){if(!c.running){var b=null;c.initialized?(c.running=!0,c.timestamp=Date.now(),c.timer=setTimeout(m,c.timeout),f.isPdf&&(b=sru.helpers.pdfViewer.text(!0))&&0<b.length&&d("com.donjohnston.sru.measure",{uuid:e,text:b})):(b=f.isPdf?sru.helpers.pdfViewer.text(!0):f.isBookshare?sru.helpers.bookshare.text():dji.utils.extractVisibleTextFromElement(document.body),
d("com.donjohnston.sru.measure",{uuid:e,text:b,isNew:!0}),c.initialized=!0,c.running=!0,c.timestamp=Date.now(),c.timer=setTimeout(m,c.timeout))}}else c.running&&(b=Date.now()-c.timestamp,clearTimeout(c.timer),c.timer=null,c.running=!1,c.timestamp=0,0<b&&d("com.donjohnston.sru.measure",{uuid:e,timeSpent:b}));sru.mainContainer.show(a.params.active);a.params.active?sru.outlines.outlineTemplates(a.params.outlineTemplates):(sru.screenSelection.activate(!1),sru.outlines.setData(null,null))}else if("com.donjohnston.sru.settings"==
a.message)dji.selectionMapper.setColors(a.params.colors.text,a.params.colors.wordHighlight),r=a.params.autoSpeak,sru.screenSelection.setAutoSpeak(r),dji.translate.toggleTranslateButton(a.params.translationLanguage.name);else if("com.donjohnston.sru.ocr"==a.message)sru.screenSelection.processDone(a.params.token,a.params.data);else if("com.donjohnston.sru.rewordify"==a.message)dji.rewordify.processDone(a.params.token,a.params.data);else if("com.donjohnston.sru.translate"==a.message)dji.rewordify.processTranslationDone(a.params.result);
else if("com.donjohnston.sru.translateFromToolbar"==a.message)dji.translate.processTranslationDone(a.params.result);else if("com.donjohnston.sru.tts.start"==a.message)sru.speech.speakStart();else if("com.donjohnston.sru.tts.wait"==a.message)sru.speech.speakWait();else if("com.donjohnston.sru.tts.progress"==a.message)sru.speech.speakProgress(a.params);else if("com.donjohnston.sru.tts.stop"==a.message)sru.speech.speakStop();else if("com.donjohnston.sru.tts.error"==a.message)sru.speech.speakError(a.params.err);
else if("com.donjohnston.sru.syncUI"===a.message)sru.outlines.setData(a.params.outlines,a.params.outlinesUiPath),sru.toolbar.expandOutlinesPanel(a.params.outlinesVisible);else if("com.donjohnston.sru.outlines.dataUpdated"===a.message)sru.outlines.updateData(a.params.outlines,a.params.outlinesUiPath);else if("com.donjohnston.sru.searchCitations"===a.message)if(b=a.params?a.params.sources:null)sru.outlines.onSearchSourcesFinished(b,a.params.catalog);else sru.outlines.onSearchSourcesFinished(null,null)}
function d(a,b){g.postMessage({message:a,params:b})}function n(a){g&&(g.disconnect(),g=null);a&&(g=chrome.runtime.connect({name:"__dji__sru_port"}),g.onMessage.addListener(p))}function u(){sru.speech.isActive()?sru.speech.stop():sru.speech.start()}function v(){sru.speech.stop();var a=!sru.screenSelection.isActive();a?(dji.rewordify.activate(!1),sru.toolbar.enableButtons(!1,!0,!1,!1,!1),sru.toolbar.activateButtons(!1,!0,!1,!1,!1)):(sru.toolbar.enableButtons(!0,!0,!0,!0,!0,!0),sru.toolbar.activateButtons(!1,
!1,!1,!1,!1));sru.screenSelection.activate(a)}function w(){sru.speech.stop();var a=!dji.rewordify.isActive();a&&(sru.toolbar.enableButtons(!1,!1,!0,!1,!1),sru.toolbar.activateButtons(null,null,!0,!1,null));dji.rewordify.activate(a)}function x(){sru.speech.stop();var a=!dji.translate.isActive();a?(sru.toolbar.enableButtons(!1,!1,!1,!0,!1),sru.toolbar.activateButtons(null,null,null,!0,null)):(sru.toolbar.enableButtons(!0,!0,!0,!0,!0),sru.toolbar.activateButtons(null,null,null,!1,null));dji.translate.activate(a)}
function z(a){var b=!sru.outlines.isHighlightActive();sru.outlines.activateHighlight(b);var c=sru.screenSelection.isActive(),d=dji.translate.isActive(),e=dji.rewordify.isActive();b?sru.outlines.startHighlight()||(sru.toolbar.enableButtons(!1,!1,!1,!1,!0),sru.toolbar.activateButtons(!1,c,null,null,!0)):(sru.toolbar.enableButtons(!0,d||e?!1:!0,d?!1:!0,e?!1:!0,1==a?!1:!0),sru.toolbar.activateButtons(null,null,null,null,!1))}function y(a){sru.screenSelection.isActive()&&sru.screenSelection.activate(!1);
dji.rewordify.isActive()&&dji.rewordify.activate(!1,!0);dji.translate.isActive()&&dji.translate.activate(!1,!0);d("com.donjohnston.sru.ui.outlinesVisible",{outlinesVisible:a})}function F(a){var b=!a,c=!a,d=!a,e=!a;c&&(dji.rewordify.isActive()||dji.translate.isActive())&&(c=!1);b&&dji.translate.isActive()&&(b=!1);d&&dji.rewordify.isActive()&&(d=!1);e&&sru.toolbar.isHighlightActive()&&(e=!1);sru.toolbar.enableButtons(null,c,b,d,e);sru.toolbar.activateButtons(a,null,null,null,null)}function G(a){"string"===
typeof a?a={uuid:e,text:a}:a instanceof Array&&(a={uuid:e,parts:a});d("com.donjohnston.sru.speak",a)}function H(){d("com.donjohnston.sru.stopSpeak")}function I(){}function J(){sru.speech.stop();k?(sru.toolbar.enableButtons(!1,!1,null,!1,!1),sru.toolbar.activateButtons(!1,!1,null,!1)):sru.outlines.isHighlightActive()?(sru.toolbar.enableButtons(!1,!1,!1,!1,!0),sru.toolbar.activateButtons(!1,!1,!1,!1,!0)):(dji.rewordify.activate(!1),sru.toolbar.enableButtons(!0,!0,!0,!0,!0),sru.toolbar.activateButtons(!1,
!1,!1,!1))}function K(a,b){dji.logger.log("Screen selection done: ",b);d("com.donjohnston.sru.ocr",{token:a,rect:b})}function L(){sru.outlines.isHighlightActive()||(sru.toolbar.enableButtons(!0,null,!0,!0,!0),sru.toolbar.activateButtons(!1,null,!1,!1))}function N(){}function O(){sru.screenSelection.isActive()?(sru.toolbar.enableButtons(!0,!0,!0,!0,!0),sru.toolbar.activateButtons(null,null,!1,!1)):(sru.speech.stop(),sru.toolbar.enableButtons(!0,!0,!0,!0,!0),sru.toolbar.activateButtons(!1,!1,!1,!1));
k=!1}function M(a,b){try{k=sru.screenSelection.isActive()}catch(c){dji.logger.error(c)}sru.toolbar.enableButtons(!0,!1,null,!1,!0);d("com.donjohnston.sru.rewordify",{text:a,token:b})}function P(a){a&&k&&(sru.screenSelection.activate(!1),sru.toolbar.enableButtons(!0,!1,null,!1,!0))}function Q(a){d("com.donjohnston.sru.translate",{text:a})}function S(a,b){d("com.donjohnston.sru.translateFromToolbar",{text:a,token:b})}function T(a){sru.outlines.isHighlightActive()||(sru.toolbar.enableButtons(!0,!1,!1,
!0,!0),sru.toolbar.activateButtons(null,null,null,!0))}function U(){sru.speech.stop();sru.toolbar.enableButtons(!0,!0,!0,!0,!0);sru.toolbar.activateButtons(!1,null,null,!1)}function D(a){d("com.donjohnston.sru.outlines.dataUpdated",a)}function E(a){d("com.donjohnston.sru.outlines.uiPathUpdated",a)}function A(a){d("com.donjohnston.sru.searchCitations",{searchData:a})}function B(){d("com.donjohnston.sru.options",{})}function C(){d("com.donjohnston.sru.signOut",{})}function V(){dji.utils.isIframeFree()||
((new MutationObserver(l)).observe(document.body,{childList:!0}),l())}function l(){for(var a=dji.utils.findValidIframeElements(),b=0;b<a.length;b++){var c=a[b];try{c.removeEventListener("load",l)}catch(d){}X.apply(c);c.addEventListener("load",l)}}function X(){if(dji.utils.validateIframe(this)){var a=this.contentDocument;if(a.head){var b=a.getElementById("dji-sru-css-speech");b||(b=a.createElement("link"),b.id="dji-sru-css-speech",b.rel="stylesheet",b.type="text/css",b.async=!0,b.href=chrome.extension.getURL("contentScripts/speech.css"),
a.head.appendChild(b),b=a.createElement("link"),b.id="dji-sru-css-rewordify",b.rel="stylesheet",b.type="text/css",b.async=!0,b.href=chrome.extension.getURL("contentScripts/rewordify.css"),a.head.appendChild(b))}}}function m(){var a=Date.now(),b=a-c.timestamp;c.timestamp=a;0<b&&b<=2*c.timeout&&d("com.donjohnston.sru.measure",{uuid:e,timeSpent:b});c.timer=setTimeout(m,c.timeout)}function R(){if(c.running){var a=sru.helpers.pdfViewer.text(!0);a&&0<a.length&&d("com.donjohnston.sru.measure",{uuid:e,text:a})}}
function q(){c={initialized:!1,running:!1,timestamp:0,timer:null,timeout:1E4}}dji.logger.logLevel(dji.logger.levels.NONE);var g=null,r=!1,k=!1,e=dji.utils.generateUUID(),c={initialized:!1,running:!1,timestamp:0,timer:null,timeout:1E4},f={isPdf:dji.utils.isSruPdf(),isBookshare:dji.utils.isBookshareBook(),isAmazonKindle:dji.utils.isAmazonKindle()};q();f.isPdf?sru.helpers.pdfViewer.initialize(h):f.isBookshare?sru.helpers.bookshare.initialize(h):f.isAmazonKindle?sru.helpers.amazonKindle.initialize(h):
h()})(window.sru.contentScriptManage=window.sru.contentScriptManage||{});
