window.sru=window.sru||{};
(function(h){function m(a,c,b){b&&(__$('.dji-sru-outline-dialog-element[id!="dji-sru-0"]').remove(),b=__$('.dji-sru-outline-dialog-element[id="dji-sru-0"]'),__$(b.find(".dji-sru-btnDialogMove")[0]).removeClass("dji-sru-disabled"));for(b=0;b<a.length;b++){var d=c,e=a[b];if(e){var f=dji.ui.templates.load(k,"template-outline-dialog-element");d.appendChild(f);f.outline=e;f.id=e.uuid();__$(f).find(".dji-sru-outline-dialog-title").val(e.title());0<sru.outlinesDataManager.directories(e).length&&(d=f.querySelector(".dji-sru-subfolders"),
m(sru.outlinesDataManager.directories(e),d),d.style.display="block")}}}function q(a){if(!__$(a.target).hasClass("dji-sru-outline-dialog-title")||__$(a.target).is("[readonly]"))a=__$(a.currentTarget).closest(".dji-sru-outline-dialog-element-header"),n(),a.hasClass("dji-sru-folder-selected")?a.removeClass("dji-sru-folder-selected"):a.addClass("dji-sru-folder-selected")}function n(){__$(".dji-sru-folder-selected").removeClass("dji-sru-folder-selected")}function r(a){a=e.querySelector(".dji-sru-folder-selected");
var c=__$(a).closest(".dji-sru-outline-dialog-element")[0];if(c&&!g){a=dji.ui.templates.load(k,"template-outline-dialog-element");var b=__$(a).find(".dji-sru-outline-dialog-title");b.removeAttr("readonly");g=!0;setTimeout(function(){b.focus()},0);b.on("blur",t).on("keydown",u);"dji-sru-0"===c.id?e.querySelector(".dji-sru-dialog-content").appendChild(a):(c=c.querySelector(".dji-sru-subfolders"),c.style.display="block",c.appendChild(a))}}function t(a){a.target.setAttribute("readonly","true");setTimeout(function(){var c=
a.target,b=__$(c).closest(".dji-sru-outline-dialog-element")[0];g=!1;if(""==c.value)b.parentNode.removeChild(b);else if(!b.id){var d=__$(c).closest(".dji-sru-subfolders")[0],d=d?__$(d).closest(".dji-sru-outline-dialog-element")[0].outline:null,c=sru.outlinesDataManager.createDirectory(c.value,d);b.id=c.uuid();b.outline=c;d||(p=!0)}},0)}function u(a){"keydown"==a.type&&13==a.keyCode&&a.target.blur()}function v(a){if(!__$(a.currentTarget).hasClass("dji-sru-disabled")){if(a=__$(".dji-sru-folder-selected").closest(".dji-sru-outline-dialog-element")[0]){var c=
a.id,b=sru.outlinesDataManager.activeOutline();if(!("dji-sru-0"===c&&!b||b&&c===b.uuid())){for(c=0;c<f.length;c++){a:{var b=f[c].uuid(),d=a.parentNode;if("dji-sru-0"==a.id&&!b||b===a.id)b=!0;else{for(;__$(d).hasClass("dji-sru-subfolders");){if(d.parentNode.outline.uuid()===b){b=!0;break a}d=d.parentNode}b=!1}}b&&f.splice(c,1)}sru.outlinesDataManager.moveOutlines(f,"dji-sru-0"!==a.id?a.outline:null)}}l()}}function l(){if(!__$(e).is(":hidden")){g=!1;__$("html").removeClass("dji-sru-move-folder-dialog");
sru.mainContainer.leaveBusyState();var a=sru.outlinesDataManager.currentUiPathState();a.view="folder";sru.outlinesDataManager.updateUiPathState(a);p?sru.outlines.updateSelectionView():sru.outlines.removeSelectionView()}}var f,e,p=!1,g=!1,k;h.createOutlineMoveDialog=function(a){e=dji.ui.templates.load(a,"template-page-dji-sru-move-folder-dialog");e.id="dji-sru-move-folder-dialog";__$.querySelector("#__dji_sru_main_container_content").appendChild(e);__$("#__dji_sru_btnDialogCancel").on("click",l);__$("#dji-sru-move-folder-dialog").on("click",
".dji-sru-btnDialogNew",r);__$("#dji-sru-move-folder-dialog").on("click",".dji-sru-btnDialogMove",v);__$("#dji-sru-move-folder-dialog").on("click",".dji-sru-outline-dialog-element-header-content",q);k=a;return e};h.show=function(a,c){f=a;m(c,e.querySelector(".dji-sru-dialog-content"),!0);var b=sru.outlinesDataManager.activeOutline();n();var d=b.isHome()?"dji-sru-0":b.uuid(),d=__$(e).find("#"+d);b.isHome()||__$(d.find(".dji-sru-outline-dialog-element-header")[0]).addClass("dji-sru-folder-selected");
0==a.length?__$(".dji-sru-btnDialogMove").each(function(){__$(this).addClass("dji-sru-disabled")}):__$(d.find(".dji-sru-btnDialogMove")[0]).addClass("dji-sru-disabled")};h.close=l})(window.sru.outlinesMoveDialog=window.sru.outlinesMoveDialog||{});
