window.sru=window.sru||{};
(function(h){function B(){var a=m.slice();if(0<a.length){var b=p[p.length-1];b&&b.isSkeleton()&&a.splice(a.length-1)}dji.utils.callListeners(C,"uiPathUpdated",a)}function u(a,b){(a||b)&&dji.utils.callListeners(C,"dataUpdated",{update:a||null,"delete":b||null})}function r(){var a={directories:[],outlines:[],topics:[],sources:[],topicsSources:[]},b,c,d=!1,e=Array.prototype.slice.call(arguments);0<e.length&&"boolean"===typeof e[e.length-1]&&(d=!!e[e.length-1],e.splice(e.length-1));for(c=0;c<e.length;c++)b=
e[c],b instanceof Array&&(0<b.length?Array.prototype.splice.apply(e,[c,1].concat(b)):e.splice(c,1),c--);for(c=0;c<e.length;c++)b=e[c],b instanceof k?b.isDirectory()?a.directories.push(d?{uuid:b.uuid()}:b.__info()):b.isHome()||a.outlines.push(d?{uuid:b.uuid()}:b.__info()):b instanceof l?a.topics.push(d?{uuid:b.uuid()}:b.__info()):b instanceof q?a.sources.push(d?{uuid:b.uuid()}:b.__info()):b instanceof x&&a.topicsSources.push(b.__info());for(var g in a)a.hasOwnProperty(g)&&0==a[g].length&&delete a[g];
return a}function E(){for(var a=1;a<m.length;a++){var b=m[a];if(b.uuid&&!h.outlineByUuid(b.uuid)){m.splice(a);break}}}function F(a){if(!a)return null;var b,c,d,e,g={topOutline:!1,topDirectory:!1,topTopic:!1,topSource:!1};if(a.directories)for(c=a.directories,b=0;b<c.length;b++)if(d=c[b],(e=f.directories[d.uuid])?e.m_info=d:(e=new y(d),f.directories[e.uuid()]=e),-1!=w(e.uuid(),!0)||0<=w(e.parentUuid(),!0))g.topDirectory=!0;if(a.outlines)for(c=a.outlines,b=0;b<c.length;b++)if(d=c[b],(e=f.outlines[d.uuid])?
e.m_info=d:(e=new k(d),f.outlines[e.uuid()]=e),-1!=w(e.uuid(),!0)||0<=w(e.parentUuid(),!0))g.topOutline=!0;if(a.topics)for(c=a.topics,b=0;b<c.length;b++)if(d=c[b],(e=f.topics[d.uuid])?e.m_info=d:(e=new l(d),f.topics[e.uuid()]=e),d=e.uuid(),-1!=z("uuidTopic",d,!0)||0<=w(e.outlineUuid(),!0))g.topTopic=!0;if(a.sources)for(c=a.sources,b=0;b<c.length;b++)if(d=c[b],(e=f.sources[d.uuid])?e.m_info=d:(e=new q(d),f.sources[e.uuid()]=e),a=e.uuid(),-1!=z("uuidSource",a,!0)||0<=w(e.outlineUuid(),!0))g.topSource=
!0;return g}function w(a,b){return z("uuid",a,b)}function z(a,b,c){if(!a)return-1;var d;if(c){if(0<m.length&&(d=m[m.length-1],d[a]==b))return m.length-1}else for(c=1;c<m.length;c++)if(d=m[c],d[a]==b)return c;return-1}function D(a,b){return a.m_info.modifiedDate<b.m_info.modifiedDate?1:a.m_info.modifiedDate>b.m_info.modifiedDate?-1:a.m_info.title.localeCompare(b.m_info.title)}function G(a){var b=function(a){var b=a.cslData();return b?b.author[0]&&b.author[0].family?b.author[0].family:"No author":a.author().split(",")[0]};
a.sort(function(a,d){return b(a).localeCompare(b(d))})}function H(a){a.sort(function(a,c){return a.m_info.location-c.m_info.location})}function M(a){var b=dji.utils.splitInWords(a.trim().toUpperCase(),!1);if(!b||0==b.length)return[];a=[];var c,d,e;for(c in f.directories)f.directories.hasOwnProperty(c)&&(d=f.directories[c],e=I(d,b),0<e&&a.push({outline:d,matches:e}));for(c in f.outlines)f.outlines.hasOwnProperty(c)&&(d=f.outlines[c],e=I(d,b),0<e&&a.push({outline:d,matches:e}));if(0==a.length)return[];
if(1==a.length)return[a[0].outline];a.sort(function(a,b){return a.matches<b.matches?1:a.matches>b.matches?-1:D(a.outline,b.outline)});c=[];for(b=0;b<a.length;b++)c.push(a[b].outline);return c}function I(a,b){for(var c=0,d=0;d<b.length;d++)-1!==a.title().toUpperCase().indexOf(b[d])&&c++;return c}function J(a,b){var c={directoriesUuids:[]},d,e;for(e in f.directories)d=f.directories[e],d.parentUuid()==a&&(c.directoriesUuids.push(d.uuid()),d=J(d.uuid(),!1),c.directoriesUuids=c.directoriesUuids.concat(d.directoriesUuids));
if(b)for(e in c.directoriesUuids.unshift(a),c.outlinesUuids=[],c.topicsUuids=[],c.sourcesUuids=[],f.outlines)d=f.outlines[e],-1!=c.directoriesUuids.indexOf(d.parentUuid())&&(c.outlinesUuids.push(d.uuid()),d=K(d.uuid()),c.topicsUuids=c.topicsUuids.concat(d.topicsUuids),c.sourcesUuids=c.sourcesUuids.concat(d.sourcesUuids));return c}function K(a){var b={topicsUuids:[],sourcesUuids:[]};for(uuid in f.topics)item=f.topics[uuid],item.outlineUuid()==a&&b.topicsUuids.push(item.uuid());for(uuid in f.sources)item=
f.sources[uuid],item.outlineUuid()==a&&b.sourcesUuids.push(item.uuid());return b}function L(a){var b=[],c,d;for(d in f.topics)c=f.topics[d],c.parentUuid()==a.uuid()&&b.push(c);for(a=0;a<b.length;a++)c=L(b[a]),b=b.concat(c);return b}function v(a,b){this.m_info=a;if(this.m_isSkeleton=!!b)this.m_info.uuid=dji.utils.generateUUID(),this.m_info.creationDate=Date.now(),this.m_info.modifiedDate=this.m_info.creationDate}function k(a,b){v.call(this,a,b);this.m_isDirectory=this.m_isHome=!1;this.m_isSkeleton&&
(this.m_info.parentUuid=a.parentUuid||null,this.m_info.title=null)}function y(a,b){k.call(this,a,b);this.m_isDirectory=!0}function A(){k.call(this,null);this.m_isHome=!0}function l(a,b){v.call(this,a,b);this.m_isSkeleton&&(this.m_info.outlineUuid=a.outlineUuid||null,this.m_info.parentUuid=a.parentUuid||null,this.m_info.location=a.hasOwnProperty("location")?a.location:-1,this.m_info.body=a.body||"",this.m_info.sourcesUuids=[])}function q(a,b){v.call(this,a,b);this.m_isSkeleton&&(this.m_info.outlineUuid=
a.outlineUuid||null,this.m_info.boundToOutline=a.hasOwnProperty("boundToOutline")?!!a.boundToOutline:!1,this.m_info.fromHighlight=a.hasOwnProperty("fromHighlight")?!!a.fromHighlight:!1,this.m_info.data=this.m_info.data||{},a.hasOwnProperty("cslData")&&(this.m_info.data.cslData=a.cslData),a.hasOwnProperty("text")&&(this.m_info.data.text=a.text))}function x(a){this.m_topicUuid=a;this.m_sourcesUuids=[];for(var b=1;b<arguments.length;b++)this.m_sourcesUuids.push(arguments[b])}var C={dataUpdated:[],uiPathUpdated:[]},
f={},m=[],p=[];h.addEventListener=function(a,b){dji.utils.addEventListener(C,a,b)};h.setData=function(a,b){a||(a={},b=null);b&&0!=b.length||(b=[{uuid:null,pageType:"outline",view:"outline"}]);f={directories:{},outlines:{},topics:{},sources:{}};F(a);m=b;E();p=[new A];for(var c=1;c<m.length;c++){var d=m[c];d.uuid&&d.uuid!=p[p.length-1].uuid()&&p.push(h.outlineByUuid(d.uuid))}};h.updateData=function(a,b){if(a){var c=F(a.update),d;if(d=a["delete"]){var e,g,t,h,k={topOutline:!1,topDirectory:!1,topTopic:!1,
topSource:!1};if(d.directories)for(g=d.directories,e=0;e<g.length;e++)if(t=g[e],h=f.directories[t],delete f.directories[t],-1!=w(t)||h&&0<=w(h.parentUuid(),!0))k.topDirectory=!0;if(d.outlines)for(g=d.outlines,e=0;e<g.length;e++)if(t=g[e],h=f.outlines[t],delete f.outlines[t],-1!=w(t)||h&&0<=w(h.parentUuid(),!0))k.topOutline=!0;if(d.topics)for(g=d.topics,e=0;e<g.length;e++)if(t=g[e],h=f.topics[t],delete f.topics[t],-1!=z("uuidTopic",t,void 0)||h&&0<=w(h.outlineUuid(),!0))k.topTopic=!0;if(d.sources)for(g=
d.sources,e=0;e<g.length;e++)if(t=g[e],h=f.sources[t],delete f.sources[g],-1!=z("uuidSource",t,void 0)||h&&0<=w(h.outlineUuid(),!0))k.topSource=!0;if(d.topicsSources)for(g=d.topicsSources,e=0;e<g.length;e++)t=g[e],f.topics[t.topicUuid].__removeLinkedSourcesUuids(t.sourcesUuids);d=k}else d=null;E();return{updateInfo:c,deleteInfo:d}}};h.outlineStackSize=function(){return p?p.length:0};h.outlineFromStack=function(a){return p[a]};h.pushOutlineToStack=function(a){p.push(a);var b={uuid:a.uuid(),pageType:"outline",
view:"outline"};a.isDirectory()||(b.selTab="dji-sru-outline-details",b.sourceType="APA");h.pushUiPathState(b)};h.pushOutlineLinkToSourceToStack=function(a,b){p.push(a);var c={uuid:a.uuid(),pageType:"linkToSource",view:"linkToSource",uuidTopic:b.uuid()};h.pushUiPathState(c)};h.popOutlineFromStack=function(){p.splice(p.length-1);h.popUiPathState()};h.activeOutline=function(){return p[p.length-1]};h.uiPathSize=function(){return m.length};h.uiPathState=function(a){return m[a]};h.currentUiPathState=function(){return m[m.length-
1]};h.updateUiPathState=function(a){B()};h.pushUiPathState=function(a){m.push(a);B()};h.popUiPathState=function(){m.splice(m.length-1);B()};h.outlineFromUiPathState=function(a){return h.outlineByUuid(a?a.uuid:null)};h.topicFromUiPathState=function(a){return h.topicByUuid(a?a.uuidTopic:null)};h.sourceFromUiPathState=function(a){return h.sourceByUuid(a?a.uuidSource:null)};h.home=function(){return 0<p.length?p[0]:null};h.outlineByUuid=function(a){if(!a)return p[0];var b=f.directories[a];b||(b=f.outlines[a]);
return b||null};h.topicByUuid=function(a){return f.topics[a]||null};h.sourceByUuid=function(a){return f.sources[a]||null};h.createDirectory=function(a,b){var c=new y({},!0);c.m_info.parentUuid=b?b.uuid():null;c.title(a);return c};h.createSkeletonOutline=function(a){a=new k({parentUuid:a.uuid()},!0);h.pushOutlineToStack(a);return a};h.moveOutlines=function(a,b){for(var c,d=[],e=b?b.uuid():null,g=0;g<a.length;g++)c=a[g],c.parentUuid(e)&&d.push(c);0<d.length&&(b&&(b.markAsModified(),d.push(b)),u(r(d)))};
h.directories=function(a){var b=[],c,d=a?a.uuid():null,e;for(e in f.directories)f.directories.hasOwnProperty(e)&&(c=f.directories[e],(d&&c.parentUuid()==d||!a&&!c.parentUuid())&&b.push(c));b.sort(D);return b};h.outlineNameIsUnique=function(a){var b=0,c;for(c in f.outlines)if(f.outlines.hasOwnProperty(c)&&f.outlines[c].title()==a&&(b++,1<b))return!1;return!0};h.folderNameIsUnique=function(a){var b=0,c;for(c in f.directories)if(f.directories.hasOwnProperty(c)&&f.directories[c].title()==a&&(b++,1<b))return!1;
return!0};v.prototype.__info=function(){return this.m_info};v.prototype.isSkeleton=function(){return this.m_isSkeleton};v.prototype.uuid=function(){return this.m_info?this.m_info.uuid:null};v.prototype.parentUuid=function(a){if(void 0===a)return this.m_info?this.m_info.parentUuid:null;if(this.m_info.parentUuid==a)return!1;this.m_info.parentUuid=a;this.markAsModified();return!0};v.prototype.parent=function(){return null};v.prototype.modifiedDate=function(){return this.m_info?this.m_info.modifiedDate:
null};v.prototype.markAsModified=function(a){this.m_info&&(this.m_info.modifiedDate=a||Date.now(),this.m_info.creationDate||(this.m_info.creationDate=this.m_info.modifiedDate))};k.prototype=Object.create(v.prototype);k.prototype.constructor=k;k.prototype.parent=function(){return this.m_info.parentUuid?h.outlineByUuid(this.m_info.parentUuid):p[0]};k.prototype.isHome=function(){return this.m_isHome};k.prototype.isSkeleton=function(){return this.m_isSkeleton};k.prototype.isDirectory=function(){return this.m_isDirectory};
k.prototype.title=function(a){if(void 0===a)return this.m_info.title;if(this.m_info.title!=a){this.m_info.title=a;if(a=this.m_isSkeleton)this.m_isDirectory?f.directories[this.m_info.uuid]=this:f.outlines[this.m_info.uuid]=this,this.m_isSkeleton=!1;var b=Date.now(),c=this.parent();this.markAsModified(b);c.markAsModified(b);u(r([c,this]));a&&B()}};k.prototype.outlines=function(a){var b=[];if((a=a?a.trim().toUpperCase():null)&&0<a.length)b=M(a);else{var c,d,e=!1,g=!1;for(c in f.directories)f.directories.hasOwnProperty(c)&&
(d=f.directories[c],e=!!(this.m_isHome&&!d.m_info.parentUuid||!this.m_isHome&&this.m_info.uuid==d.m_info.parentUuid),g=!a||0==a.length||-1!=d.m_info.title.toUpperCase().indexOf(a),e&&g&&b.push(d));for(c in f.outlines)f.outlines.hasOwnProperty(c)&&(d=f.outlines[c],e=!!(this.m_isHome&&!d.m_info.parentUuid||!this.m_isHome&&this.m_info.uuid==d.m_info.parentUuid),g=!a||0==a.length||-1!=d.m_info.title.toUpperCase().indexOf(a),e&&g&&b.push(d));b.sort(D)}return b};k.prototype.topics=function(a){var b=[],
c;for(c in f.topics)if(f.topics.hasOwnProperty(c)){var d=f.topics[c];d&&d.outlineUuid()==this.m_info.uuid&&(!a&&!d.parentUuid()||a&&a.uuid()==d.parentUuid())&&b.push(d)}H(b);return b};k.prototype.sources=function(){var a=[],b;for(b in f.sources)if(f.sources.hasOwnProperty(b)){var c=f.sources[b];c&&c.outlineUuid()==this.m_info.uuid&&a.push(c)}G(a);return a};k.prototype.deleteOutlines=function(a){var b=[],c=[],d=[],e=[],g=Date.now(),h=[],k=[],l,m,n;for(n=0;n<a.length;n++)m=a[n],m.isDirectory()?(l=J(m.uuid(),
!0),b=b.concat(l.directoriesUuids),c=c.concat(l.outlinesUuids)):(l=K(m.uuid()),c.push(m.uuid())),d=d.concat(l.topicsUuids),e=e.concat(l.sourcesUuids);for(n=0;n<b.length;n++)k.push(f.directories[b[n]]),delete f.directories[b[n]];for(n=0;n<c.length;n++)k.push(f.outlines[c[n]]),delete f.outlines[c[n]];for(n=0;n<d.length;n++)k.push(f.topics[d[n]]),delete f.topics[d[n]];for(n=0;n<e.length;n++)k.push(f.sources[e[n]]),delete f.sources[e[n]];this.m_isHome||(h.push(this),this.markAsModified(g));u(r(h),r(k,
!0))};k.prototype.createTopic=function(a,b,c){this.m_info.title||(dji.logger.warning("Adding topic to an outline without title: ",this.m_info.uuid),this.title("Outline Name"));var d=Date.now(),e=[this],g,h=this.topics(c);if(-1==b||h.length<=b)b=h.length;for(var k=b;k<h.length;k++)g=h[k],g.m_info.location++,g.markAsModified(d),e.push(g);g=new l({outlineUuid:this.m_info.uuid,location:b,body:a,parentUuid:c?c.uuid():null},!0);g.m_isSkeleton=!1;e.push(g);f.topics[g.uuid()]=g;this.markAsModified(d);u(r(e));
return g};k.prototype.deleteTopic=function(a){if(a&&a.outlineUuid()==this.m_info.uuid){var b=Date.now(),c=[this],d=[],e,g,h=a.siblings(),k=L(a);k.unshift(a);var l=[];e={};for(var m,n=0;n<k.length;n++){g=k[n].sourcesUuids();for(var p=0;p<g.length;p++)m=g[p],e.hasOwnProperty(m)||(e[m]=!0,l.push(f.sources[m]))}for(e=0;e<l.length;e++)g=l[e],g.boundToOutline()||this.hasOtherCitingTopics(g,k)||(delete f.sources[g.uuid()],d.push(g));for(e=a.location()+1;e<h.length;e++)a=h[e],a.m_info.location--,a.markAsModified(b),
c.push(a);for(e=0;e<k.length;e++)d.push(k[e]),delete f.topics[k[e].uuid()];this.markAsModified(b);u(r(c),r(d,!0))}};k.prototype.createSource=function(a,b,c){this.m_info.title||(dji.logger.warning("Adding source to an outline without title: ",this.m_info.uuid),this.title("Untitled"));var d={};a.id?(d.text={},d.text.MLA=sru.citations.generateCition(a,"mla","en-US"),d.text.APA=sru.citations.generateCition(a,"apa","en-US"),d.text.CHICAGO=sru.citations.generateCition(a,"chicago-nb","en-US"),d.manuallyEdited=
!1,delete a.id,d.cslData=JSON.parse(JSON.stringify(a))):(d.cslData=null,d.author=a.authors,d.title=a.title,d.text.MLA=a.citation.MLA,d.text.APA=a.citation.APA,d.text.CHICAGO=a.citation.CHICAGO,d.text.HARVARD=a.citation.HARVARD);a=new q({outlineUuid:this.m_info.uuid,boundToOutline:!c,fromHighlight:!!b,data:d},!0);a.m_isSkeleton=!1;b=Date.now();var e;a:{d=a;for(e in f.sources)if(f.sources.hasOwnProperty(e)){var g=f.sources[e];if(d===g||d.uuid()==g.uuid()){e=g;break a}if(d.outlineUuid()==g.outlineUuid()&&
g.matches(d)){e=g;break a}}e=null}e?e.isEqual(a)?a=e:(e.data().manuallyEdited||e.update(a.cslData(),!1,!0),a=e,e=null):f.sources[a.uuid()]=a;c&&c.linkSource(a,!0);d=[this];this.markAsModified(b);e||(d.push(a),a.markAsModified(b));c&&(d.push(c),c.markAsModified(b),d.push(new x(c.uuid(),a.uuid())));u(r(d));return a};k.prototype.deleteSource=function(a,b){var c=Date.now(),d=[this],e=[a];b&&(d.push(b),b.markAsModified(c),e.push(new x(b.uuid(),a.uuid())));for(var g in f.topics)if(f.topics.hasOwnProperty(g)){var h=
f.topics[g];h&&h.outlineUuid()==this.m_info.uuid&&h.unlinkSource(a,!0,!0)&&(d.push(h),h.markAsModified(c),e.push(new x(h.uuid(),a.uuid())))}delete f.sources[a.uuid()];this.markAsModified(c);u(r(d),r(e,!0))};k.prototype.hasCitingTopics=function(a){for(var b in f.topics)if(f.topics.hasOwnProperty(b)){var c=f.topics[b];if(c&&c.outlineUuid()==this.m_info.uuid&&c.hasLinkedSource(a))return!0}return!1};k.prototype.hasOtherCitingTopics=function(a,b){for(var c in f.topics)if(f.topics.hasOwnProperty(c)){var d=
f.topics[c];if(d&&d.outlineUuid()==this.m_info.uuid&&d.hasLinkedSource(a)&&-1==b.indexOf(d))return!0}return!1};y.prototype=Object.create(k.prototype);y.prototype.constructor=y;A.prototype=Object.create(k.prototype);A.prototype.constructor=A;A.prototype.title=function(){return"Home"};l.prototype=Object.create(v.prototype);l.prototype.constructor=l;l.prototype.__info=function(){return{uuid:this.m_info.uuid,outlineUuid:this.m_info.outlineUuid,parentUuid:this.m_info.parentUuid,location:this.m_info.location,
body:this.m_info.body,creationDate:this.m_info.creationDate,modifiedDate:this.m_info.modifiedDate}};l.prototype.outlineUuid=function(){return this.m_info.outlineUuid};l.prototype.outline=function(){return f.outlines[this.m_info.outlineUuid]||null};l.prototype.location=function(){return this.m_info.location};l.prototype.body=function(a){if(void 0===a)return this.m_info.body;a!=this.m_info.body&&(this.m_info.body=a,this.markAsModified(),u(r(this)))};l.prototype.sourcesUuids=function(){return this.m_info.sourcesUuids};
l.prototype.sources=function(){for(var a=[],b=0;b<this.m_info.sourcesUuids.length;b++){var c=f.sources[this.m_info.sourcesUuids[b]];c&&a.push(c)}G(a);return a};l.prototype.__removeLinkedSourcesUuids=function(a){if(a&&0<a.length)for(var b=-1,c=0;c<a.length;c++)b=this.m_info.sourcesUuids.indexOf(a[c]),-1!=b&&this.m_info.sourcesUuids.splice(b,1)};l.prototype.linkSource=function(a,b){if(-1==this.m_info.sourcesUuids.indexOf(a.uuid())&&(this.m_info.sourcesUuids.push(a.uuid()),!b)){var c=[this.outline(),
this,new x(this.uuid(),a.uuid())],d=Date.now();this.outline().markAsModified(d);this.markAsModified(d);u(r(c))}};l.prototype.unlinkSource=function(a,b,c){var d=this.m_info.sourcesUuids.indexOf(a.uuid());if(-1==d)return!1;c=!c;this.m_info.sourcesUuids.splice(d,1);b||a.boundToOutline()||(b=this.outline(),b.hasCitingTopics(a)||(c=!1,b.deleteSource(a,this)));c&&(b=[this.outline(),this],a=[new x(this.uuid(),a.uuid())],d=Date.now(),this.outline().markAsModified(d),this.markAsModified(d),u(r(b),r(a)));return!0};
l.prototype.hasLinkedSource=function(a){return-1!=this.m_info.sourcesUuids.indexOf(a.uuid())};l.prototype.hasLinkedSources=function(){return 0<this.m_info.sourcesUuids.length};l.prototype.indent=function(){if(!(1>this.m_info.location)){var a=this.outline(),b=this.siblings(),c=this.m_info.location,d=b[this.m_info.location-1],e=d.lastChildLocation()+1,g=Date.now();this.m_info.parentUuid=d.m_info.uuid;this.m_info.location=e;for(d=c+1;d<b.length;d++)b[d].m_info.location--,b[d].markAsModified(g);b=[a,
this,b.slice(c+1)];a.markAsModified(g);this.markAsModified(g);u(r(b))}};l.prototype.outdent=function(){var a=this.parent();if(a){var b=this.outline(),c=a?a.parent():null,d=a.m_info.location+1,e=h.outlineByUuid(this.m_info.outlineUuid).topics(c),g=this.siblings(),f=this.m_info.location,a=Date.now();this.m_info.parentUuid=c?c.m_info.uuid:null;this.m_info.location=d;for(c=f+1;c<g.length;c++)g[c].m_info.location--,g[c].markAsModified(a);for(c=d;c<e.length;c++)e[c].m_info.location++,e[c].markAsModified(a);
c=[b,this,g.slice(f+1),e.slice(d)];b.markAsModified(a);this.markAsModified(a);u(r(c))}};l.prototype.moveTo=function(a,b){if(b==this||this.hasDescendant(a))return!1;var c=this.outline(),d=[c,this],e=!!(!a&&this.m_info.parentUuid||a&&this.m_info.parentUuid!=a.uuid),f=b;f==a&&(f=null);var k=f?f.m_info.location+1:0,l=h.outlineByUuid(this.m_info.outlineUuid).topics(a),m=this.siblings(),p=this.m_info.location,n=Date.now(),q;!e&&f&&this.m_info.location<f.m_info.location&&k--;this.m_info.parentUuid=a?a.m_info.uuid:
null;this.m_info.location=k;q=e?m.length:k+1;for(f=p+1;f<q;f++)m[f].m_info.location--,m[f].markAsModified(n),d.push(m[f]);if(e)for(f=k;f<l.length;f++)l[f].m_info.location++,l[f].markAsModified(n),d.push(l[f]);else for(f=k;f<p;f++)l[f].m_info.location++,l[f].markAsModified(n),d.push(l[f]);c.markAsModified(n);this.markAsModified(n);u(r(d));return!0};l.prototype.siblings=function(){var a=[],b=null,c;for(c in f.topics)f.topics.hasOwnProperty(c)&&(b=f.topics[c],this.m_info.outlineUuid==b.m_info.outlineUuid&&
this.m_info.parentUuid==b.m_info.parentUuid&&a.push(b));H(a);return a};l.prototype.lastChildLocation=function(){var a=null,b=-1,c;for(c in f.topics)f.topics.hasOwnProperty(c)&&(a=f.topics[c],this.m_info.outlineUuid==a.m_info.outlineUuid&&this.m_info.uuid==a.m_info.parentUuid&&(b=Math.max(b,a.m_info.location)));return b};l.prototype.parent=function(){return this.m_info.parentUuid?f.topics[this.m_info.parentUuid]||null:null};l.prototype.hasDescendant=function(a){if(a==this)return!0;for(;a&&a.m_info.parentUuid;){if(a.m_info.parentUuid==
this.m_info.uuid)return!0;a=f.topics[a.parentUuid]}return!1};q.prototype=Object.create(v.prototype);q.prototype.constructor=q;q.prototype.outlineUuid=function(){return this.m_info.outlineUuid};q.prototype.outline=function(){return f.outlines[this.m_info.outlineUuid]};q.prototype.data=function(a){};q.prototype.boundToOutline=function(){return this.m_info.boundToOutline};q.prototype.data=function(){return this.m_info.data};q.prototype.author=function(){return this.m_info.data.author};q.prototype.cslData=
function(a){return a?JSON.parse(JSON.stringify(this.m_info.data.cslData)):this.m_info.data.cslData};q.prototype.text=function(a){return a?this.m_info.data.text[a]:this.m_info.data.text};q.prototype.matches=function(a){return this.m_info.fromHighlight&&a.m_info.fromHighlight&&this.m_info.data.cslData.URL===a.m_info.data.cslData.URL?!0:!1};q.prototype.isEqual=function(a){return a&&this.m_info.fromHighlight&&a.m_info.fromHighlight?dji.utils.objectsAreEqual(this.m_info.data.cslData,a.m_info.data.cslData):
!1};q.prototype.update=function(a,b,c){b&&dji.utils.objectsAreEqual(this.m_info.data.cslData,a)||(a.id||(a.id="id0"),this.m_info.data.text.MLA=sru.citations.generateCition(a,"mla","en-US"),this.m_info.data.text.APA=sru.citations.generateCition(a,"apa","en-US"),this.m_info.data.text.CHICAGO=sru.citations.generateCition(a,"chicago-nb","en-US"),delete a.id,this.m_info.data.cslData=JSON.parse(JSON.stringify(a)),this.m_info.data.manuallyEdited=b,c||(a=this.outline(),b=Date.now(),c=[a,this],a.markAsModified(b),
this.markAsModified(b),u(r(c))))};x.prototype.__info=function(){return{topicUuid:this.m_topicUuid,sourcesUuids:this.m_sourcesUuids}}})(window.sru.outlinesDataManager=window.sru.outlinesDataManager||{});
