window.dji=window.dji||{};
(function(p){function G(d){try{var b=dji.selectionMapper.mapSelection({fromCaretToEnd:d,clearSelection:!0});if(b&&b.text&&0<b.text.length&&0<b.text.trim().length){var f=b,h=b.element.getBoundingClientRect();dji.utils.addClassToHtmlElements("dji-sru-rewordify-active");if(dji.utils.isSruPdf()||dji.utils.isAmazonKindle()||K())b.isEditor=!0;E=dji.utils.generateUUID();if(b.isEditor){a.isActive=!0;a.body.innerText=b.text.trim();a.body.scrollTop=0;var e="input"!==b.type&&b.custom.map?b.custom.map[0].element.parentElement:
b.element;K()&&(e=document.getElementById("dji-sru-overlay-selection").getElementsByTagName("span")[0]);if(e){var l=window.getComputedStyle(e,null).getPropertyValue("font-size");a.body.style.fontSize=""!=e.style.fontSize?parseFloat(e.style.fontSize)+"px":l;var g=window.getComputedStyle(e,null).getPropertyValue("font-style");a.body.style.fontStyle=0<g.length?g:e.style.fontStyle;var m=window.getComputedStyle(e,null).getPropertyValue("font-family");a.body.style.fontFamily=0<m.length?m:e.style.fontFamily;
var q=window.getComputedStyle(e,null).getPropertyValue("font-variant");a.body.style.fontVariant=0<q.length?q:e.style.fontVariant;var u=window.getComputedStyle(e,null).getPropertyValue("font-weight");a.body.style.fontWeight=0<u.length?u:e.style.fontWeight}}dji.utils.removeEventListenerFromBodyElements("click",F,!0);dji.utils.removeClassFromHtmlElements("dji-sru-rewordify-from-cursor");dji.selectionMapper.enableSelection(!1);window.dji.ui.effects.enterBusyState();a.isActive&&dji.utils.addClassToElement(document.documentElement,
"dji-sru-bodycover");setTimeout(function(){if(E===E){var d=f;f.isEditor&&(dji.utils.addClassToElement(a.main,"dji-working"),dji.utils.addClassToElement(a.main,"dji-visible"),f=null,a.body.firstChild?(document.getSelection().setBaseAndExtent(a.body.firstChild,0,a.body.lastChild,a.body.lastChild.textContent.length),f=dji.selectionMapper.mapDocumentSelection({iframes:[],document:document,element:a.body},!0)):document.getSelection().empty());!f||0>=f.text.length?H():(c={initialContext:d,selectionContext:f,
boundingRect:h},dji.utils.callListeners(v,"process",c.selectionContext.text,E))}},0)}else d||(dji.utils.addClassToHtmlElements("dji-sru-rewordify-from-cursor"),dji.utils.addEventListenerToBodyElements("click",F,!0),dji.selectionMapper.enableSelection(!0));return!0}catch(r){dji.logger.error(r)}return!1}function F(d){if(!c&&d.target){var a=["dji-sru-close-btn","dji-sru-overlay-child"];if(!dji.utils.elementHasId(d.target,["dji-sru-busy-state","dji-sru-screen-selection","dji-sru-x-line","dji-sru-y-line",
"dji-sru-crosshair"])&&!dji.utils.elementHasClass(d.target,a)){if("A"==d.target.tagName||dji.utils.elementHasClass(d.target,["dji-sru-rewordify-chunk","dji-sru-ocr-word"]))d.preventDefault(),d.stopPropagation(),a=dji.utils.documentForElement(d.target).getSelection(),a.selectAllChildren(d.target),a.collapseToStart();dji.selectionMapper.simulateSelectionFromEvent(d);setTimeout(function(){G(!0)},0)}}}function W(a){a.__dji_sru_speak_cursor||sru.speech.isActive()||(a.preventDefault(),a.stopPropagation(),
a=a.srcElement.__dji_sru_rewordify_data.word,a.translatedText||a.currentWord!=a.words.length-1?(a.currentWord=(a.currentWord+1)%a.words.length,L(a,a.currentWord==a.words.length-1)):(c.word=a,dji.utils.callListeners(v,"translateText",a.words[a.currentWord])))}function L(a,b){for(var c=a.chunks,h=0,e=a.words[a.currentWord],l=0;l<c.length;l++){var g=c[l],m=l<c.length-1?e.substring(h,h+g.range.length):e.substring(h),h=h+g.range.length;g.dji_span.innerText=l<c.length-1?m:m+String.fromCharCode(8203);b&&
a.translatedText?(dji.utils.addClassToElement(g.dji_span,"dji-sru-rewordify-translated"),0==a.currentWord?dji.utils.addClassToElement(g.dji_span,"dji-sru-rewordify-translated-original"):dji.utils.removeClassFromElement(g.dji_span,"dji-sru-rewordify-translated-original"),0<document.getElementsByClassName("dji-sru-google-translate-logo").length||(g=document.createElement("a"),g.setAttribute("href","http://translate.google.com"),g.setAttribute("class","dji-sru-google-translate-logo"),document.body.appendChild(g),
document.getElementsByClassName("dji-sru-google-translate-logo")[0].instances=1,m=document.createElement("img"),m.setAttribute("class","dji-sru-google-translate-logo-img"),g.appendChild(m))):(dji.utils.removeClassFromElement(g.dji_span,"dji-sru-rewordify-translated"),dji.utils.removeClassFromElement(g.dji_span,"dji-sru-rewordify-translated-original"),M())}}function M(){0<document.getElementsByClassName("dji-sru-google-translate-logo").length&&0==document.getElementsByClassName("dji-sru-rewordify-translated").length&&
document.body.removeChild(document.getElementsByClassName("dji-sru-google-translate-logo")[0])}function I(d){var b=d.toElement;if(b!=a.main.tl&&b!=a.main.bl&&b!=a.main.br){for(;b&&b!=a.body&&b!=a.main;)b=b.parentElement;b!=a.body&&(d.preventDefault(),d.stopPropagation())}}function H(){dji.utils.preventInputEventsOnBodyElements(!1);dji.utils.removeEventListenerFromBodyElements("click",F,!0);dji.utils.removeClassFromElement(a.main,"dji-visible");if(a.isActive)a.body.innerText="",a.main.style.setProperty("left",
"-10000px"),a.main.style.setProperty("top","-10000px"),a.main.style.setProperty("width","auto"),a.main.style.setProperty("height","auto"),a.isActive=!1;else if(c){for(var d=null,b=c.initialContext.activeElementInfo.document,f=b.getElementsByClassName("dji-sru-rewordify-chunk"),h=f.length-1;0<=h;h--){var e=f[h],l=e.__dji_sru_rewordify_data?e.__dji_sru_rewordify_data.originalText:e.firstChild.textContent;d&&d!=e.parentElement&&d.normalize();d=e.parentElement;e.parentElement.replaceChild(b.createTextNode(l),
e)}d&&d.normalize()}dji.utils.removeClassFromHtmlElements("dji-sru-rewordify-from-cursor");dji.utils.removeClassFromHtmlElements("dji-sru-rewordify-active");M();dji.selectionMapper.enableSelection(!1);c&&dji.selectionMapper.clearSelection(c.initialContext);E=c=null;w=!1;dji.utils.callListeners(v,"deactivate");dji.utils.removeClassFromElement(document.documentElement,"dji-sru-bodycover");window.dji.ui.effects.leaveBusyState()}function K(){return dji.utils.elementHasClass(document.documentElement,"dji-sru-screen-selection")}
var V=!1,v={activate:[],deactivate:[],process:[],resultsProcessed:[],translateText:[]},c=null,E=null,w=!1,a={main:null,close:null,body:null,isActive:!1};p.initialize=function(){V=!0;a.main=document.createElement("div");a.main.setAttribute("dji-sru-rewordify-popup",!0);a.main.addEventListener("mousedown",I,!0);a.close=document.createElement("div");a.close.setAttribute("class","dji-sru-close-btn");a.close.addEventListener("mousedown",I,!0);a.close.addEventListener("click",H,!0);a.main.appendChild(a.close);
a.body=document.createElement("div");a.body.setAttribute("dji-sru-rewordify-body",!0);a.body.setAttribute("tabindex","0");a.main.appendChild(a.body);a.main.tl=document.createElement("div");dji.utils.addClassToElement(a.main.tl,"dynDiv_resizeDiv_tl");a.main.appendChild(a.main.tl);a.main.bl=document.createElement("div");dji.utils.addClassToElement(a.main.bl,"dynDiv_resizeDiv_bl");a.main.appendChild(a.main.bl);a.main.br=document.createElement("div");dji.utils.addClassToElement(a.main.br,"dynDiv_resizeDiv_br");
a.main.appendChild(a.main.br);(dji.utils.isSruPdf()||dji.utils.isAmazonKindle())&&ByRei_dynDiv.init.main();document.body.appendChild(a.main)};p.addEventListener=function(a,b){v.hasOwnProperty(a)&&"function"==typeof b&&-1==v[a].indexOf(b)&&v[a].push(b)};p.isActive=function(){return w};p.activate=function(d,b){V&&d!=w&&(d?(w=!0,dji.utils.callListeners(v,"activate"),dji.utils.preventInputEventsOnBodyElements(!0),w=G(!1),w||(dji.utils.preventInputEventsOnBodyElements(!1),window.dji.ui.effects.leaveBusyState(),
dji.utils.callListeners(v,"deactivate"))):b&&!a.isActive||H())};p.processDone=function(d,b){dji.logger.log(d,b);if(c&&E===d)if(!b||!b.found||!b.tokens||0>=b.tokens.length)H();else{c.rewordifyTokens=b.tokens;for(var f=0;f<b.tokens.length;f++){d=b.tokens[f];var h=c.selectionContext.text.substr(d.pos,d.length);dji.logger.log(h,d.words.join("|"))}try{for(var e=c.rewordifyTokens,l=c.selectionContext,g=l.custom.selectionOffset,f=[],h=null,m=[],q=null,u=null,r=null,p=null,k=null,z=null,A=null,w=null,x=-1,
F=-1,G=-1,Q=0;Q<e.length;Q++){var n=e[Q];if(n.words&&!(0>=n.words.length)){F=n.pos;G=n.pos+n.length;z=A=null;dji.logger.log(c.selectionContext.text.substr(n.pos,n.length),JSON.stringify(n));for(var p={index:f.length,range:{start:n.pos+g,length:n.length},chunks:[],words:n.words,currentWord:0,tooltip:n.words.join(", ")},N=F;N<G;N++){try{w=l.custom.map[N+g],A=w.element}catch(O){throw dji.logger.error(O),O;}k&&z==A?k.range.length++:(k={element:A,range:{offset:N,start:w.offset,length:1},group:p.index},
p.chunks.push(k),q&&q.element==A||(q={element:A,chunks:[]},m.push(q)),q.chunks.push(k));z=A}f.push(p)}}c.words=f;for(x=0;x<m.length;x++){for(var q=m[x],z=q.element,h=q.chunks,t=document.createDocumentFragment(),e=0,P=z.textContent,l=0;l<h.length;l++)k=h[l],e<k.range.start&&(u=P.substring(e,k.range.start),t.appendChild(document.createTextNode(u))),u=P.substring(k.range.start,k.range.start+k.range.length),e=k.range.start+k.range.length,r=document.createElement("span"),r.innerText=u,r.setAttribute("dji-sru-rewordify-group",
k.group),r.setAttribute("class","dji-sru-rewordify-chunk dji-sru-rewordify-match"),r.setAttribute("title",f[k.group].tooltip),r.addEventListener("click",W),t.appendChild(r),r.__dji_sru_rewordify_data={word:f[k.group],originalText:u},k.dji_span=r;e<P.length&&(u=P.substring(e),t.appendChild(document.createTextNode(u)));z.parentElement.replaceChild(t,z)}for(x=0;x<f.length;x++)f[x].currentWord=Math.min(1,f[x].words.length),L(f[x]);dji.utils.callListeners(v,"resultsProcessed",!0);dji.utils.preventInputEventsOnBodyElements(!1);
window.dji.ui.effects.leaveBusyState();var R=c.initialContext.activeElementInfo.iframes,S=c.boundingRect,B=a.main.getBoundingClientRect(),J=a.body.getBoundingClientRect(),T=sru.mainContainer.getBoundingClientRect(),K=Math.max(1,window.devicePixelRatio),M=dji.utils.elementIsVisible(c.initialContext.element),t=30/K,C=B.height,U=B.width;a.body.scrollTop=0;U=Math.max(50,Math.min(T.left-2*t,U));a.main.style.height=U+"px";B=a.main.getBoundingClientRect();C=B.height;0<a.body.scrollHeight&&(C=Math.min(400,
a.body.scrollHeight+J.height));C=Math.max(50,Math.min(window.innerHeight-2*t,C));a.main.style.height=C+"px";var B=a.main.getBoundingClientRect(),D=S.top,y=S.left;if(0<R.length)for(J=0;J<R.length;J++)var I=R[J].getBoundingClientRect(),D=D+I.top,y=y+I.left;window.innerHeight<D+C&&(D=window.innerHeight-C-t/2-1);D=Math.max(D,t);y=Math.max(0,M?y+S.width+10:y);T.left<y+B.width+t&&(y=T.left-B.width-t-3);a.main.style.top=D+"px";a.main.style.left=y+"px";a.body.focus();dji.utils.removeClassFromElement(a.main,
"dji-working")}catch(O){dji.logger.error(O),dji.utils.callListeners(v,"resultsProcessed",!1),H()}}};p.processTranslationDone=function(a){if(a&&!a.error&&a.translatedText){c.word.translatedText=a.translatedText;c.word.words.push(a.translatedText);c.word.currentWord=(c.word.currentWord+1)%c.word.words.length;c.word.tooltip=c.word.words.join(", ");for(a=0;a<c.word.chunks.length;a++)c.word.chunks[a].dji_span.setAttribute("title",c.word.tooltip);L(c.word,!0)}else c.word.currentWord=(c.word.currentWord+
1)%c.word.words.length,L(c.word,!1)}})(window.dji.rewordify=window.dji.rewordify||{});
