window.sru=window.sru||{};
(function(n){var p,q,e,f,d,h;function G(a){p=a.x;q=a.y;e=p;f=q;d=p;h=q}function D(){g===c.select&&(G({x:0,y:0}),g=c.start,E(),dji.utils.removeClassFromElement(b,"dji-sru-screen-select"))}function H(a){a.x<=p?e+=a.x-e:d+=a.x-d;a.y<=q?f+=a.y-f:h+=a.y-h;e>d&&(d=e);f>h&&(h=f)}function E(){var a=f<q?f+2:f,b=e<p?e+2:e;v.style.height=f+3+"px";l.style.top=f+3+"px";l.style.width=b+3+"px";l.style.height=Math.max(h-f-3,0)+"px";k.style.top=a+"px";k.style.left=b+"px";k.style.width=d-b+"px";k.style.height=h-a+
"px";m.style.top=f+3+"px";m.style.left=d-3+"px";m.style.width=window.innerWidth-d+3+"px";m.style.height=Math.max(h-f-3,0)+"px";w.style.top=h+"px";w.style.height=window.innerHeight-h+"px"}function N(){y()}function O(a){g!=c.ready&&(a={x:a.clientX,y:a.clientY},z.style.left=a.x+"px",A.style.top=a.y+"px",t.style.left=a.x-6+"px",t.style.top=a.y-6+"px",g===c.select&&(H(a),E()))}function P(a){g!=c.ready&&(a.stopPropagation(),a.preventDefault(),g===c.start&&(G({x:a.clientX,y:a.clientY}),g=c.select,dji.utils.addClassToElement(b,
"dji-sru-screen-select"),E()))}function Q(a){g!=c.ready&&g===c.select&&a.clientX!==p&&a.clientY!=q&&(a={x:a.clientX,y:a.clientY},g===c.select&&(H(a),e+=4,f+=5,d-=4,h-=4,a=window.devicePixelRatio,a={zoomLevel:a,left:e*a,right:d*a,top:f*a,bottom:h*a},g=c.ready,dji.utils.removeClassFromElement(b,"dji-sru-screen-select"),F("busy"),dji.utils.callListeners(x,"selectionDone",B,a)))}function I(a){a.stopPropagation();a.preventDefault();g!=c.ready&&g===c.select&&27===a.keyCode&&(b.className="",D())}function J(a){g===
c.select?(b.className="",D()):g===c.ready&&y();a.stopPropagation();a.preventDefault()}function K(a){y()}function y(){C=!1;document.removeEventListener("keydown",I,!0);document.removeEventListener("scroll",J,!0);window.removeEventListener("resize",K,!0);b.className="";D();B=null;g=c.none;r.innerHTML="";dji.utils.removeClassFromElement(document.documentElement,"dji-sru-screen-selection");dji.utils.callListeners(x,"deactivate")}function F(a){if(g===c.ready)switch(a){case "busy":b.className="dji-sru-screen-select-busy";
break;case "ready":b.className="dji-sru-screen-select-ready";break;default:b.className=""}else b.className=""}var L=!1,C=!1,x={activate:[],deactivate:[],selectionDone:[],resultsProcessed:[]},b=null,l=null,v=null,m=null,w=null,k=null,r=null,z=null,A=null,t=null;h=d=f=e=q=p=0;var c={none:0,start:1,select:2,ready:3},g=c.none,B=null,M=!1;n.initialize=function(){L=!0;b=document.createElement("div");b.id="dji-sru-screen-selection";z=document.createElement("div");z.id="dji-sru-x-line";b.appendChild(z);A=
document.createElement("div");A.id="dji-sru-y-line";b.appendChild(A);t=document.createElement("div");t.id="dji-sru-crosshair";b.appendChild(t);v=document.createElement("div");v.id="dji-sru-overlay-top";v.className="dji-sru-overlay-child";b.appendChild(v);l=document.createElement("div");l.id="dji-sru-overlay-left";l.className="dji-sru-overlay-child";b.appendChild(l);k=document.createElement("div");k.id="dji-sru-overlay-selection";if(null!==b){var a=document.createElement("div");a.className="dji-sru-close-btn";
a.addEventListener("click",N,!0);k.appendChild(a)}b.appendChild(k);r=document.createElement("div");r.id="dji-sru-ocr-content";r.setAttribute("tabindex","0");k.appendChild(r);m=document.createElement("div");m.id="dji-sru-overlay-right";m.className="dji-sru-overlay-child";b.appendChild(m);w=document.createElement("div");w.id="dji-sru-overlay-bottom";w.className="dji-sru-overlay-child";b.appendChild(w);b.addEventListener("mousemove",O,!0);b.addEventListener("mouseup",Q,!0);b.addEventListener("mousedown",
P,!0);document.body.appendChild(b)};n.addEventListener=function(a,b){x.hasOwnProperty(a)&&"function"==typeof b&&-1==x[a].indexOf(b)&&x[a].push(b)};n.activate=function(a){if(L&&a!=C)if(a){B=dji.utils.generateUUID();C=!0;document.getSelection().empty();a=window.innerWidth/2;var b=window.innerHeight/2;z.style.left=a+"px";A.style.top=b+"px";t.style.left=a-6+1+"px";t.style.top=b-6+1+"px";document.addEventListener("keydown",I,!0);document.addEventListener("scroll",J,!0);window.addEventListener("resize",
K,!0);g=c.start;dji.utils.addClassToElement(document.documentElement,"dji-sru-screen-selection");dji.utils.callListeners(x,"activate")}else y()};n.isActive=function(){return C};n.setAutoSpeak=function(a){M=a};n.setState=F;n.processDone=function(a,b){if(B!==a||!b||!b.paragraphs)return y();for(var c=window.devicePixelRatio,f=document.createDocumentFragment(),g=b.paragraphs,h=0;h<g.length;h++){var e=g[h],d=document.createElement("div");d.setAttribute("class","dji-sru-ocr-para");d.style.setProperty("left",
(0+e.bounds.left)/c+"px");d.style.setProperty("top",(0+e.bounds.top)/c+"px");d.style.setProperty("width",e.bounds.width/c+"px");d.style.setProperty("height",e.bounds.height/c+"px");for(var k=e.lines,m=0;k&&m<k.length;m++)for(var n=k[m],p=n.words,q=0;p&&q<p.length;q++){var l=p[q],t=l.bounds.left-e.bounds.left+1,w=n.bounds.top-e.bounds.top+1,v=n.bounds.height,u=document.createElement("span");u.setAttribute("class","dji-sru-ocr-word");u.style.setProperty("left",t/c+"px");u.style.setProperty("top",w/
c+"px");u.style.setProperty("width",l.bounds.width/c+"px");u.style.setProperty("height",v/c+"px");u.style.setProperty("line-height",v/c+"px");u.style.setProperty("font-size",l.style.fontPointSize/c+"pt");u.innerText=l.text;d.appendChild(u);d.appendChild(document.createTextNode(" "))}f.appendChild(d)}r.appendChild(f);setTimeout(function(){F("ready");dji.utils.callListeners(x,"resultsProcessed");M&&0<r.querySelectorAll("span.dji-sru-ocr-word").length&&(dji.utils.addClassToElement(r,"dji-sru-temp-selection"),
document.getSelection().selectAllChildren(r),r.focus(),setTimeout(function(){dji.utils.removeClassFromElement(r,"dji-sru-temp-selection");sru.speech.start(!0)},0))},0)}})(window.sru.screenSelection=window.sru.screenSelection||{});
