alert(document.getElementById("sdfsdfsd").value);

window.dji=window.dji||{};
(function(x){function R(a,k){if(1>arguments.length)return null;if(1==arguments.length)return arguments[0];for(var f=[],d=0,d=0;d<arguments.length;d++){for(var c=[],b=arguments[d];b;)c.unshift(b),b=b.parentElement;0<c.length&&f.push(c)}if(1>f.length)return null;if(1==f.length)return f[0][f.length-1];c=null;for(b=0;!(f[0].length<=b);b++){for(var e=f[0][b],d=1;d<f.length;d++)if(f[d].length<=b||f[d][b]!=e){e=null;break}if(e)c=e;else break}c&&3===c.nodeType&&(c=c.parentElement);return c}function Q(){var a=
dji.utils.colorToRgb(O.word),a=[a.r,a.g,a.b].join(", "),a="html.dji-sru-highlight-active *::selection {    background: rgba("+a+", 0.99) !important;    color: "+O.text+" !important;}html.dji-sru-highlight-active .kix-selection-overlay {    opacity: 0 !important;}html.dji-sru-highlight-active #dji-sru-ocr-content *::selection {    background: rgba("+a+", 0.4) !important;    color: transparent !important;}";dji.utils.isSruPdf()&&(a+="html.dji-sru-highlight-active body div#outerContainer div#mainContainer div#viewerContainer *::selection {    color: rgba(255, 255, 255, 0.01) !important;}");
return a}var M=null,J=null,P=null,N=null,O={text:"#000000",word:"#71FDFE"},S=dji.utils.isSruPdf();x.enableHighlight=function(a){for(var k=Q(),f=dji.utils.findValidDocumentElements(null,!0),d=0;d<f.length;d++){var c=f[d],b=c.getElementById("dji-sru-css-highlight");b&&c.head.removeChild(b);a?(c.head||(b=c.createElement("head"),c.documentElement.appendChild(b)),b=c.createElement("style"),b.id="dji-sru-css-highlight",b.innerText=k,c.head.appendChild(b),dji.utils.addClassToElement(c.documentElement,"dji-sru-highlight-active")):
dji.utils.removeClassFromElement(c.documentElement,"dji-sru-highlight-active")}};x.enableSelection=function(a){var k=dji.utils.activeElementInfo(!0);if(!k)return null;if(k.isAmazonKindle)return N.__enableSelection(a)};x.simulateSelectionFromEvent=function(a){var k=dji.utils.activeElementInfo(!0);if(!k)return null;if(k.isAmazonKindle)return N.__simulateSelectionFromEvent(a)};x.setColors=function(a,k,f){a&&(a=dji.utils.colorToHex(a))&&(O.text=a);k&&(k=dji.utils.colorToHex(k))&&(O.word=k);a=Q();k=dji.utils.findValidDocumentElements();
for(f=0;f<k.length;f++){var d=k[f],c=d.getElementById("dji-sru-css-highlight");c&&(d.head.removeChild(c),c=d.createElement("style"),c.id="dji-sru-css-highlight",c.innerText=a,d.head.appendChild(c))}};x.mapSelection=function(a){var k=dji.utils.activeElementInfo(!0);if(!k)return null;var f=k.element;a=a||{};a.fromCaretToEnd=a.fromCaretToEnd||!1;a.accurate=a.accurate||!1;a.clearSelection=a.clearSelection||!1;return void 0!==f.selectionStart?M.__getContextFromInput(k,a.fromCaretToEnd,a.clearSelection):
k.isGoogleDocsEditor?P.__getContext(k,a.fromCaretToEnd,a.accurate,a.clearSelection):!k.isAmazonKindle||dji.utils.elementHasClass(document.documentElement,"dji-sru-screen-selection")||dji.utils.elementHasClass(document.documentElement,"dji-sru-rewordify-active")||dji.utils.elementHasSpecialAttribute(document.documentElement,"dji-sru-screen-selection")||dji.utils.elementHasSpecialAttribute(document.documentElement,"dji-sru-rewordify-active")?J.__getContextFromDocument(k,a.fromCaretToEnd,a.clearSelection):
N.__getContext(k,a.fromCaretToEnd,a.clearSelection)};x.mapDocumentSelection=function(a,k){return(a=a||dji.utils.activeElementInfo(!0))?J.__getContextFromDocument(a,!1,k):null};x.select=function(a,k,f){k=a.extended.selection.start+k;return"input"===a.type?M.__selectInInput(a,k,f):J.__selectInDocument(a,k,f)};x.selectWord=function(a,k){return"input"===a.type?M.__selectWordInInput(a,k):"amazon.kindle"!==a.type||dji.utils.elementHasClass(document.documentElement,"dji-sru-screen-selection")?J.__selectWordInDocument(a,
k):N.__selectWordInAmazonKindle(a,k)};x.restoreSelection=function(a){if("input"===a.type)return M.__restoreSelectionInInput(a);if("amazon.kindle"===a.type&&!dji.utils.elementHasClass(document.documentElement,"dji-sru-screen-selection"))return N.__restoreSelectionInAmazonKindle(a);J.__restoreSelectionInDocument(a)};x.clearSelection=function(a){if("input"===a.type)return M.__clearSelectionInInput(a);if("amazon.kindle"===a.type&&!dji.utils.elementHasClass(document.documentElement,"dji-sru-screen-selection"))return N.__clearSelectionInAmazonKindle(a);
J.__clearSelectionInDocument(a)};x.insertText=function(a,k,f){if(a=dji.utils.elementContext(a)){if(a.isPlainEditor)return M.__insertText(a,k,f);if(a.isContentEditable)return J.__insertText(a,k,f);if(a.isGoogleDocsEditor)return P.__insertText(a,k,f)}};(function(a){a.__getContextFromInput=function(a,f,d){var c=a.element,b=dji.utils.htmlToAscii(c.value),e=(f?b.length:c.selectionEnd)-c.selectionStart;if(0>=e)return null;a={type:"input",activeElementInfo:a,element:c,isEditor:!0,selection:{start:c.selectionStart,
length:e},text:b,custom:{selectionOffset:0},extended:{text:b,selection:{start:c.selectionStart,length:e}},originalSelection:{start:c.selectionStart,end:c.selectionEnd}};if(0<a.text.length){c=a.selection.start;b=a.selection.start+a.selection.length;if(f){for(f=Math.max(0,a.selection.start-160);c>=f;c--)if(dji.charSet.wordSeparator.characterIsMember(a.text.charAt(c))){c++;break}c=Math.max(0,c)}f=c-a.selection.start;a.selection.start+=f;a.selection.length-=f;a.custom.selectionOffset=c;a.extended.selection=
a.selection;a.text=c<b?a.text.slice(c,b):""}0==a.text.trim().length&&(a=null);d&&a&&a.element.setSelectionRange(0,0);return a};a.__selectInInput=function(a,f,d){a.element.setSelectionRange(f,f+d)};a.__selectWordInInput=function(k,f){for(var d=k.extended.selection.start+f,c=d,b=1,e=k.extended.text,t=null,n=e.length;d<n&&(t=e.charAt(d),dji.charSet.whiteSpace.characterIsMember(t));d++);for(c=d;c<n;c++)if(t=e.charAt(c),"-"!=t){if("&"==t&&c==d){c++;b=0;break}if(dji.charSet.wordSeparator.characterIsMember(t)){b=
0;break}}c<d?c=d:e.length<=c&&(c=e.length-1);a.__selectInInput(k,d,c-d+b)};a.__restoreSelectionInInput=function(a){if(a.originalSelection){var f=a.originalSelection;a.element.setSelectionRange(f.start,f.end)}};a.__clearSelectionInInput=function(a){a.element.setSelectionRange(a.element.selectionEnd,a.element.selectionEnd)};a.__insertText=function(a,f){a.document.execCommand("insertText",!1,f)}})(M={});(function(a){function k(a,d){return"SECTION"===a||"P"===a||"LI"===a||"TD"===a?"\n":"DIV"===a?S?" ":
"\n":null}a.__selectWordInDocument=function(f,d){var c=f.custom.map,b;b=f.extended.selection.start+d;f.custom.matrix&&d<f.custom.matrix.length&&(b=f.custom.matrix[b].index);for(var e=b,k=1,n=null,g=c.length;b<g&&(n=c[b],n.ignore||n.embedded||dji.charSet.whiteSpace.characterIsMember(n.text));b++);for(;0<=b;b--)if(n=c[b],!n.ignore&&(n.embedded||dji.charSet.wordSeparator.characterIsMember(n.text))){b++;break}b=Math.max(b,0);if(!(g<=b)){for(e=b;e<g;e++){n=c[e];if(!n.ignore&&n.embedded&&0<n.text.length){e--;
break}if("-"!=n.text){if("&"==n.text&&e==b){e++;k=0;break}if(dji.charSet.wordSeparator.characterIsMember(n.text)){k=0;break}}}for(;b<=e&&b<g&&(n=c[b],n.ignore);b++);for(;b<=e&&0<=e;e--)try{if(n=c[e],!n.ignore)break}catch(v){break}e<b?e=b:c.length<=e&&(e=c.length-1);a.__selectInDocument(f,b,e-b,k)}};a.__selectInDocument=function(a,d,c,b){var e=a.activeElementInfo.document.getSelection();a=a.custom.map;var k=a[d];e.collapse(k.element,k.offset);0<c&&(d=a[d+c],e.extend(d.element,d.offset+(b||0)))};a.__getContextFromDocument=
function(f,d,c){var b=null;if(d){d=f.document.getSelection();if("Caret"!=d.type||0>=d.rangeCount)return null;c=!0;var b={type:d.type,anchorNode:d.anchorNode,anchorOffset:d.anchorOffset,focusNode:d.focusNode,focusOffset:d.focusOffset},e=f.element&&(dji.utils.elementHasId(f.element,"dji-sru-ocr-content")||dji.utils.elementHasClass(f.element,["dji-sru-ocr-para","dji-sru-ocr-word"])),k=f.element&&dji.utils.elementHasAttribute(f.element,"dji-sru-rewordify-body"),n=dji.utils.closestParent(d.anchorNode,
".dji-sru-outline-title-in-toolbar");f.element&&f.element.nodeType===Node.ELEMENT_NODE&&e||(d.modify("move","right","character"),d.modify("extend","left","word"),d.collapseToStart());var g=f.document.body;e||k?g=k?f.element:document.getElementById("dji-sru-ocr-content"):n?g=n:f.element.isContentEditable&&(g=dji.utils.editorContainer(f.element));(g=dji.utils.lastElementChild(g,!0))&&g.nodeType==Node.TEXT_NODE?d.extend(g,g.textContent.length):g&&d.extend(g,0)}d=a.__mapContentFromDocumentSelection(f);
if(!d)return null;b={type:"document.selection",activeElementInfo:f,element:d.commonAncestor,isEditor:window.dji.utils.isEditor(d.commonAncestor),selection:d.selection,text:d.text,translations:d.translations,custom:{map:d.map,selectionOffset:0},extended:{text:d.text,selection:{start:d.selection.start,length:d.selection.length}},originalSelection:b||d.originalSelection};0<b.text.length&&(d=b.selection.start,e=b.selection.start+b.selection.length,k=d-b.selection.start,b.selection.start+=k,b.selection.length-=
k,b.custom.selectionOffset=d,b.extended.selection=b.selection,b.text=d<e?b.text.slice(d,e):"");0==b.text.trim().length&&(b=null);c&&b&&f.document.getSelection().empty();return b};a.__mapContentFromDocumentSelection=function(f){var d=f.document.getSelection();if("Range"!==d.type)return null;if(0>=d.rangeCount)return{selection:{start:0,length:0},text:"",map:[]};var c=d.getRangeAt(0),c={selection:{start:0,length:0},text:"",map:[],params:{startContainer:c.startContainer,startOffset:c.startOffset,endContainer:c.endContainer,
endOffset:c.endOffset,selection:d,range:c,prevNode:null,stop:!1}};if(c.params.startContainer.nodeType===Node.ELEMENT_NODE){var b=c.params.startContainer;0<c.params.startOffset&&(b=c.params.startContainer.childNodes[c.params.startOffset-1]);var e=c.params;try{for(;b&&b.nodeType!==Node.TEXT_NODE&&b.firstChild;)b=b.firstChild}catch(k){}e.startContainer=b;c.params.startOffset=0}if(c.params.endContainer.nodeType===Node.ELEMENT_NODE&&0<c.params.endOffset){b=c.params.endContainer;0<c.params.endOffset&&(b=
c.params.endContainer.childNodes[c.params.endOffset-1]);e=c.params;try{for(;b&&b.nodeType!==Node.TEXT_NODE&&b.lastChild;)b=b.lastChild}catch(k){}e.endContainer=b;c.params.endContainer.nodeType===Node.ELEMENT_NODE?c.params.endOffset=c.params.endContainer.childElementCount:c.params.endContainer.nodeType===Node.TEXT_NODE?c.params.endOffset=c.params.endContainer.textContent.length:c.params.startOffset=0}e=R(c.params.startContainer,c.params.endContainer)||f.document.body;a.__mapContentFromDocumentSelectionUsingParams(f.document,
e,c,null);f={commonAncestor:e,selection:c.selection,text:c.text,map:c.map,translations:c.translations,originalSelection:{type:d.type,anchorNode:d.anchorNode,anchorOffset:d.anchorOffset,focusNode:d.focusNode,focusOffset:d.focusOffset}};f.selection.length-=f.selection.start;return f};a.__mapContentFromDocumentSelectionUsingParams=function(a,d,c,b){var e=null,t=null,n=null,g=!1;b=[{start:0,end:-1,translated:!1}];for(d=a.createTreeWalker(d,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,function(p){var h=
(p.nodeType===Node.TEXT_NODE?"":p.getAttribute("id")||"").toLowerCase(),b=(p.nodeType===Node.TEXT_NODE?"":p.tagName||"").toUpperCase();dji.utils.elementHasAttribute(p,["dji-sru-rewordify-popup","dji-sru-rewordify-body"])&&(h="dji-sru-rewordify-popup");return!dji.utils.elementIsInsideBody(p)||"STYLE"==b||"SCRIPT"==b||"NOSCRIPT"==b||"SELECT"==b||"INPUT"==b||"TEXTAREA"==b||"IFRAME"==b||"OBJECT"==b||"EMBED"==b||"IMG"==b||0==h.indexOf("dexcontrolscontainer")||0==h.indexOf("__dji_")||0==h.indexOf("dji-")&&
"dji-sru-rewordify-popup"!=h&&"dji-sru-rewordify-body"!=h&&"dji-sru-screen-selection"!=h&&"dji-sru-overlay-selection"!=h&&"dji-sru-ocr-content"!=h&&"dji-sru-ocr-word"!=h?(t||p!==c.params.startContainer||(t=p),n||p!==c.params.endContainer||(n=p),t&&dji.utils.elementIsVisible(p,a)&&(c.text+=" ",c.map.push({element:p,offset:p,text:" ",embedded:!0})),NodeFilter.FILTER_REJECT):dji.utils.elementIsVisible(p,a)?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT},!0);e=d.nextNode();){var v=e.tagName,y=e.nodeType;
if(!t&&(e===c.params.startContainer&&(t=e),!t))continue;n||e!==c.params.endContainer||(n=e);var w=g;e.nodeType===Node.TEXT_NODE&&(w=e.parentNode.classList.contains("dji-sru-rewordify-translated")&&!e.parentNode.classList.contains("dji-sru-rewordify-translated-original"));w!==g&&(b[b.length-1].translated!==w&&b.push({start:c.text.length,end:-1,translated:w}),g=w);null!==c.params.prevNode&&((v=k(v))||y!==Node.TEXT_NODE||(v=k(c.params.prevNode.tagName)),v&&(c.text+=v,c.map.push({element:c.params.prevNode,
offset:c.params.prevNode.childNodes.length,text:v,embedded:!0})));if(e.nodeType===Node.TEXT_NODE){var y=e.textContent,v=e===t?c.params.startOffset:0,w=e===n?c.params.endOffset:y.length,L=null,L=null;if(0!==v||w!==y.length)y=y.substring(v,w);for(w=0;w<y.length;w++)L=y.charAt(w),dji.charSet.invisibleWhiteSpace.characterIsMember(L)||(L=g?L:dji.utils.htmlToAscii(L),c.text+=L,c.map.push({element:e,offset:w+v,text:L,embedded:!1}))}if(n)break;c.params.prevNode=e}c.selection.start=0;c.selection.length=c.text.length;
if(1<b.length){e=RegExp("[a-z\u0100-\uffff]","iu");for(g=1;g<b.length;g++)d=b[g-1],y=b[g],d.translated===y.translated?(b.splice(g,1),g--):d.start===y.start?(b.splice(g-1,1),g--):(v=c.text.substring(d.start,y.start),e.test(v)?d.end=y.start-1:(y.start=d.start,b.splice(g-1,1),g--));for(e=1;e<b.length;e++)b[e-1].translated===b[e].translated&&(b.splice(e,1),e--)}if(1<b.length||b[0].translated){for(e=1;e<b.length;e++)b[e-1].end=b[e].start-1;b[b.length-1].end=c.text.length-1;for(e=0;e<b.length;e++)g=b[e],
g.text=c.text.substring(g.start,g.end+1);c.translations=b}};a.__restoreSelectionInDocument=function(a){if(a.originalSelection){var d=a.originalSelection;a=a.activeElementInfo.document.getSelection();"None"===d.type?a.empty():(a.collapse(d.anchorNode,d.anchorOffset),a.extend(d.focusNode,d.focusOffset))}};a.__clearSelectionInDocument=function(a){try{a.activeElementInfo.document.getSelection().empty()}catch(d){}};a.__insertText=function(a,d,c){c?a.document.execCommand("insertHTML",!1,d):a.document.execCommand("insertText",
!1,d)}})(J={});(function(a){function k(a){var b=e.getBoundingClientRect(),d=[];if(a)return{first:b,last:b,caret:b,clientRects:d,isSelection:!1};a=c.querySelectorAll("div.kix-page-content-wrapper");for(var f=0,p=-1;f<a.length;f++){var h=Array.prototype.slice.call(a[f].querySelectorAll("div.kix-selection-overlay"));if(0<h.length){if(0<=p&&p<f-1)return d=[],{first:b,last:b,caret:b,clientRects:d,isSelection:!1};for(p=0;p<h.length;p++){var D=h[p].getBoundingClientRect();0<D.width&&0<D.height&&d.push(D)}p=
f}}if(0>=d.length)return{first:b,last:b,caret:b,clientRects:d,isSelection:!1};a=0<d.length?d[0]:null;f=0<d.length?d[d.length-1]:null;return a&&f&&(h=(b.top+b.bottom)/2,h<a.top||f.bottom<h)?(d=[],{first:b,last:b,caret:b,clientRects:d,isSelection:!1}):{first:a,last:f,caret:b,clientRects:d,isSelection:!0}}function f(a,b,c){if(null===a)return n.innerHTML="",null;var d={element:null,offset:0,lookAhead:!1},p=a.getBoundingClientRect();b=Math.max(0,b-p.left);g.style.left=b+"px";n.innerHTML="";n.className=
a.className;n.style.cssText=a.style.cssText;for(var h=!1,f=a.childNodes,q=0;!h&&q<f.length;q++){var l=f[q],e=n.innerHTML;1==l.nodeType&&"SPAN"==l.tagName&&(l=l.firstChild);if(3==l.nodeType){for(var p=l.textContent,k=0,F=p.length,t=0,A=0,H=!1;k<F;)if(t=parseInt((k+F)/2),n.innerHTML=e+p.slice(0,t),A=n.offsetWidth,b-.4<=A&&A<=b+.4){k=t;d.element=l;d.offset=k;h=!0;break}else n.offsetWidth<b?k=t+1:(F=t,H=!0);n.innerHTML=e+p.slice(0,k);H&&!h&&(d.element=l,d.offset=k,h=!0);if(h){for(d.lookAhead=!0;d.lookAhead&&
0<=k;k--)d.lookAhead=!dji.charSet.wordSeparator.characterIsMember(p.charAt(k));k++;c&&(d.offset=k)}}else if(p=l.getBoundingClientRect(),n.innerHTML=e+"<span style='width: "+p.width+"px;'></span>",n.offsetWidth<b){d.element=l;d.offset=0;h=!0;break}}!h&&0<f.length&&(d.element=f[f.length-1],1==d.element.nodeType&&"SPAN"==d.element.nodeName&&(d.element=d.element.firstChild),d.offset=3==d.element.nodeType?d.element.textContent.length:d.element.childElementCount);d.kixWordNode=a;return d}function d(){var a=
document.getElementById("__DJI_SRU_CONTAINER");a||(a=document.createElement("div"),a.id="__DJI_SRU_CONTAINER",document.body.appendChild(a));t=document.createElement("div");t.id="__DJI_SRU_GOOGLEDOCS_MEASUREMENT_WINDOW";n=document.createElement("span");n.id="__DJI_SRU_GOOGLEDOCS_MEASUREMENT_WINDOW_SPAN";g=document.createElement("div");g.id="__DJI_SRU_GOOGLEDOCS_MEASUREMENT_WINDOW_CARET";t.appendChild(n);t.appendChild(g);a.appendChild(t)}if(dji.utils.isGoogleDocs()){var c=document.getElementById("kix-appview"),
b=c.getElementsByClassName("kix-appview-editor")[0];c.getElementsByClassName("kix-cursor");var e=c.getElementsByClassName("kix-cursor-caret")[0],t=null,n=null,g=null;a.__getContext=function(a,d,g,n){c=document.getElementById("kix-appview");b=c.getElementsByClassName("kix-appview-editor")[0];c.getElementsByClassName("kix-cursor");e=c.getElementsByClassName("kix-cursor-caret")[0];var p;var h=k(d);if(h.isSelection||d){g=[];var D=[],q=[],l=-1,z=null,E=null,t=null,G=null,A=-1,H=h.first,r=h.last,I=H.left;
p=r.right;var H=(H.top+H.bottom)/2,r=(r.top+r.bottom)/2,D=h.clientRects,m=b.querySelectorAll("div.kix-page div.kix-paragraphrenderer"),l=null,B=[];if(d){D=(h.first.top+h.first.bottom)/2;h=null;q=l=-1;for(q=0;q<m.length&&!(h=m[q].getBoundingClientRect(),D<h.bottom);q++);for(;q<m.length;q++)B.push(m[q])}else if(h.isSelection)for(var l=-1,u=0;u<D.length&&l+1<m.length;u++){for(var C=D[u],q=l+1;q<m.length;q++)if(h=m[q].getBoundingClientRect(),0<h.width&&0<h.height&&!(C.right<=h.left||h.right<=C.left||
C.bottom<=h.top||h.bottom<=C.top)){B.push(m[q]);l=q;q++;break}for(;q<m.length;q++)if(h=m[q].getBoundingClientRect(),0<h.width&&0<h.height)if(C.right<=h.left||h.right<=C.left||C.bottom<=h.top||h.bottom<=C.top)break;else B.push(m[q]),l=q}else{for(var D=(h.first.top+h.first.bottom)/2,q=h.first.left,u=h.first.right,C=h.isSelection?0:h.first.right-h.first.left+1,x=(h.last.top+h.last.bottom)/2,h=h.last.right,K=-1,K=-1,K=0;K<m.length&&!(l=m[K].getBoundingClientRect(),l.top<=D&&D<=l.bottom&&l.left<=u&&q<=
l.right+C);K++);for(;K<m.length;K++)if(l=m[K].getBoundingClientRect(),l.top<x&&l.left<=h&&q<=l.right+C)B.push(m[K]);else break}m=-1;q=h=null;for(m=0;m<B.length;m++)if(h=B[m].querySelectorAll("div.kix-lineview div.kix-lineview-content"),u=-1,u=null,0<h.length){D=[];l=-1;for(u=1;u<h.length;u++)if(q=h[u].getBoundingClientRect(),H<q.top){l=u-1;break}for(-1===l&&(l=h.length-1);l<h.length;l++)if(u=h[l],q=u.getBoundingClientRect(),d||q.top<r)q=u.querySelectorAll("span.kix-lineview-text-block span.kix-wordhtmlgenerator-word-node"),
0<q.length&&(null==z&&(z=q),E=q,D.push(q));else break;0<D.length&&g.push(D)}if(0==g.length)p=null;else{for(m=0;m<z.length;m++)if(h=z[m],q=h.getBoundingClientRect(),I<q.right){t=h;A=m;break}if(d)G=E[E.length-1];else for(m=0;m<E.length;m++)if(h=E[m],q=h.getBoundingClientRect(),q.left<p)G=h;else break;E=f(t,I,d);if(d&&E&&E.lookAhead)for(t=null,H=I=!1,--A;0<=A;A--){h=z[A];r=1==h.childNodes.length?h.firstChild:null;if(!r||r.nodeType!==Node.TEXT_NODE)break;B=r.textContent;for(m=B.length-1;0<=m;m--){t=B.charAt(m);
if(dji.charSet.wordSeparator.characterIsMember(t)){I=!0;break}dji.charSet.invisibleWhiteSpace.characterIsMember(t)||(H=!0)}if(I&&!H)break;m++;m<B.length&&(E.kixWordNode=h,E.element=r,E.offset=m)}z=null;d?(z={element:G.lastChild,offset:0,kixWordNode:G},3==z.element.nodeType&&(z.offset=z.element.textContent.length)):z=f(G,p);p={anchorNode:E.element,anchorOffset:E.offset,extentNode:z.element,extentOffset:z.offset,kixParagraphs:g,kixAnchorNode:E.kixWordNode,kixExtentNode:z.kixWordNode}}}else p=null;if(!p)return null;
d="";g=[];G=[];A=z=!1;for(E=0;!A&&E<p.kixParagraphs.length;E++){t=p.kixParagraphs[E];for(I=0;!A&&I<t.length;I++)for(H=t[I],r=null,B=!1,h=l=m=0;!A&&h<H.length;h++){q=H[h];D=q.childNodes;if(B=r!=q.parentNode)r=q.parentNode,l=r.style,m=l.paddingLeft?parseFloat(l.paddingLeft):0,l=l.paddingRight?parseFloat(l.paddingRight):0;z&&B&&0<m&&(d+=" ",g.push({index:g.length,element:null,offset:0,text:" ",embedded:!0}),G.push(g[g.length-1]));for(q=0;!A&&q<D.length;q++)if(u=D[q],1==u.nodeType&&"SPAN"==u.nodeName&&
(u=u.firstChild),3==u.nodeType){if(z||u==p.anchorNode){C=dji.utils.htmlToAscii(u.textContent,!0);x=0;K=null;u==p.anchorNode?(u==p.extentNode?(C=C.substring(p.anchorOffset,p.extentOffset),A=!0):C=C.substring(p.anchorOffset),x=p.anchorOffset,z=!0):u==p.extentNode&&(C=C.substring(0,p.extentOffset),A=!0);d+=C;for(var J=0;J<C.length;J++)K=C.charAt(J),8203==K.charCodeAt(0)?g.push({index:g.length,element:u,offset:J+x,text:"",embedded:!0,ignore:!0}):(g.push({index:g.length,element:u,offset:J+x,text:K,embedded:!1}),
G.push(g[g.length-1]))}}else z&&(d+=" ",g.push({index:g.length,element:u,offset:q+1,text:" ",embedded:!0}),G.push(g[g.length-1]));z&&B&&0<l&&(d+=" ",g.push({index:g.length,element:null,offset:0,text:" ",embedded:!0}),G.push(g[g.length-1]))}z&&E+1<p.kixParagraphs.length&&(d+="\n",g.push({index:g.length,element:null,offset:0,text:" ",embedded:!0}),G.push(g[g.length-1]))}p=document.getSelection();a={type:"google.docs",activeElementInfo:a,element:b,isEditor:!0,selection:{start:0,length:d.length},text:d,
custom:{map:g,matrix:G,selectionOffset:0},extended:{text:d,selection:{start:0,length:d.length}},originalSelection:{type:p.type,anchorNode:p.anchorNode,anchorOffset:p.anchorOffset,focusNode:p.focusNode,focusOffset:p.focusOffset}};0==a.text.trim().length&&(a=null);n&&a&&p.empty();a&&a.text&&(a.text=a.text.replace(/\u200B/g,""));return a};a.__insertText=function(a,b){dji.logger.lof("Insert Text into to Google Docs is handled by Google!")};d()}})(P={});(function(a){function k(a,b){for(var c=f(b);c;){var q=
d(a,c);if(null!=q)return q;c=f(c)}return null}function f(a){return a.nextElementSibling?a.nextElementSibling:a.parentElement?f(a.parentElement):null}function d(a,b){if(b.className==a)return b;for(var c=null,q=b.childNodes,l=0;l<q.length;l++)if(c=d(a,q[l]))return c;return null}function c(){window.top.sru.speech.stop()}function b(a){if(33<=a.keyCode&&40>=a.keyCode)return a.preventDefault(),a.stopPropagation(),!1}function e(){var a=document.getElementById("__DJI_SRU_CONTAINER");a||(a=document.createElement("div"),
a.id="__DJI_SRU_CONTAINER",document.body.appendChild(a))}if(dji.utils.isAmazonKindle()){var t=null,n=null,g=null,v=[],y=null,w=[],x=null;a.__getContext=function(a,b,d){t=document.getElementById("KindleReaderIFrame").contentWindow.document;n=a.iframes[0].contentWindow.document;g=a.iframes[1]?a.iframes[1].contentWindow.document:null;if(0<n.getElementsByClassName("amazon-selection").length)if(v=n.getElementById("annotation-section").getElementsByClassName("amazon-selection"),0<n.getElementById("annotation-section").childNodes.length)for(var c=
n.getElementById("annotation-section"),c=c.childNodes,l=c.length-1;0<=l;l--)"kindle.selection"==c[l].getAttribute("annotationtype")&&(y=c[l].attributes.annotationstart.value);else v=[],y=null;else v=[],y=null;if(g&&0<g.getElementsByClassName("amazon-selection").length)if(w=g.getElementById("annotation-section").getElementsByClassName("amazon-selection"),0<g.getElementById("annotation-section").childNodes.length)for(c=g.getElementById("annotation-section"),c=c.childNodes,l=c.length-1;0<=l;l--)"kindle.selection"==
c[l].getAttribute("annotationtype")&&(x=c[l].attributes.annotationstart.value);else w=[],x=null;else w=[],x=null;c=v&&0!=v.length||w&&0!=w.length?{leftSelection:v,leftSelectionStart:y,rightSelection:w,rightSelectionStart:x}:null;if(!c)return null;var c="",f=[],e=n.getElementById(y);!e&&g&&(e=g.getElementById(x));e&&":"==e.id.charAt(1)&&(e=e.childNodes[0]);for(var l=0,l=y?parseInt(y):parseInt(x),F=null,F=0<v.length?v[0]:w[0],G=parseFloat(F.style.width),A=parseFloat(F.style.left),H=parseFloat(F.style.height),
r=e,I=g?g.getElementById(r.id):null,e=e.parentNode;e&&0>e.id.indexOf(":");)e=e.parentNode;var m=e,B=!0,u=!0;if(b)for(F=parseInt(a.iframes[0].style.height);B;){c+=r.innerText;for(b=0;b<r.innerText.length;b++)f.push({element:r,equivalentInRightPage:I,offset:parseInt(r.id)-l+b,text:r.innerText.charAt(b),embedded:!1});for(m=r=k("k4w",r);m&&0>m.id.indexOf(":");)m=m.parentNode;if(r){if(I=g?g.getElementById(r.id):r,B=I.getBoundingClientRect().bottom<F)c+=e==m?" ":"\n",f.push({element:null,offset:parseInt(r.id)-
l-1,text:" ",embedded:!0}),e=m}else B=!1}else for(;B&&u;)if(m=r.getBoundingClientRect(),I=g?g.getElementById(r.id):r,m.left<G+A){c+=r.innerText;for(b=0;b<r.innerText.length;b++)f.push({element:r,equivalentInRightPage:I,offset:parseInt(r.id)-l+b,text:r.innerText.charAt(b),embedded:!1});if(m.height>H||m.right==G+A)(F=F.nextElementSibling)?(G=parseFloat(F.style.width),A=parseFloat(F.style.left),u=!0):u=!1;for(m=r=k("k4w",r);m&&0>m.id.indexOf(":");)m=m.parentNode;r?(c+=e==m?" ":"\n",f.push({element:null,
offset:parseInt(r.id)-l-1,text:" ",embedded:!0}),B=!0,e=m):B=!1}else(F=F.nextElementSibling)?(G=parseFloat(F.style.width),A=parseFloat(F.style.left),u=!0):u=!1;b=[];r=[];for(l=0;l<v.length;l++)b.push(v[l].cloneNode(!0));for(l=0;l<w.length;l++)r.push(w[l].cloneNode(!0));a={type:"amazon.kindle",activeElementInfo:a,element:t.body,isEditor:!0,selection:{start:0,length:c.length},text:c,custom:{map:f,selectionOffset:0},extended:{text:c,selection:{start:0,length:c.length}},originalSelection:{type:"amazon.kindle",
leftPageSelection:b,rightPageSelection:r}};0==a.text.trim().length&&(a=null);if(d&&a){d=v[0]?v[0].parentNode:null;for(l=v.length-1;0<=l;l--)v[l].parentNode.removeChild(v[l]);d&&0==d.childNodes.length&&d.parentNode.removeChild(d);d=w[0]?w[0].parentNode:null;for(l=w.length-1;0<=l;l--)w[l].parentNode.removeChild(w[l]);d&&0==d.childNodes.length&&d.parentNode.removeChild(d)}return a};a.__enableSelection=function(a){if(a)for(dji.utils.activeElementInfo().element.getElementById("kindleReader_touchLayer").setAttribute("style",
"z-index: -1;"),dji.utils.activeElementInfo().element.getElementsByClassName("header")[0].setAttribute("style","z-index: -1;"),dji.utils.activeElementInfo().element.getElementsByClassName("footer")[0].setAttribute("style","z-index: -1;"),dji.utils.activeElementInfo().element.getElementById("appBarOverlay")&&(a=dji.utils.activeElementInfo().element.getElementById("appBarOverlay"),a.click.apply(a)),dji.utils.activeElementInfo().iframes[0].contentWindow.document.body.style.webkitUserSelect="auto",dji.utils.activeElementInfo().iframes[1]&&
(dji.utils.activeElementInfo().iframes[1].contentWindow.document.body.style.webkitUserSelect="auto"),dji.utils.activeElementInfo().iframes[0].contentWindow.addEventListener("resize",c),dji.utils.activeElementInfo().iframes[1]&&dji.utils.activeElementInfo().iframes[1].contentWindow.addEventListener("resize",c),document.addEventListener("keydown",b,!0),document.addEventListener("keyup",b,!0),a=document.getElementById("KindleReaderIFrame").contentWindow.document,a.addEventListener("keydown",b,!0),a.addEventListener("keyup",
b,!0),a=0;a<dji.utils.activeElementInfo().iframes.length;a++){var d=dji.utils.activeElementInfo().iframes[a].contentWindow.document;d.addEventListener("keydown",b,!0);d.addEventListener("keyup",b,!0)}else for(dji.utils.activeElementInfo().element.getElementById("kindleReader_touchLayer").setAttribute("style","z-index: 200;"),dji.utils.activeElementInfo().element.getElementsByClassName("header")[0].setAttribute("style","z-index: 490;"),dji.utils.activeElementInfo().element.getElementsByClassName("footer")[0].setAttribute("style",
"z-index: 490;"),dji.utils.activeElementInfo().iframes[0].contentWindow.document.body.style.webkitUserSelect="none",dji.utils.activeElementInfo().iframes[1]&&(dji.utils.activeElementInfo().iframes[1].contentWindow.document.body.style.webkitUserSelect="none"),dji.utils.activeElementInfo().iframes[0].contentWindow.removeEventListener("resize",c),dji.utils.activeElementInfo().iframes[1]&&dji.utils.activeElementInfo().iframes[1].contentWindow.removeEventListener("resize",c),document.removeEventListener("keydown",
b,!0),document.removeEventListener("keyup",b,!0),a=document.getElementById("KindleReaderIFrame").contentWindow.document,a.removeEventListener("keydown",b,!0),a.removeEventListener("keyup",b,!0),a=0;a<dji.utils.activeElementInfo().iframes.length;a++)d=dji.utils.activeElementInfo().iframes[a].contentWindow.document,d.removeEventListener("keydown",b,!0),d.removeEventListener("keyup",b,!0)};a.__simulateSelectionFromEvent=function(a){var b=a.view.document;if(dji.utils.activeElementInfo().iframes[0].contentWindow.document==
b||dji.utils.activeElementInfo().iframes[1]&&dji.utils.activeElementInfo().iframes[1].contentWindow.document==b){var c=b.getElementById("content-overlays");c||(c=b.createElement("div"),c.id="content-overlays",c.setAttribute("style","position: absolute; top: -20px; left: -18px;"),b.getElementById("content-overlays")?c=b.getElementById("content-overlays"):b.appendChild(c));var d=b.getElementById("annotation-section");d||(d=b.createElement("div"),d.id="annotation-section",d.setAttribute("class","kindle-annotation-wrapper"),
b.getElementById("annotation-section")?d=b.getElementById("annotation-section"):c.appendChild(d));c=b.createElement("div");c.setAttribute("annotationtype","kindle.selection");c.setAttribute("annotationstart",a.target.id);c.setAttribute("data-annotationclickable","false");d.appendChild(c);d=b.createElement("div");d.setAttribute("class","amazon-selection");b=Math.abs(parseInt(b.body.style.top))+parseInt(a.target.getBoundingClientRect().top);d.setAttribute("style","top: "+b+"px; height: "+a.target.getBoundingClientRect().height+
"px; left: "+a.target.getBoundingClientRect().left+"px; width: "+a.target.getBoundingClientRect().width+"px");c.appendChild(d)}};a.__selectWordInAmazonKindle=function(a,b){var c=a.activeElementInfo.iframes[0].contentWindow.document.getSelection(),d=a.activeElementInfo.iframes[1]?a.activeElementInfo.iframes[1].contentWindow.document.getSelection():null,e=a.custom.map[b].element,f=a.custom.map[b].equivalentInRightPage;a.activeElementInfo.iframes[1]?(e&&f&&0>f.getBoundingClientRect().top?(e.style.webkitUserSelect=
"auto",a.selectableSpans||(a.selectableSpans=[]),a.selectableSpans.push(e),c.collapse(e,0),c.extend(e,1)):c.empty(),f&&(f.style.webkitUserSelect="auto",a.selectableSpans||(a.selectableSpans=[]),a.selectableSpans.push(e),d.collapse(f,0),d.extend(f,1))):(e.style.webkitUserSelect="auto",a.selectableSpans||(a.selectableSpans=[]),a.selectableSpans.push(e),c.collapse(e,0),c.extend(e,1))};a.__restoreSelectionInAmazonKindle=function(a){a.activeElementInfo.iframes[0].contentWindow.document.getSelection().empty();
a.activeElementInfo.iframes[1]&&a.activeElementInfo.iframes[1].contentWindow.document.getSelection().empty();for(var b=0;a.selectableSpans&&b<a.selectableSpans.length;b++)a.selectableSpans[b].removeAttribute("style");if(a.originalSelection){if(b=n.getElementById("annotation-section"))for(var c=b.childNodes,b=0;b<c.length;b++)if("kindle.selection"==c[b].getAttribute("annotationtype")){for(var d=0;d<a.originalSelection.leftPageSelection.length;d++)c[b].appendChild(a.originalSelection.leftPageSelection[d]);
break}if(g&&(b=g.getElementById("annotation-section")))for(c=b.childNodes,b=0;b<c.length;b++)if("kindle.selection"==c[b].getAttribute("annotationtype")){for(d=0;d<a.originalSelection.rightPageSelection.length;d++)c[b].appendChild(a.originalSelection.rightPageSelection[d]);break}}};a.__clearSelectionInAmazonKindle=function(a){a.activeElementInfo.iframes[0].contentWindow.document.getSelection().empty();a.activeElementInfo.iframes[1]&&a.activeElementInfo.iframes[1].contentWindow.document.getSelection().empty();
try{for(var b=n.getElementById("content-overlays"),c=b.getElementById("annotation-section"),d=c.childNodes,e=d.length-1;0<=e;e--)"kindle.selection"==d[e].getAttribute("annotationtype")&&c.removeChild(d[e]);if(g)for(b=g.getElementById("content-overlays"),c=b.getElementById("annotation-section"),d=c.childNodes,e=d.length;0<=e;e--)"kindle.selection"==d[e].getAttribute("annotationtype")&&c.removeChild(d[e])}catch(f){}};e()}})(N={})})(window.dji.selectionMapper=window.dji.selectionMapper||{});
