window.sru=window.sru||{};
(function(d){function m(a,b){var e=$("#dji-sru-toast");e.length||(e=$("<div id='dji-sru-toast'></div>"),e.appendTo($("body")));a?e.removeClass("dji-sru-toast-info").addClass("dji-sru-toast-error"):e.removeClass("dji-sru-toast-error").addClass("dji-sru-toast-info");e.text(b);e.show(500);e.timer&&(clearTimeout(e.timer),e.timer=null);e.timer=setTimeout(function(){e.timer=null;e.hide(500)},1E4)}function h(a,c){try{if(b=dji.selectionMapper.mapSelection({fromCaretToEnd:a,clearSelection:!0,accurate:!0})){b.clearSelectionAtEnd=
dji.utils.isAmazonKindle()&&a?!0:c;dji.utils.preventInputEventsOnBodyElements(!0,!1,null,!0);dji.selectionMapper.enableHighlight(!0);dji.utils.addClassToHtmlElements("dji-sru-speak-waiting",!0);var e=[];if(b.translations&&0<b.translations.length)for(var d=0;d<b.translations.length;d++)e.push({text:b.translations[d].text,isTranslated:b.translations[d].translated});else e.push({text:b.text,isTranslated:!1});dji.utils.callListeners(f,"start",e)}return!0}catch(g){b&&(b=null,dji.selectionMapper.enableHighlight(!1)),
dji.logger.error(g)}return!1}function k(){var a=null!=b;dji.utils.removeEventListenerFromBodyElements("click",l,!0,!0);dji.utils.preventInputEventsOnBodyElements(!1,!1,null,!0);b&&(b.clearSelectionAtEnd?dji.selectionMapper.clearSelection(b):dji.selectionMapper.restoreSelection(b),dji.selectionMapper.enableHighlight(!1));dji.utils.removeClassFromHtmlElements("dji-sru-speak-from-cursor",!0);dji.utils.removeClassFromHtmlElements("dji-sru-speak-active",!0);dji.utils.removeClassFromHtmlElements("dji-sru-speak-waiting",
!0);dji.selectionMapper.enableSelection(!1);return a}function l(a){if(a.target)if(b)dji.utils.elementHasId(a.target,"__dji_sru_speakButton")||(dji.utils.elementHasClass(a.target,"dji-sru-close-btn")?d.stop():(a.preventDefault(),a.stopPropagation(),d.restart()));else{var c=["dji-sru-close-btn","dji-sru-overlay-child","dji-sru-toolbar","dji-sru-toolbar-button"];if(!dji.utils.elementHasId(a.target,["dji-sru-busy-state","dji-sru-screen-selection","dji-sru-x-line","dji-sru-y-line","dji-sru-crosshair"])&&
!dji.utils.elementHasClass(a.target,c)){a.__dji_sru_speak_cursor=!0;if("A"==a.target.tagName||dji.utils.elementHasClass(a.target,["dji-sru-ocr-word","dji-sru-outline-title-in-toolbar"]))a.preventDefault(),a.stopPropagation(),c=dji.utils.documentForElement(a.target).getSelection(),c.selectAllChildren(a.target),c.collapseToStart();dji.utils.elementHasClass(document.documentElement,"dji-sru-rewordify-active")||dji.utils.elementHasSpecialAttribute(document.documentElement,"dji-sru-rewordify-active")||
dji.selectionMapper.simulateSelectionFromEvent(a);setTimeout(function(){h(!0)},0)}}}var f={activate:[],start:[],stop:[]},b=null,c=!1,g=!1;d.initialize=function(){};d.addEventListener=function(a,b){f.hasOwnProperty(a)&&"function"==typeof b&&-1==f[a].indexOf(b)&&f[a].push(b)};d.isActive=function(){return c};d.start=function(a){c||(c=!0,dji.utils.callListeners(f,"activate",c),(c=h(!1,a))?(dji.utils.addClassToHtmlElements("dji-sru-speak-from-cursor",!0),dji.utils.preventInputEventsOnBodyElements(!0,!1,
null,!0),dji.selectionMapper.enableSelection(!0),dji.utils.addEventListenerToBodyElements("click",l,!0,!0)):(dji.utils.callListeners(f,"activate",c),dji.selectionMapper.enableSelection(!1)))};d.restart=function(){c&&(g=!0,dji.utils.callListeners(f,"stop"))};d.stop=function(){c&&(g=!1,k()&&dji.utils.callListeners(f,"stop"),c=!1,dji.utils.callListeners(f,"activate",c),dji.selectionMapper.enableSelection(!1))};d.speakStart=function(){dji.utils.removeClassFromHtmlElements("dji-sru-speak-waiting",!0);
dji.utils.addClassToHtmlElements("dji-sru-speak-active",!0)};d.speakWait=function(){dji.utils.removeClassFromHtmlElements("dji-sru-speak-active",!0);dji.utils.addClassToHtmlElements("dji-sru-speak-waiting",!0)};d.speakProgress=function(a){c&&b&&dji.selectionMapper.selectWord(b,a.charIndex)};d.speakStop=function(){c&&(g?(b&&(dji.selectionMapper.clearSelection(b),b=null,dji.selectionMapper.enableHighlight(!1)),dji.utils.removeClassFromHtmlElements("dji-sru-speak-waiting",!0),dji.utils.removeClassFromHtmlElements("dji-sru-speak-active",
!0),dji.utils.addClassToHtmlElements("dji-sru-speak-from-cursor",!0),dji.selectionMapper.enableSelection(!0)):(k(),b=null,c=!1,dji.utils.callListeners(f,"activate",c)))};d.speakError=function(a){c&&(dji.logger.error(a),m(!0,"No connection. Snap&Read will use offline voice."))}})(window.sru.speech=window.sru.speech||{});
