window.sru=window.sru||{};
(function(e){function g(b,a){var d=c[b];a?dji.utils.removeClassFromElement(d.button,"dji-sru-disabled"):dji.utils.addClassToElement(d.button,"dji-sru-disabled");d.enabled=a}function k(b,a){var d=c[b];a!=d.active&&(a?dji.utils.addClassToElement(d.button,"dji-sru-active"):dji.utils.removeClassFromElement(d.button,"dji-sru-active"),d.active=a)}function l(b,a){var d=c[b];a!=d.visible&&(a?dji.utils.removeClassFromElement(d.button,"dji-sru-hidden"):dji.utils.addClassToElement(d.button,"dji-sru-hidden"),
d.visible=a)}function w(b){b.preventDefault();b.stopPropagation()}function m(){c[a.speak].enabled&&dji.utils.callListeners(f,"speak")}function n(){c[a.screenshot].enabled&&dji.utils.callListeners(f,"screenshot")}function p(){c[a.rewordify].enabled&&dji.utils.callListeners(f,"rewordify")}function q(){c[a.translate].enabled&&dji.utils.callListeners(f,"translate")}function r(b){(c[a.highlight].enabled||1==b)&&dji.utils.callListeners(f,"highlight",b)}function t(b){(c[a.showOutlines].enabled=b)?dji.utils.addClassToHtmlElements("dji-sru-outline-active",
!0):(dji.utils.removeClassFromHtmlElements("dji-sru-outline-active",!0),sru.outlines.hideBulletToolbars())}var u=!1,f={speak:[],screenshot:[],rewordify:[],translate:[],showOutlines:[],highlight:[]},a={speak:"__dji_sru_speakButton",screenshot:"__dji_sru_screenshotButton",rewordify:"__dji_sru_rewordifyButton",translate:"__dji_sru_translateButton",showOutlines:"__dji_sru_showButton",highlight:"__dji_sru_highlightButton"},x={speak:m,screenshot:n,rewordify:p,translate:q,showOutlines:function(){dji.utils.callListeners(f,
"showOutlines",!c[a.showOutlines].enabled);t(!c[a.showOutlines].enabled)},highlight:r},c={},v=null;e.initialize=function(){if(!u){v=sru.mainContainer.mainContainer().querySelector(".dji-sru-toolbar");dji.shortcuts.initialize();dji.shortcuts.addEventListener("speak",m);dji.shortcuts.addEventListener("screenshot",n);dji.shortcuts.addEventListener("rewordify",p);dji.shortcuts.addEventListener("translate",q);for(var b in a)if(a.hasOwnProperty(b)){var h=v.querySelector("#"+a[b]);h.addEventListener("mousedown",
w);h.onclick=x[b];c[a[b]]={button:h,active:!1,enabled:!0,visible:!0};"highlight"===b&&(c[a[b]].highlightable=!1,g(a.highlight,!1))}c[a.showOutlines].enabled=!1;u=!0}};e.addEventListener=function(b,a){f.hasOwnProperty(b)&&"function"==typeof a&&-1==f[b].indexOf(a)&&f[b].push(a)};e.enableButtons=function(b,h,d,c,e){null!==b&&void 0!==b&&g(a.speak,b);null!==h&&void 0!==h&&g(a.screenshot,h);null!==d&&void 0!==d&&g(a.rewordify,d);null!==c&&void 0!==c&&g(a.translate,c);null!==e&&void 0!==e&&sru.outlines.isHighlightable()&&
g(a.highlight,e)};e.enableHighlightButton=function(b){b&&(c[a.translate].active||c[a.rewordify].active)&&!c[a.speak].enabled||g(a.highlight,b)};e.activateHighlightButton=function(b){k(a.highlight,b)};e.disableHighlight=function(){r(!0)};e.isHighlightActive=function(){return c[a.highlight].active&&c[a.highlight].enabled};e.activateButtons=function(b,c,d,e,f){null!==b&&void 0!==b&&k(a.speak,b);null!==c&&void 0!==c&&k(a.screenshot,c);null!==d&&void 0!==d&&k(a.rewordify,d);null!==e&&void 0!==e&&k(a.translate,
e);null!==f&&void 0!==f&&k(a.highlight,f)};e.showButtons=function(b,c,d,e){null!==b&&void 0!==b&&l(a.speak,b);null!==c&&void 0!==c&&l(a.screenshot,c);null!==d&&void 0!==d&&l(a.rewordify,d);null!==e&&void 0!==e&&l(a.translate,e)};e.expandOutlinesPanel=function(a){t(a)};e.setTitle=function(a){var c=sru.mainContainer.mainContainer().querySelector(".dji-sru-outline-title-in-toolbar");c&&(a?a.isSkeleton()?c.innerText="Outline Name":a.isHome()?c.innerText="":c.innerText=a.title():c.innerText="")}})(window.sru.toolbar=
window.sru.toolbar||{});
