window.dji=window.dji||{};
(function(n){function J(){dji.utils.preventInputEventsOnBodyElements(!1);dji.utils.removeEventListenerFromBodyElements("selectstart",B,!0);dji.utils.removeEventListenerFromBodyElements("mouseup",C,!0);dji.utils.removeEventListenerFromBodyElements("click",K,!0);dji.utils.removeClassFromHtmlElements("dji-sru-translate-from-cursor");dji.utils.removeClassFromHtmlElements("dji-sru-rewordify-active");dji.utils.removeClassFromElement(b.main,"dji-visible");dji.selectionMapper.enableSelection(!1);if(b.isActive)b.body.innerText=
"",b.main.style.setProperty("left","-10000px"),b.main.style.setProperty("top","-10000px"),b.main.style.setProperty("width","auto"),b.main.style.setProperty("height","auto"),b.isActive=!1;else if(f){for(var a=null,d=f.initialContext.activeElementInfo.document,g=d.getElementsByClassName("dji-sru-rewordify-chunk"),c=g.length-1;0<=c;c--){var e=g[c],h=e.__dji_sru_rewordify_data?e.__dji_sru_rewordify_data.originalText:e.firstChild.textContent;a&&a!=e.parentElement&&a.normalize();a=e.parentElement;e.parentElement.replaceChild(d.createTextNode(h),
e)}a&&a.normalize()}N();f&&f&&dji.selectionMapper.clearSelection(f.initialContext);w=f=null;D=!1;dji.utils.callListeners(z,"deactivate");dji.utils.removeClassFromElement(document.documentElement,"dji-sru-bodycover");window.dji.ui.effects.leaveBusyState()}function L(){try{var a=dji.selectionMapper.mapSelection({fromCaretToEnd:!1,clearSelection:!0});if(a&&a.text&&0<a.text.length&&0<a.text.trim().length){var d=a,g=a.element.getBoundingClientRect();dji.utils.addClassToHtmlElements("dji-sru-rewordify-active");
if(dji.utils.isSruPdf()||dji.utils.isAmazonKindle()||x())a.isEditor=!0;w=dji.utils.generateUUID();if(a.isEditor){b.isActive=!0;b.body.innerText=a.text.trim();b.body.scrollTop=0;var c="input"!==a.type&&a.custom.map?a.custom.map[0].element.parentElement:a.element;x()&&(c=document.getElementById("dji-sru-overlay-selection").getElementsByTagName("span")[0]);if(c){var e=window.getComputedStyle(c,null).getPropertyValue("font-size");b.body.style.fontSize=""!=c.style.fontSize?parseFloat(c.style.fontSize)+
"px":e;var h=window.getComputedStyle(c,null).getPropertyValue("font-style");b.body.style.fontStyle=0<h.length?h:c.style.fontStyle;var r=window.getComputedStyle(c,null).getPropertyValue("font-family");b.body.style.fontFamily=0<r.length?r:c.style.fontFamily;var t=window.getComputedStyle(c,null).getPropertyValue("font-variant");b.body.style.fontVariant=0<t.length?t:c.style.fontVariant;var v=window.getComputedStyle(c,null).getPropertyValue("font-weight");b.body.style.fontWeight=0<v.length?v:c.style.fontWeight;
c.getBoundingClientRect&&(g=c.getBoundingClientRect())}}x()&&sru.screenSelection.activate(!1);window.dji.ui.effects.enterBusyState();b.isActive&&(dji.utils.addClassToElement(document.documentElement,"dji-sru-bodycover"),dji.utils.removeClassFromHtmlElements("dji-sru-translate-from-cursor"),dji.utils.removeEventListenerFromBodyElements("selectstart",B,!0),dji.utils.removeEventListenerFromBodyElements("mouseup",C,!0),dji.utils.removeEventListenerFromBodyElements("click",K,!0),dji.selectionMapper.enableSelection(!1));
setTimeout(function(){if(w===w){var a=d;d.isEditor&&(dji.utils.addClassToElement(b.main,"dji-working"),dji.utils.addClassToElement(b.main,"dji-visible"),d=null,b.body.firstChild?(document.getSelection().setBaseAndExtent(b.body.firstChild,0,b.body.lastChild,b.body.lastChild.textContent.length),d=dji.selectionMapper.mapDocumentSelection({iframes:[],document:document,element:b.body},!0)):document.getSelection().empty());if(!d||0>=d.text.length)J();else{f={initialContext:a,selectionContext:d,boundingRect:g,
translateTokens:[]};for(var a="",c=[{length:f.selectionContext.text.length,pos:0,words:[f.selectionContext.text]}],e=f.selectionContext,h=e.custom.selectionOffset,m=[],p=null,r=null,u=null,k=null,t=null,q=-1,v=-1,F=0;F<c.length;F++)if(u=c[F],u.words&&!(0>=u.words.length))for(q=u.pos,v=u.pos+u.length,u=k=null;q<v;q++){try{t=e.custom.map[q+h],k=t.element}catch(n){throw dji.logger.error(n),n;}r&&u==k?r.range.length++:(r={element:k,range:{offset:q,start:t.offset,length:1}},p&&p.element==k||(p={element:k,
chunks:[]},m.push(p)),p.chunks.push(r));u=k}for(c=0;c<m.length;c++)if(m[c].element&&m[c].element.data&&""!=m[c].element.data.trim()){e=m[c].chunks;h="";for(p=0;p<e.length;p++)a+=e[p].element.data.substr(e[p].range.start,e[p].range.length),h+=e[p].element.data.substr(e[p].range.start,e[p].range.length);f.translateTokens.push({words:[h],pos:e[0].range.offset,length:h.length});c<m.length-1&&(a+="||")}dji.utils.callListeners(z,"translateFromToolbar",a,w)}}},0)}else dji.utils.addClassToHtmlElements("dji-sru-translate-from-cursor"),
dji.utils.addEventListenerToBodyElements("selectstart",B,!0),dji.utils.addEventListenerToBodyElements("mouseup",C,!0),dji.utils.addEventListenerToBodyElements("click",K,!0),dji.selectionMapper.enableSelection(!0),dji.utils.isAmazonKindle()&&!x()&&dji.utils.activeElementInfo().element.getElementById("kindleReader_touchLayer").setAttribute("style","z-index: 200;");return!0}catch(l){dji.logger.error(l)}return!1}function B(a){y=!0}function C(a){if(!dji.utils.elementHasSpecialAttribute(document.documentElement,
"dji-sru-speak-from-cursor")&&!dji.utils.elementHasSpecialAttribute(document.documentElement,"dji-sru-outline-highlight-active")&&a){if(dji.utils.isGoogleDocs()||dji.utils.isAmazonKindle())y=!0;if(y){var b=["dji-sru-close-btn","dji-sru-overlay-child","dji-sru-toolbar","dji-sru-rewordify-translated"],g=["dji-sru-rewordify-body"];dji.utils.elementHasId(a.target,["dji-sru-busy-state","dji-sru-screen-selection","dji-sru-x-line","dji-sru-y-line","dji-sru-crosshair"])||dji.utils.elementHasClass(a.target,
b)||dji.utils.elementHasAttribute(a.target,g)||(y=!1,a=dji.utils.documentForElement(a.target).getSelection(),U(a),(dji.utils.isGoogleDocs()||dji.utils.isAmazonKindle()||!a.getRangeAt(0).collapsed)&&setTimeout(function(){L()},0))}}}function U(a){a=window.getSelection();if(!a.isCollapsed){var b=document.createRange();b.setStart(a.anchorNode,a.anchorOffset);b.setEnd(a.focusNode,a.focusOffset);var g=b.collapsed,c=a.focusNode,e=a.focusOffset;a.collapse(a.anchorNode,a.anchorOffset);b=[];b=g?["backward",
"forward"]:["forward","backward"];a.modify("move",b[0],"character");a.modify("move",b[1],"word");a.extend(c,e);g=a.toString().charAt(a.toString().length-1);dji.charSet.wordSeparator.characterIsMember(g)||(a.modify("extend",b[1],"character"),a.modify("extend",b[0],"word"))}}function K(a){a.srcElement.classList.contains("dji-sru-rewordify-translated")||(a.preventDefault(),a.stopPropagation())}function V(a){a.__dji_sru_speak_cursor||sru.speech.isActive()||(a.preventDefault(),a.stopPropagation(),a=a.srcElement.__dji_sru_rewordify_data.word,
a.currentWord=(a.currentWord+1)%a.words.length,Q(a),a.currentWord==a.words.length-1?R():N())}function Q(a){for(var b=a.chunks,g=0,c=a.words[a.currentWord],e=0;e<b.length;e++){var h=b[e],f="";c&&(f=e<b.length-1?c.substring(g,g+h.range.length):c.substring(g));g+=h.range.length;0==a.currentWord?dji.utils.addClassToElement(h.dji_span,"dji-sru-rewordify-translated-original"):dji.utils.removeClassFromElement(h.dji_span,"dji-sru-rewordify-translated-original");h.dji_span.innerText=e<b.length-1?f:f+String.fromCharCode(8203)}}
function R(){if(!(0<document.getElementsByClassName("dji-sru-google-translate-logo").length)){var a=document.createElement("a");a.setAttribute("href","http://translate.google.com");a.setAttribute("class","dji-sru-google-translate-logo");document.body.appendChild(a);var b=document.createElement("img");b.setAttribute("class","dji-sru-google-translate-logo-img");a.appendChild(b)}}function N(){0<document.getElementsByClassName("dji-sru-google-translate-logo").length&&0==document.getElementsByClassName("dji-sru-rewordify-translated").length&&
document.body.removeChild(document.getElementsByClassName("dji-sru-google-translate-logo")[0])}function S(a){var d=a.toElement;if(d!=b.main.tl&&d!=b.main.bl&&d!=b.main.br){for(;d&&d!=b.body&&d!=b.main;)d=d.parentElement;d!=b.body&&(a.preventDefault(),a.stopPropagation())}}function x(){return dji.utils.elementHasClass(document.documentElement,"dji-sru-screen-selection")}var T=!1,z={activate:[],deactivate:[],translateFromToolbar:[],translateDone:[]},D=!1,w=null,f=null,b={main:null,close:null,body:null,
isActive:!1};n.initialize=function(){T=!0;b.main=document.createElement("div");b.main.setAttribute("dji-sru-rewordify-popup",!0);b.main.addEventListener("mousedown",S,!0);b.close=document.createElement("div");b.close.setAttribute("class","dji-sru-close-btn");b.close.addEventListener("mousedown",S,!0);b.close.addEventListener("click",J,!0);b.main.appendChild(b.close);b.body=document.createElement("div");b.body.setAttribute("dji-sru-rewordify-body",!0);b.body.setAttribute("tabindex","0");b.main.appendChild(b.body);
b.main.tl=document.createElement("div");dji.utils.addClassToElement(b.main.tl,"dynDiv_resizeDiv_tl");b.main.appendChild(b.main.tl);b.main.bl=document.createElement("div");dji.utils.addClassToElement(b.main.bl,"dynDiv_resizeDiv_bl");b.main.appendChild(b.main.bl);b.main.br=document.createElement("div");dji.utils.addClassToElement(b.main.br,"dynDiv_resizeDiv_br");b.main.appendChild(b.main.br);document.body.appendChild(b.main);(dji.utils.isSruPdf()||dji.utils.isAmazonKindle())&&ByRei_dynDiv.init.main()};
n.addEventListener=function(a,b){z.hasOwnProperty(a)&&"function"==typeof b&&-1==z[a].indexOf(b)&&z[a].push(b)};n.isActive=function(){return D};n.activate=function(a,d){T&&a!=D&&(a?(dji.utils.callListeners(z,"activate"),dji.utils.preventInputEventsOnBodyElements(!0),(D=L())||J()):d&&!b.isActive||J())};var y=!1;n.processTranslationDone=function(a){if(a&&a.translatedText){f.translatedText=a.translatedText;f.originalText=a.originalText;try{var d=f.translatedText.split("||");for(a=0;a<d.length;a++)f.translateTokens[a]?
f.translateTokens[a].words.push(d[a]):f.translateTokens.push({words:[""],pos:0,length:0});var g=f.selectionContext,c=g.custom.selectionOffset,d=[];a=null;for(var e=[],h=null,r=null,t=null,v=null,l=null,n=null,E=null,w=null,m=-1,p=-1,D=-1,u=0;u<f.translateTokens.length;u++){var k=f.translateTokens[u];if(k.words&&!(0>=k.words.length)){p=k.pos;D=k.pos+k.length;n=E=null;dji.logger.log(f.selectionContext.text.substr(k.pos,k.length),JSON.stringify(k));for(var v={index:d.length,range:{start:k.pos+c,length:k.length},
chunks:[],words:k.words,currentWord:0,tooltip:k.words.join(", ")},x=p;x<D;x++){try{w=g.custom.map[x+c],E=w.element}catch(y){throw dji.logger.error(y),y;}l&&n==E?l.range.length++:(l={element:E,range:{offset:x,start:w.offset,length:1},group:v.index},v.chunks.push(l),h&&h.element==E||(h={element:E,chunks:[]},e.push(h)),h.chunks.push(l));n=E}d.push(v)}}f.words=d;for(m=0;m<e.length;m++){h=e[m];n=h.element;a=h.chunks;for(var q=document.createDocumentFragment(),g=0,O=n.textContent,c=0;c<a.length;c++)l=a[c],
g<l.range.start&&(r=O.substring(g,l.range.start),q.appendChild(document.createTextNode(r))),r=O.substring(l.range.start,l.range.start+l.range.length),g=l.range.start+l.range.length,t=document.createElement("span"),t.innerText=r,t.setAttribute("dji-sru-rewordify-group",l.group),t.setAttribute("class","dji-sru-rewordify-chunk dji-sru-rewordify-translated"),t.addEventListener("click",V),q.appendChild(t),t.__dji_sru_rewordify_data={word:d[l.group],originalText:r},l.dji_span=t;g<O.length&&(r=O.substring(g),
q.appendChild(document.createTextNode(r)));n.parentElement.replaceChild(q,n)}for(m=0;m<d.length;m++)d[m].currentWord=Math.min(1,d[m].words.length),Q(d[m]),R();dji.utils.callListeners(z,"translateDone",!0);dji.utils.preventInputEventsOnBodyElements(!1);window.dji.ui.effects.leaveBusyState();var F=f.initialContext.activeElementInfo.iframes,B=f.boundingRect,G=b.main.getBoundingClientRect(),M=b.body.getBoundingClientRect(),C=sru.mainContainer.getBoundingClientRect(),K=Math.max(1,window.devicePixelRatio),
N=dji.utils.elementIsVisible(f.initialContext.element),q=30/K,H=G.height,P=G.width;b.body.scrollTop=0;P=Math.max(50,Math.min(C.left-2*q,P));b.main.style.height=P+"px";G=b.main.getBoundingClientRect();H=G.height;0<b.body.scrollHeight&&(H=Math.min(400,b.body.scrollHeight+M.height));H=Math.max(50,Math.min(window.innerHeight-2*q,H));b.main.style.height=H+"px";var G=b.main.getBoundingClientRect(),I=B.top,A=B.left;if(0<F.length)for(M=0;M<F.length;M++)var L=F[M].getBoundingClientRect(),I=I+L.top,A=A+L.left;
window.innerHeight<I+H&&(I=window.innerHeight-H-q/2-1);I=Math.max(I,q);A=Math.max(0,N?A+B.width+10:A);C.left<A+G.width+q&&(A=C.left-G.width-q-3);b.main.style.top=I+"px";b.main.style.left=A+"px";b.body.focus();dji.utils.removeClassFromElement(b.main,"dji-working")}catch(y){dji.logger.error(y),dji.utils.callListeners(z,"translateDone",!1),J()}}else J()};n.toggleTranslateButton=function(a){"English"==a?sru.toolbar.showButtons(!0,!0,!0,!1):sru.toolbar.showButtons(!0,!0,!0,!0)}})(window.dji.translate=
window.dji.translate||{});
