window.jsdapi=window.jsdapi||{};
(function(e){function c(b){var f=jsdapi.url()+"/sru";b&&(f+="/"+b);return f}function g(b){var f=c("files");b&&(f+="/"+b);return f}function k(b){var f=c("outlines");b&&(f+="/"+b);return f}function l(b){var f=c("measurements");b&&(f+="/"+b);return f}function h(b){if(b)try{b.apply(this,[].slice.call(arguments).splice(1))}catch(f){dji.logger.error(f)}}e.checkForUpdates=function(b,f){jsdapi.authorize(function(d){if(!d)return h(f,{error:401,message:"Authorization failed!"});d={responseType:"json",method:"POST",
url:g("check/updates"),query:{dapiAuthToken:d},contentType:"application/json",content:JSON.stringify({basic:!0,types:b})};jsdapi.http.sendRequest(d,function(b){if(b&&!b.error&&b.files)for(var a in b.files)if(b.files.hasOwnProperty(a)){var d=b.files[a],c;if("outlines/*"!==a)for(c=0;c<d.length;c++)d[c]=jsdapi.sru.types.File.fromJSON(d[c])}h(f,b)})})};e.listFiles=function(b,f,d){jsdapi.authorize(function(c){if(!c)return h(d,{error:401,message:"Authorization failed!"});c={responseType:"json",method:"POST",
url:g("list"),query:{dapiAuthToken:c},contentType:"application/json",content:JSON.stringify({type:b,language:f})};jsdapi.http.sendRequest(c,function(a){if(a&&!a.error&&a.files)for(var b=0;b<a.files.length;b++)a.files[b]=jsdapi.sru.types.File.fromJSON(a.files[b]);h(d,a)})})};e.createFile=function(b,f,d){jsdapi.authorize(function(c){if(!c)return h(d,{error:401,message:"Authorization failed!"});var a=new jsdapi.utf8.Utf8Data;a.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");a.appendString("Content-ID: info\r\n");
a.appendString('Content-Disposition: inline; name="info";\r\n');a.appendString("Content-Type: application/octet-stream\r\n");a.appendString("Content-Transfer-Encoding: binary\r\n\r\n");a.appendString(b.toJSONString());a.appendString("\r\n");a.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");a.appendString("Content-ID: body\r\n");a.appendString('Content-Disposition: inline; name="body";\r\n');a.appendString("Content-Type: application/octet-stream\r\n");a.appendString("Content-Transfer-Encoding: binary\r\n\r\n");
a.appendString(f);a.appendString("\r\n");a.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c--");c={responseType:"json",method:"POST",url:g("create"),query:{dapiAuthToken:c},contentType:'multipart/related; boundary="004460bc4277474996e8e922d1b4b4ecbf5a4c7c"',content:a.toUint8Array()};jsdapi.http.sendRequest(c,function(a){a&&!a.error&&a.file&&(a.file=jsdapi.sru.types.File.fromJSON(a.file));h(d,a)})})};e.updateFile=function(b,f,c){jsdapi.authorize(function(e){if(!e)return h(c,{error:401,message:"Authorization failed!"});
var a=new jsdapi.utf8.Utf8Data;a.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");a.appendString("Content-ID: info\r\n");a.appendString('Content-Disposition: inline; name="info";\r\n');a.appendString("Content-Type: application/octet-stream\r\n");a.appendString("Content-Transfer-Encoding: binary\r\n\r\n");a.appendString(b.toJSONString());a.appendString("\r\n");a.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c\r\n");a.appendString("Content-ID: body\r\n");a.appendString('Content-Disposition: inline; name="body";\r\n');
a.appendString("Content-Type: application/octet-stream\r\n");a.appendString("Content-Transfer-Encoding: binary\r\n\r\n");a.appendString(f);a.appendString("\r\n");a.appendString("--004460bc4277474996e8e922d1b4b4ecbf5a4c7c--");e={responseType:"json",method:"POST",url:g("update"),query:{dapiAuthToken:e},contentType:'multipart/related; boundary="004460bc4277474996e8e922d1b4b4ecbf5a4c7c"',content:a.toUint8Array()};jsdapi.http.sendRequest(e,function(a){a&&!a.error&&a.file&&(a.file=jsdapi.sru.types.File.fromJSON(a.file));
h(c,a)})})};e.downloadFile=function(b,c,d){jsdapi.authorize(function(e){if(!e)return h(d,{error:401,message:"Authorization failed!"});e={responseType:c||"binary",method:"GET",url:g("content"),query:{dapiAuthToken:e,type:b.type,uuid:b.uuid}};jsdapi.http.sendRequest(e,function(a){h(d,a)})})};e.testUpdateOutlines=function(){var b={update:{directories:[{uuid:"d3",parentUuid:"d1",title:"Directory 03",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"d1.a.1.x",parentUuid:"d1.a.1",title:"Directory 01.a.1.x",
creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"d1.a.1.y",parentUuid:"d1.a.1",title:"Directory 01.a.1.y",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"d1.a",parentUuid:"d1",title:"Directory 01.a",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"d1.b",parentUuid:"d1",title:"Directory 01.b",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"d1.a.1",parentUuid:"d1.a",title:"Directory 01.a.1",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"d1.a.2",parentUuid:"d1.a",
title:"Directory 01.a.2",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"d1",title:"Directory 01",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"d2",title:"Directory 02",creationDate:Date.now(),modifiedDate:Date.now()}],outlines:[{uuid:"o1",parentUuid:"d1",title:"Outline 01",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"o2",parentUuid:null,title:"Outline 02",creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"o3",title:"Outline 03",creationDate:Date.now(),modifiedDate:Date.now()}],
topics:[{uuid:"t1",outlineUuid:"o1",body:"<b>Topic 01 content</b>",location:10,creationDate:Date.now(),modifiedDate:Date.now(),sourcesUuids:["s1","s3"]},{uuid:"t2",outlineUuid:"o1",body:"<b>Topic 02 content</b>",location:3,creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"t3",outlineUuid:"o1",body:"<b>Topic 03 content</b>",location:2,creationDate:Date.now(),modifiedDate:Date.now()}],sources:[{uuid:"s1",outlineUuid:"o1",data:JSON.stringify({info:{author:"Codrin",title:"About ice"},text:{MLA:"<p>Codrin, About ice</p>"}}),
creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"s4",outlineUuid:"o1",data:JSON.stringify({info:{author:"Alina",title:"About earth"},text:{MLA:"<p>Alina, About earth</p>"}}),creationDate:Date.now(),modifiedDate:Date.now()},{uuid:"s3",outlineUuid:"o1",data:JSON.stringify({info:{author:"Otilia",title:"About water"},text:{MLA:"<p>Otila, About water</p>"}}),creationDate:Date.now(),modifiedDate:Date.now()}]},"delete":{directories:[{uuid:"d2"}],outlines:[{uuid:"o2"}],topics:[{uuid:"t3"}],sources:[{uuid:"s2"}]}};
e.comboUpdateOutlinesData(b,function(b){})};e.comboUpdateOutlinesData=function(b,c){jsdapi.authorize(function(d){if(!d)return h(c,{error:401,message:"Authorization failed!"});d={responseType:"json",method:"POST",url:k("data/combo-update"),query:{dapiAuthToken:d},contentType:"application/json",content:JSON.stringify(b)};jsdapi.http.sendRequest(d,function(b){h(c,b)})})};e.downloadOutlinesData=function(b,c){jsdapi.authorize(function(d){if(!d)return h(c,{error:401,message:"Authorization failed!"});d=
{responseType:"json",method:"POST",url:k("data/download"),query:{dapiAuthToken:d},contentType:"application/json",content:JSON.stringify(b)};jsdapi.http.sendRequest(d,function(b){h(c,b)})})};e.updateMeasurements=function(b,c){jsdapi.authorize(function(d){if(!d)return h(c,{error:401,message:"Authorization failed!"});d={responseType:"json",method:"POST",url:l("update"),query:{dapiAuthToken:d},contentType:"application/json",content:JSON.stringify(b)};jsdapi.http.sendRequest(d,function(b){h(c,b)})})}})(window.jsdapi.sru=
window.jsdapi.sru||{});
(function(e){e.File=function(c,e){this.uuid=c;this.type=e;this.comment=this.version=this.modifiedUuid=this.modifiedDate=this.creationDate=this.checksum=this.language=null};e.File.fromJSON=function(c){var g=new e.File(c.uuid,c.type);g.language=c.language;g.checksum=c.checksum;g.creationDate=c.creationDate;g.modifiedDate=c.modifiedDate;g.modifiedUuid=c.modifiedUuid;g.version=c.version;g.comment=c.comment;return g};e.File.fromJSONString=function(c){try{c=JSON.parse(c)}catch(g){dji.logger.error(g)}return e.File.fromJSON(c)};e.File.prototype.toJSON=
function(){return{uuid:this.uuid,type:this.type,language:this.language,checksum:this.checksum,creationDate:this.creationDate,modifiedDate:this.modifiedDate,modifiedUuid:this.modifiedUuid,version:this.version,comment:this.comment}};e.File.prototype.toJSONString=function(){return JSON.stringify(this.toJSON())}})(window.jsdapi.sru.types=window.jsdapi.sru.types||{});
