window.dji=window.dji||{};window.dji.ui=window.dji.ui||{};
(function(g){g.initialize=function(){var a=document.createElement("div");a.id="dji-sru-busy-state";dji.utils.preventInputEventsOnTree(a,!0);document.body.appendChild(a)};g.enterBusyState=function(){window.dji.utils.addClassToElement(document.documentElement,"dji-sru-busy-state")};g.leaveBusyState=function(){window.dji.utils.removeClassFromElement(document.documentElement,"dji-sru-busy-state")}})(window.dji.ui.effects=window.dji.ui.effects||{});
(function(g){var a={},e=null,m=null;g.cache=function(f,b,c){e||(e=document.createElement("iframe"),e.id="__dji_sru_templates",e.setAttribute("style","position: absolute; top: -5000px; left: -5000px; width: 200px; height: 200px;"),document.documentElement.appendChild(e),m=e.contentDocument);var d=m.createElement("link");d.href=chrome.extension.getURL(f);d.async=!0;d.rel="import";d.id=b;d.addEventListener("load",function(){a[d.id]=d["import"];m.head.removeChild(d);c&&c(a[d.id])});m.head.appendChild(d)};
g.source=function(f){return a.hasOwnProperty(f)?a[f]:null};g.load=function(a,b){1==arguments.length&&(b=a,a=document);a||(a=document);var c=a.querySelector('[dji-template-id="'+b+'"]');c&&(c=c.cloneNode(!0),c.removeAttribute("id"));return c}})(window.dji.ui.templates=window.dji.ui.templates||{});
(function(g){g.initializeContainer=function(a,e,m){var f=document,b=e;"object"===typeof e&&(f=e.source||document,b=e.name);e=dji.ui.templates.load(f,b);if(!e)return!1;var c=a.querySelector(".dji-sru-pagination-container-viewport");a.pageTemplateInfo={source:f,name:b};a.setAttribute("dji-page-template",b);$(e).addClass("dji-sru-page-current");e.style.left="0px";if(m)try{m(e)}catch(d){dji.logger.error(d)}c.appendChild(e);return!0};g.initViewport=function(a){a=a.querySelector(".dji-sru-pagination-container-viewport");
a.style.left="0px";a.style.width="410px"};g.createPages=function(a,e,m,f,b){var c=a.pageTemplateInfo;if(!c)return!1;var d=a.querySelector(".dji-sru-pagination-container-viewport");a=a.getBoundingClientRect().width||parseInt(window.getComputedStyle(a).width);0>=a&&(dji.logger.warning("pagination.createPages: container has invalid width (",a,"). Fallback top 410px!"),a=410);var k=a,h=0,g=0;$(d).empty();for(var l,n=0;n<e;n++){l=dji.ui.templates.load(c.source,c.name);if(!l)return!1;if(f)try{f(l,n,m)}catch(q){dji.logger.error(q)}l.style.left=
g+"px";l.style.display="none";d.appendChild(l);h+=a;g+=a;k-=a}l.style.display="block";$(l).addClass("dji-sru-page-current");d.style.width=h+"px";d.style.left=k+"px";b&&b()};g.nextPage=function(a,e,m){var f=a.pageTemplateInfo;if(!f)return!1;var b=dji.ui.templates.load(f.source,f.name);if(!b)return!1;var c=a.querySelector(".dji-sru-pagination-container-viewport"),d=c.querySelector(".dji-sru-page-current"),k=a.getBoundingClientRect(),h=c.getBoundingClientRect(),f=h.left-k.left-k.width,k=h.width+k.width,
h=h.width;if(0<f)m&&m();else{var g=function(){c.removeEventListener("webkitTransitionEnd",g);d.style.display="none";$(a).removeClass("dji-transition");$(c).removeClass("dji-transition");$(d).removeClass("dji-sru-page-current");$(b).removeClass("dji-sru-page-next").addClass("dji-sru-page-current");m&&m()};c.addEventListener("webkitTransitionEnd",g);if(e)try{e(b)}catch(l){dji.logger.error(l)}$(a).addClass("dji-transition");$(c).addClass("dji-transition");$(b).addClass("dji-sru-page-next");b.style.left=
h+"px";b.style.display="block";c.appendChild(b);c.style.width=k+"px";c.style.left=f+"px"}};g.previousPage=function(a,e,g,f){var b=a.querySelector(".dji-sru-pagination-container-viewport"),c=b.querySelector(".dji-sru-page-current"),d=c.previousElementSibling;if(d){for(var k=1,h=c;h.previousElementSibling;)h=h.previousElementSibling,k++;var p=410*(k-1),h=410*-(k-2),k=410*(k-2);if(0<h)f&&f();else{var l=function(){b.removeEventListener("webkitTransitionEnd",l);c.style.display="none";b.style.width=p+"px";
$(a).removeClass("dji-transition");$(b).removeClass("dji-transition");$(c).removeClass("dji-sru-page-current");$(d).removeClass("dji-sru-page-next").addClass("dji-sru-page-current");if(g)try{g(c)}catch(e){dji.logger.error(e)}b.removeChild(c);f&&f()};b.addEventListener("webkitTransitionEnd",l);if(e)try{e(d)}catch(n){dji.logger.error(n)}$(a).addClass("dji-transition");$(b).addClass("dji-transition");$(d).addClass("dji-sru-page-next");d.style.left=k+"px";d.style.display="block";b.style.left=h+"px"}}else f&&
f()};g.homePage=function(a,e,g,f){var b=a.querySelector(".dji-sru-pagination-container-viewport"),c=b.querySelector(".dji-sru-page-current"),d=b.firstElementChild;if(d&&c!=d){var k=a.getBoundingClientRect();b.getBoundingClientRect();var h=k.width,p=function(){b.removeEventListener("webkitTransitionEnd",p);c.style.display="none";b.style.width=h+"px";$(a).removeClass("dji-transition");$(b).removeClass("dji-transition");$(c).removeClass("dji-sru-page-current");$(d).removeClass("dji-sru-page-next").addClass("dji-sru-page-current");
if(g)try{g(c)}catch(e){dji.logger.error(e)}b.removeChild(c);f&&f(d)};b.addEventListener("webkitTransitionEnd",p);if(e)try{e(d)}catch(l){dji.logger.error(l)}for(e=1;e<b.children.length-1;e++)b.removeChild(b.children[e]);$(a).addClass("dji-transition");$(d).addClass("dji-sru-page-next");d.style.left="0px";d.style.display="block";b.style.left=-h+"px";b.style.width=2*h+"px";c.style.left=k.width+"px";setTimeout(function(){$(b).addClass("dji-transition");b.style.left="0px"},0)}else f&&f(d)}})(window.dji.ui.pagination=
window.dji.ui.pagination||{});
