(function(){function p(){var a=document.activeElement;if(a){if("IFRAME"===a.tagName)try{var f=a.contentDocument.body;f&&f.isContentEditable&&(a=f)}catch(h){}a?(a=a.ownerDocument,a=a.defaultView||a.parentWindow):a=window;return a}return window}function r(){return document.getElementById("WACViewPanel_EditingElement")}function y(a){switch(a){case 16:return"Shift";case 37:return"Left";case 39:return"Right"}return null}function m(a,f,h){h=h||{};var c=document.createEvent("Event");c.initEvent(a,!0,!0);
c.ctrlKey=!!h.ctrlKey;c.shiftKey=!!h.shiftKey;c.altKey=!!h.altKey;c.metaKey=!!h.metaKey;c.which=f;"keypress"===a?(c.charCode=f,c.keyIdentifier=""):(c.keyCode=f,c.keyIdentifier=y(f));return c}function e(){this.ready=!1;this.methods={};this.b=[];this.g=[];this.f=this.f.bind(this);document.addEventListener(e.c.k,this.f,!1)}function x(){var a,f=[];a=document.getElementById("WACViewPanel").getElementsByClassName("Paragraph");for(var h=[],c=r(),b=0,d=a.length;b<d;b++)c.contains(a[b])||h.push(a[b]);a=r().getElementsByClassName("Paragraph");
for(c=0;c<h.length;c++)for(b=0;b<a.length;b++)if(a[b].getAttribute("paraid")===h[c].getAttribute("paraid")){h[c]=a[b];break}for(c=0;c<h.length;c++)for(b=document.createTreeWalker(h[c],NodeFilter.SHOW_TEXT,null,!1);a=b.nextNode();)f.push(a);return f}function t(a,f){for(var h=document.createRange(),c=x(),b=0,d=!1,g=!1,k=0;k<c.length;k++){var l=-1!==c[k].parentNode.className.indexOf("EOP"),e=c[k].parentNode&&c[k].parentNode.parentNode&&-1!==c[k].parentNode.parentNode.className.indexOf("LineBreakBlob"),
n=-1!==c[k].parentNode.className.indexOf("LineMarker"),m=l?1:c[k].textContent.length;!(a<=b+m)||d||l||e||n||(h.setStart(c[k],a-b),d=!0);!(f<=b+m)||g||l||e||n||(h.setEnd(c[k],f-b),g=!0);if(d&&g)break;b+=c[k].length}d||g||(h.setStart(c[c.length-1],c[c.length-1].length),h.setEnd(c[c.length-1],c[c.length-1].length));return h}function u(a,f){var h=r(),c=p().getSelection(),b=t(a,f),d=b.getClientRects()[0],g="";if(a!==f&&(b.startContainer!==b.endContainer||b.startOffset!==b.endOffset)){for(var k=b.cloneContents(),
g=[],l=document.createTreeWalker(k,NodeFilter.SHOW_TEXT,null,!1);k=l.nextNode();)g.push(k);k="";for(l=0;l<g.length;l++)g[l].parentNode&&1===g[l].parentNode.nodeType&&"WACViewPanel_WACEditing_DescribedByElement"===g[l].parentNode.getAttribute("id")||(k+=g[l].textContent);g=k}b=b.commonAncestorContainer||b.startContainer;3===b.nodeType&&(b=b.parentNode);b.dispatchEvent(new MouseEvent("mousedown",{clientX:d.left,clientY:d.top+d.height/2,bubbles:!0,cancelable:!0}));b.dispatchEvent(new MouseEvent("mouseup",
{clientX:d.left,clientY:d.top+d.height/2,bubbles:!0,cancelable:!0}));b.dispatchEvent(new MouseEvent("click",{clientX:d.left,clientY:d.top+d.height/2,bubbles:!0,cancelable:!0}));d=p().getSelection();if(0<d.rangeCount){for(var d=d.getRangeAt(0),b=x(),l=k=null,e=0,n=0;n<b.length;n++){var q=b[n].length;b[n]===d.startContainer&&(k=e+d.startOffset);b[n]===d.endContainer&&(l=e+d.endOffset);if(null!==k&&null!==l)break;e+=q}d={startOffset:k,endOffset:l}}else d=null;if(d&&"number"===typeof d.startOffset&&"number"===
typeof d.endOffset)if(b=d.startOffset-a,0<b)for(d=0;d<b;d++)h.dispatchEvent(m("keydown",37)),h.dispatchEvent(m("keyup",37));else if(0>b)for(d=0;d<-b;d++)h.dispatchEvent(m("keydown",39)),h.dispatchEvent(m("keyup",39));g=g.length;for(d=0;d<g;d++)h.dispatchEvent(m("keydown",39,{shiftKey:!0})),h.dispatchEvent(m("keyup",39,{shiftKey:!0}));c.removeAllRanges();b=t(a,f);c.addRange(b);return b}function v(a){var f;if(a.createRange)try{f=a.createRange()}catch(h){return null}else if(a.rangeCount)f=a.getRangeAt(0);
else return null;return f}e.c={k:"aw-office365-content",h:"aw-office365-extension"};e.a={j:"req_ready",i:"ready",e:"return",l:"call",d:"error"};e.prototype.r=function(){document.dispatchEvent(new CustomEvent(e.c.h,{detail:JSON.stringify({type:e.a.j})}))};e.prototype.q=function(){this.ready=!0;this.postMessage({type:e.a.i});for(var a;a=this.g.shift();)this.postMessage(a)};e.prototype.p=function(){this.ready=!0;for(var a;a=this.g.shift();)this.postMessage(a)};e.prototype.f=function(a){a=JSON.parse(a.detail||
"{}");var f=a.type;if(f===e.a.e)this.o(a);else if(f===e.a.l)this.m(a);else if(f===e.a.d)this.n(a);else if(f===e.a.j)this.q();else if(f===e.a.i)this.p();else throw Error("Unhandled message."+a);};e.prototype.o=function(a){var f=a.id,h=this.b[f];this.b[f]=null;this.b[f+1]=null;h(a.returns)};e.prototype.m=function(a){var f=a.name,h=a.arguments;if(f in this.methods)try{var c=this.methods[f].apply(null,h);c instanceof Promise?c.then(function(d){this.postMessage({id:a.id,type:e.a.e,returns:d})}.bind(this)):
this.postMessage({id:a.id,type:e.a.e,returns:c})}catch(b){this.postError(e.a.d,a.id,b.message)}else this.postError(e.a.d,a.id,"Function doesn't exist!")};e.prototype.n=function(a){var f=a.id,h=this.b[f+1];this.b[f]=null;this.b[f+1]=null;h(a.message)};e.prototype.postError=function(a,f,h){this.postMessage({id:f,type:a,message:h})};e.prototype.postMessage=function(a){this.ready?document.dispatchEvent(new CustomEvent(e.c.h,{detail:JSON.stringify(a)})):this.g.push(a)};var w=new e,q=!1;w.methods.updateWindowSelection=
u;w.methods.replaceText=function(a,f,h){function c(){b++;return 5<b?Promise.resolve():(new Promise(function(a){setTimeout(a,100)})).then(function(){var a=p().getSelection();g&&g.collapsed&&a&&(g=v(a))}).then(function(){if(!g)return g=u(f,h),new Promise(function(a){setTimeout(a,100)})}).then(function(){var b=p().getSelection();if(!g||!g.startContainer||!g.endContainer||g.startContainer!==d&&!d.contains(g.startContainer)||g.endContainer!==d&&!d.contains(g.endContainer))if(b){if(g=v(b),!g||!g.startContainer||
!g.endContainer||g.startContainer!==d&&!d.contains(g.startContainer)||g.endContainer!==d&&!d.contains(g.endContainer))throw Error("Browser selection outside allowed region.");}else throw Error("Browser selection outside allowed region.");var c=document.createTextNode(a);d.dispatchEvent(m("keydown",65));d.dispatchEvent(m("keypress",a.charCodeAt(0)));var f=g.cloneRange();f.collapse(!1);f.insertNode(c);g.deleteContents();f=new Range;f.setStart(c,c.length);f.setEnd(c,c.length);b.removeAllRanges();b.addRange(f);
d.dispatchEvent(m("keyup",65))})}if(q)return Promise.resolve();q=!0;var b=0,d=r(),g=null,e=document.createElement("div");e.className="appwriter-invisible-overlay";document.body.appendChild(e);return Promise.resolve().then(function(){if(f===h){var b=t(f,h),e=p().getSelection();e.removeAllRanges();e.addRange(b);d.dispatchEvent(m("keydown",0));d.dispatchEvent(m("keypress",a.charCodeAt(0)));var b=v(p().getSelection()),e=document.createTextNode(a),g=b.cloneRange();g.collapse(!1);g.insertNode(e);b.deleteContents();
b=new Range;b.setStart(e,e.length);b.setEnd(e,e.length);e=p().getSelection();e.removeAllRanges();e.addRange(b);d.dispatchEvent(m("keyup",0))}else return u(f,h),c()}).then(function(){q=!1;e.parentNode&&e.parentNode.removeChild(e)},function(a){q=!1;e.parentNode&&e.parentNode.removeChild(e);throw a;})};w.r()}).call(this);
