window.dji=window.dji||{};
(function(h){function n(c,g,m,h){var f=null;c.getDirectory=function(e,b,a){if(!f)return d(a,null);f.root.getDirectory(e,{create:b},function(b){d(a,b)},function(b){dji.logger.group("getDirectory failed for file: "+e);dji.logger.error(b);dji.logger.groupEnd();d(a,null)})};c.getFile=function(e,b,a){if(!f)return d(a,null);f.root.getFile(e,{create:b},function(b){d(a,b)},function(b){dji.logger.group("getFile failed for file: "+e);dji.logger.error(b);dji.logger.groupEnd();d(a,null)})};c.createDirectory=
function(e,b){if(!f)return d(b,null);var a=r(e);if(!a||0>=a.length)d(b,null);else{var l=f.root,k=-1,c=function(){k++;k<a.length?l.getDirectory(a[k],{create:!0},function(e){dji.logger.log(e);l=e;k+1<a.length?c():d(b,l)},function(a){dji.logger.error(a);d(b,null)}):d(b,l)};c()}};c.writeFile=function(e,b,a){if(!f)return d(a,!1,null);f.root.getFile(e,{create:!0},function(e){e.createWriter(function(k){var c=function(){d(a,!0,e)},f=function(b){dji.logger.error(b);d(a,!1,null)};k.onwriteend=function(){k.onwriteend=
c;k.onerror=f;var a=b instanceof Blob?b:new Blob([b],{type:"application/octet-stream"});k.write(a)};k.onerror=function(b){dji.logger.error(b);d(a,!1,null)};k.truncate(0)},function(b){dji.logger.error(b);d(a,!1,null)})},function(b){dji.logger.error(b);d(a,!1,null)})};c.writeFileAsText=function(e,b,a){if(!f)return d(a,!1,null);f.root.getFile(e,{create:!0},function(e){e.createWriter(function(c){var f=function(){d(a,!0,e)},g=function(b){dji.logger.error(b);d(a,!1,null)};c.onwriteend=function(){c.onwriteend=
f;c.onerror=g;var a=b instanceof Blob?b:new Blob([b],{type:"text/plain;charset=UTF-8"});c.write(a)};c.onerror=function(b){dji.logger.error(b);d(a,!1,null)};c.truncate(0)},function(b){dji.logger.error(b);d(a,!1,null)})},function(b){dji.logger.error(b);d(a,!1,null)})};c.readFile=function(e,b){if(!f)return d(b,null,null);f.root.getFile(e,{},function(a){a.file(function(e){var c=new FileReader;c.onloadend=function(){d(b,this.result,a)};c.onerror=function(a){dji.logger.error(a);d(b,null,null)};c.readAsText(e)},
function(a){dji.logger.error(a);d(b,null,null)})},function(a){dji.logger.group("readFile failed for file: "+e);dji.logger.error(a);dji.logger.groupEnd();d(b,null,null)})};c.readFileAsBinaryString=function(c,b){if(!f)return d(b,null,null);f.root.getFile(c,{},function(a){a.file(function(c){var e=new FileReader;e.onloadend=function(){d(b,this.result,a)};e.onerror=function(a){dji.logger.error(a);d(b,null,null)};e.readAsBinaryString(c)},function(a){dji.logger.error(a);d(b,null,null)})},function(a){dji.logger.group("readFile failed for file: "+
c);dji.logger.error(a);dji.logger.groupEnd();d(b,null,null)})};c.readFileAsArrayBuffer=function(c,b){if(!f)return d(b,null,null);f.root.getFile(c,{},function(a){a.file(function(c){var e=new FileReader;e.onloadend=function(){d(b,this.result,a)};e.onerror=function(a){dji.logger.error(a);d(b,null,null)};e.readAsArrayBuffer(c)},function(a){dji.logger.error(a);d(b,null,null)})},function(a){dji.logger.group("readFile failed for file: "+c);dji.logger.error(a);dji.logger.groupEnd();d(b,null,null)})};c.removeDirectory=
function(c,b){if(!f)return d(b,!1);f.root.getDirectory(c,{},function(a){a.removeRecursively(function(){d(b,!0)},function(a){dji.logger.error(a);d(b,!1)})},function(a){dji.logger.error(a);d(b,"NotFoundError"===a.name)})};c.removeFile=function(c,b){if(!f)return d(b,!1);f.root.getFile(c,{},function(a){a.remove(function(){d(b,!0)},function(a){dji.logger.error(a);d(b,!1)})},function(a){dji.logger.error(a);d(b,"NotFoundError"===a.name)})};c.removeFiles=function(e,b){if(!f||!e||0>=e.length)d(b);else{var a=
-1,g=function(){a++;a<e.length?c.removeFile(e[a],function(){setTimeout(g,0)}):d(b)};g()}};window.webkitRequestFileSystem(g,m,function(c){dji.logger.log("fileSystem: ",c);f=c;setTimeout(function(){h(!0)},0)},function(c){dji.logger.error(c);h(!1)})}function r(c){if(!c||0>=c.length)return null;c=c.split("/");for(var d=[],h=0;h<c.length;h++)0<c[h].length&&d.push(c[h]);return d}function d(c){if(c)try{c.apply(this,[].slice.call(arguments).splice(1))}catch(d){dji.logger.error(d)}}var p={},q={};h.persistent=
null;h.temporary=null;h.initialize=function(c){if(h.persistent)return d(c,!0);try{dji.logger.group("Initialize HTML5 file system"),dji.logger.log("requesting quota: ",104857600),navigator.webkitPersistentStorage.requestQuota(104857600,function(g){dji.logger.log("quota granted: ",g);n(p,window.PERSISTENT,g,function(m){if(!m)return dji.logger.groupEnd(),d(c,!1);h.persistent=p;n(q,window.TEMPORARY,g,function(g){h.temporary=q;dji.logger.groupEnd();setTimeout(function(){d(c,g)},0)})})},function(g){dji.logger.error(g);
dji.logger.groupEnd();d(c,!1)})}catch(g){dji.logger.error(g),dji.logger.groupEnd(),d(c,!1)}}})(window.dji.fileSystem=window.dji.fileSystem||{});
