window.dji=window.dji||{};
(function(d){function l(a){a.stopPropagation()}function n(a){a.preventDefault();a.stopPropagation()}var k=null;d.os=function(){k||(k={chrome:-1!=window.navigator.userAgent.indexOf("CrOS"),mac:-1!=window.navigator.userAgent.indexOf("Macintosh"),windows:-1!=window.navigator.userAgent.indexOf("Windows")},k.name=k.chrome?"chrome":k.mac?"mac":"windows");return k};d.loadFile=function(a){try{var b=new XMLHttpRequest,c=chrome.extension.getURL(a);b.open("GET",c,!1);b.send();return b.responseText}catch(e){dji.logger.error(e)}};d.getMetadata=
function(){try{var a={},b=document.querySelector("title"),c=document.querySelector("meta[name='DC.title'"),e=c?c.getAttribute("content"):null;a.title=(b?b.innerText:e)||"";var b=[],d=document.querySelector("meta[name='author'"),c="";if(d&&""!==d.getAttribute("content"))c=d.getAttribute("content");else{var f=document.querySelector("meta[name='DC.contributor'");f&&(c=f.getAttribute("content"))}if(""!=c){var h=c.split(" ");1<h.length?b.push({given:h.slice(0,h.length-1).join(" "),family:h[h.length-1]}):
d?b.push({given:"",family:c}):b.push({given:c,family:""})}a.author=b;var m=document.querySelector("meta[name='date'")||document.querySelector("meta[name='DC.created'"),k=m?m.getAttribute("content"):(new Date(Date.now())).getFullYear(),l=/[0-9]{4,4}/.exec(k);0<l.length&&(a.issued={},a.issued["date-parts"]=[[l]]);var k=new Date(Date.now()),n=k.getMonth()+1,u=k.getDate(),l=k.getFullYear();a.accessed={};a.accessed["date-parts"]=[[l,n,u]];var q=document.querySelector("meta[name='medium'");q&&(a.medium=
q.getAttribute("content"));var r=window.location.pathname;a.URL=this.isSruPdf()?r.slice(1,r.length):window.location.href;var t=a.URL.split("://")[1];if(t){var p=t.split("www.");a["container-title"]=1==p.length?p[0].split("/")[0]:p[1].split("/")[0]}return a}catch(v){dji.logger.error(v)}return null};d.getSourcesFromXML=function(a){var b=[];a=(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("entry");for(var c=0;c<a.length;c++){for(var e={},d=0;d<a[c].childNodes.length;d++){var f=a[c].childNodes[d];
switch(f.nodeName){case "title":e.title=f.textContent;break;case "content":e.citation={};e.citation.all=f.textContent;for(var f=(new DOMParser).parseFromString("<content>"+f.textContent+"</content>","text/xml").getElementsByTagName("p"),h=0;h<f.length;h++){var m=f[h].innerHTML;switch(f[h].getAttribute("class")){case "citation_style_APA":e.citation.APA=m;break;case "citation_style_MLA":e.citation.MLA=m;break;case "citation_style_CHICAGO":e.citation.CHICAGO=m;break;case "citation_style_HARVARD":e.citation.CHICAGO=
m;break;case "citation_style_TURABIAN":e.citation.HARVARD=m}}break;case "author":e.authors=f.childNodes[1].textContent;break;case "id":e.linkCatalog=f.textContent;break;case "oclcterms:recordIdentifier":e.recordId=f.textContent}}b.push(e)}return b};d.addEventListener=function(a,b,c){a.hasOwnProperty(b)&&"function"==typeof c&&-1==a[b].indexOf(c)&&a[b].push(c)};d.removeEventListener=function(a,b,c){a.hasOwnProperty(b)&&"function"==typeof c&&(c=a[b].indexOf(c),-1!==c&&a[b].splice(c,1))};d.callListeners=
function(a,b){if(a&&a.hasOwnProperty(b)){var c=a[b];if(c&&0<c.length)for(var e=[].slice.call(arguments).splice(2),d=0;d<c.length;d++){var f=c[d];if(f)try{f.apply(this,e)}catch(h){dji.logger.error(h)}}}};d.callMethod=function(a){if(a)try{a.apply(this,[].slice.call(arguments).splice(1))}catch(b){dji.logger.error(b)}};d.checkInternetConnectionAvailable=function(a){var b=null,c=function(b){try{a(b)}catch(c){dji.logger.error(c)}};if(navigator.onLine)try{var e=new XMLHttpRequest;e.open("HEAD","https://www.google.com/?random="+
Math.random(),!0);e.onreadystatechange=function(){if(4===e.readyState&&0<e.status){var a=200<=e.status&&300>e.status||304===e.status;b&&clearTimeout(b);setTimeout(function(){c(a)},0)}};e.send();b=setTimeout(function(){e.abort();setTimeout(function(){c(!1)},0)},2E3)}catch(d){b&&clearTimeout(b),c(!1)}else c(!1)};d.isChromeOS=function(){return-1!=window.navigator.userAgent.indexOf("CrOS")};d.isMacOS=function(){return-1!=window.navigator.userAgent.indexOf("Macintosh")};d.isWindowsOS=function(){return-1!=
window.navigator.userAgent.indexOf("Windows")};d.isLoginApp=function(){for(var a=[/.*login.*\.donjohnston\.net/,/.*login.*\.qadji\.com/,/.*login.*\.stagedji\.com/,/.*login.*\.codeiasi\.net/],b=window.location.hostname,c=0;c<a.length;c++)if(a[c].test(b))return!0;return!1};d.isGoogleSearch=function(){var a=window.location.hostname.split(".");return 2!=a.length&&3!=a.length||"google"!==a[a.length-2]?!1:2==a.length||"www"===a[0]};d.isGoogleDocs=function(){if("docs.google.com"!==window.location.hostname)return!1;
var a=window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/d\//i);a||(a=window.location.pathname.match(/^(\/a\/[^\/]+)?\/document\/edit/i));return null!==a&&void 0!==a&&0<a.length};d.isGoogleDocsEditor=function(a,b){if(!a||!b&&!d.isGoogleDocs())return!1;if("IFRAME"==a.tagName)return d.elementHasClass(a,"docs-texteventtarget-iframe");for(;a;){if(d.elementHasClass(a,"kix-appview-editor"))return!0;a=a.parentElement}return!1};d.isGoogleHangouts=function(){return"talkgadget.google.com"===window.location.hostname};
d.isGoogleMail=function(){return d.stringEndsWith(window.location.hostname,"mail.google.com")};d.isYahooMail=function(){return d.stringEndsWith(window.location.hostname,"mail.yahoo.com")};d.isMicrosoftMail=function(){return d.stringEndsWith(window.location.hostname,"mail.live.com")};d.isEvernote=function(){return d.stringEndsWith(window.location.hostname,"evernote.com")};d.isFacebook=function(){return d.stringEndsWith(window.location.hostname,"facebook.com")};d.isTwitter=function(){return d.stringEndsWith(window.location.hostname,
"twitter.com")};d.isSru=function(){return d.stringStartsWith(window.location.href,"chrome-extension://"+chrome.runtime.id)};d.isSruPdf=function(){return d.stringStartsWith(window.location.href,"chrome-extension://"+chrome.runtime.id)};d.isBookshareBook=function(){if("bookshare-reader.s3.amazonaws.com"!==window.location.hostname)return!1;var a=window.location.search.match(/[\?\&]book=/i);return null!==a&&void 0!==a&&0<a.length};d.isAmazonKindle=function(){return d.stringEndsWith(window.location.hostname,
"read.amazon.com")};d.isIframeFree=function(){return d.isGoogleMail()};d.stringStartsWith=function(a,b){return 0===a.indexOf(b,0)};d.stringEndsWith=function(a,b){return-1!==a.indexOf(b,a.length-b.length)};d.addLeadingZero=function(a,b){var c="0000000000"+a;return c.substr(c.length-Math.max(String(a).length,b||2))};d.hostnameFromURL=function(a){return a.toString().replace(/^(.*\/\/[^\/?#]*).*$/,"$1")};d.jsonFromUrlQueryAndHash=function(a){if(!a)return null;try{var b=null,c=null;a=a.split("#");1==a.length?
a=a[0]:2==a.length&&(c=a[1],a=a[0]);a=a.split("?");2==a.length&&(b=a[1]);if(b)for(key in b='{"'+b.replace(/&/g,'", "').replace(/=/g,'": "')+'"}',b=JSON.parse(b),b)b.hasOwnProperty(key)&&(b[key]=decodeURIComponent(b[key]));if(c)for(key in c='{"'+c.replace(/&/g,'", "').replace(/=/g,'": "')+'"}',c=JSON.parse(c),c)c.hasOwnProperty(key)&&(c[key]=decodeURIComponent(c[key]));return a={query:b,hash:c}}catch(e){dji.logger.error(e)}return null};d.htmlToAscii=function(a,b){if(void 0===a||null===a||0==a.length)return a;
var c=d.htmlToAsciiTextArray(a,b),e=c.join("");delete c;return e};d.escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};d.escapeFileName=function(a){return a.replace(/\:/g,"_").replace(/\\/g,"_").replace(/\//g,"_").replace(/\&/g,"_").replace(/>/g,"_").replace(/</g,"_").replace(/"/g,"_").replace(/\|/g,"_").replace(/\*/g,"_").replace(/\?/g,"_")};d.objectsAreEqual=function(a,b){if(a===b)return!0;if(null===a||void 0===
a||null===b||void 0===b||typeof a!==typeof b||"string"==typeof a||"number"==typeof a)return!1;if(a instanceof Array||b instanceof Array){if(!(a instanceof Array&&b instanceof Array)||a.length!=b.length)return!1;for(var c=0;c<a.length;c++)if(!d.objectsAreEqual(a[c],b[c]))return!1;return!0}for(var e,g=0;2>g;g++){for(c in a)if(a.hasOwnProperty(c)&&(!b.hasOwnProperty(c)||!d.objectsAreEqual(a[c],b[c])))return!1;e=a;a=b;b=e}return!0};d.indexOfElementInArray=function(a,b){if(a)for(var c=0;c<a.length;c++)if(a[c]===
b)return c;return-1};d.findParagraph=function(a,b){return!a||b>a.length?null:d.findToken(a,b,dji.charSet.paragraphSeparator)};d.findSentence=function(a,b){return!a||b>a.length?null:d.findToken(a,b,dji.charSet.sentenceSeparator)};d.findWord=function(a,b){return!a||b>a.length?null:d.findToken(a,b,dji.charSet.wordSeparator)};d.findToken=function(a,b,c){if(b>a.length||null==c)return null;for(var e=b,e=b;0<=e;e--)if(c.characterIsMember(a.charAt(e))){e++;break}0>e&&(e=0);c=null;e<=b&&(c=a.slice(e,b+1));
return c};d.colorToRgb=function(a){var b=/rgba?\((\d{1,3}), ?(\d{1,3}), ?(\d{1,3}),? ?(\d{1,3})?\)$/i.exec(a);if(b)return{r:parseInt(b[1]),g:parseInt(b[2]),b:parseInt(b[3])};a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,b,d,f){return b+b+d+d+f+f});return(b=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(b[1],16),g:parseInt(b[2],16),b:parseInt(b[3],16)}:null};d.colorToHex=function(a){a&&(a=d.colorToRgb(a));return a?d.rgbToHex(a.r,a.g,a.b):null};d.rgbToHex=function(a,b,
c){a=[a.toString(16),b.toString(16),c.toString(16)];for(b=0;b<a.length;b++)1==a[b].length&&(a[b]="0"+a[b]);return"#"+a.join("")};d.elementHasId=function(a,b){if(!a||a.nodeType!==Node.ELEMENT_NODE||!b)return!1;try{var c=a.getAttribute("id");if(c&&0<c.length){var e=!1;return e=b instanceof Array?-1!=b.indexOf(c):c===b}}catch(d){}return!1};d.elementHasAttribute=function(a,b){if(!a||a.nodeType!==Node.ELEMENT_NODE||!b)return!1;try{if(b instanceof Array)for(var c=0;c<b.length;c++){if(a.hasAttribute(b))return!0}else return a.hasAttribute(b)}catch(e){}return!1};
d.addClassToElement=function(a,b){if(a&&b)try{var c=(a.getAttribute("class")||"").split(/\s/,void 0,!0);-1==c.indexOf(b)&&(c.push(b),a.setAttribute("class",c.join(" ")))}catch(e){}};d.removeClassFromElement=function(a,b){if(a&&b)try{var c=(a.getAttribute("class")||"").split(/\s/,void 0,!0),e=c.indexOf(b);-1!=e&&(c.splice(e,1),a.setAttribute("class",c.join(" ")))}catch(d){}};d.elementHasClass=function(a,b,c){if(!a||a.nodeType!==Node.ELEMENT_NODE||!b)return!1;try{var e=!1,d=(a.getAttribute("class")||
"").split(/\s/,void 0,!0);if(b instanceof Array)for(a=0;a<b.length;a++)if(e=-1!=d.indexOf(b[a]),c){if(!e)return!0}else{if(e)return!0}else return e=-1!=d.indexOf(b)}catch(f){}return!1};d.addClassToHtmlElements=function(a,b){for(var c=d.findValidDocumentElements(b),e=0;e<c.length;e++){var g=c[e];d.addClassToElement(g.documentElement,a);g.documentElement.setAttribute(a,"true")}};d.removeClassFromHtmlElements=function(a,b){for(var c=d.findValidDocumentElements(b),e=0;e<c.length;e++){var g=c[e];d.removeClassFromElement(g.documentElement,
a);g.documentElement.removeAttribute(a)}};d.elementHasSpecialAttribute=function(a,b){return a.hasAttribute(b)&&"true"==a.getAttribute(b)};d.elementIsVisible=function(a,b){if(!a)return!1;if(a.nodeType==Node.DOCUMENT_NODE)return!0;b=b||document;if(a.parentNode&&"HTML"==a.parentNode.tagName)return"BODY"===a.tagName;a.nodeType==Node.TEXT_NODE&&(a=a.parentElement);var c=b.defaultView.getComputedStyle(a,null);return"fixed"===c.getPropertyValue("position")?"none"!==c.getPropertyValue("display"):a.offsetParent?
!0:!1};d.closestParent=function(a,b){for(;a&&a.nodeType!=Node.ELEMENT_NODE;)a=a.parentElement;return a=a?a.closest(b):null};d.elementIsInsideBody=function(a){for(;a;){if(a.tagName&&"BODY"==a.tagName.toUpperCase())return!0;a=a.parentNode}return!1};d.lastElementChild=function(a,b){if(a)try{if(b)for(var c=null,e=d.documentForElement(a);a&&(c=a.lastChild);){for(;c&&!d.elementIsVisible(c,e);)c=c.previousElementSibling;if(!c)break;a=c}else for(;a&&a.lastChild&&a.nodeType!==Node.TEXT_NODE;)a=a.lastChild}catch(g){dji.logger.error(g)}return a};
d.isEditor=function(a,b){if(b){var c=d.elementContext(a);return c?c.isEditor:!1}if(void 0!==a.selectionStart)return!0;for(;a;){try{if("true"==a.getAttribute("contenteditable"))return!0}catch(e){}a=a.parentNode}return!1};d.editorContainer=function(a){if(a)try{if(void 0!==a.selectionStart)return a;if(a.isContentEditable){for(;a.parentElement&&a.parentElement.isContentEditable;)a=a.parentElement;return a}}catch(b){dji.logger.error(b)}return null};d.elementContext=function(a){if(!a)return null;var b=
{document:d.documentForElement(a),element:a,editor:null,isEditor:!1,isPlainEditor:!1,isContentEditable:!1,isGoogleDocs:d.isGoogleDocs(),isGoogleDocsEditor:!1,isGoogleHangouts:d.isGoogleHangouts(),isYahooMail:d.isYahooMail(),isAmazonKindle:!1};try{void 0!==a.selectionStart&&(b.isPlainEditor=!0)}catch(c){}try{a.isContentEditable&&(b.isContentEditable=!0)}catch(c){}b.isPlainEditor||b.isContentEditable?b.editor=a:d.isGoogleDocsEditor(a)?(b.isGoogleDocsEditor=!0,b.editor=document.querySelector(".kix-appview-editor")):
d.isAmazonKindle()&&!dji.utils.elementHasClass(document.documentElement,"dji-sru-screen-selection")&&(b.isAmazonKindle=!0);b.isEditor=b.isPlainEditor||b.isContentEditable||b.isGoogleDocsEditor;return b};d.activeElementInfo=function(a){var b=[],c=document,e=c.activeElement,g=!1,f=!1;if(d.isGoogleDocsEditor(e))"IFRAME"==e.tagName&&(a=(a=document.getElementById("kix-appview"))?a.getElementsByClassName("kix-appview-editor"):null)&&0<a.length&&(e=a[0]),g=!0;else if(d.isAmazonKindle()&&!dji.utils.elementHasClass(document.documentElement,
"dji-sru-screen-selection"))e=document.getElementById("KindleReaderIFrame").contentWindow.document,e.getElementById("column_0_frame_0")&&"hidden"!=e.getElementById("column_0_frame_0").style.visibility?b.push(e.getElementById("column_0_frame_0")):e.getElementById("column_0_frame_1")&&b.push(e.getElementById("column_0_frame_1")),e.getElementById("column_1_frame_0")&&"hidden"!=e.getElementById("column_1_frame_0").style.visibility?b.push(e.getElementById("column_1_frame_0")):e.getElementById("column_1_frame_1")&&
b.push(e.getElementById("column_1_frame_1")),c=document,f=!0;else{for(var h=!1;!h&&e&&"IFRAME"==e.tagName;)try{h=!0,d.validateIframe(e,!0)&&null!==e.contentDocument&&(b.push(e),c=e.contentDocument,e=c.activeElement,h=!1)}catch(m){break}if(!e||a&&"IFRAME"==e.tagName)return null}return{iframes:b,document:c,element:e,isGoogleDocsEditor:g,isAmazonKindle:f}};d.extractVisibleTextFromElement=function(a){if(!a)return"";if(3==a.nodeType)return a.textContent;var b="",c=null;for(a=document.createTreeWalker(a,
NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,function(a){if(3==a.nodeType)return NodeFilter.FILTER_ACCEPT;if("SCRIPT"==a.tagName||"NOSCRIPT"==a.tagName||"IMG"==a.tagName||"SELECT"==a.tagName||"INPUT"==a.tagName&&(!a.type||"text"!=a.type.toLowerCase()))return NodeFilter.FILTER_REJECT;var c=(a.getAttribute("id")||"").toLowerCase();if("dexcontrolscontainer"==c||"dexcontrolscontainermeasurement"==c||"__dji_cwe_body_overlay"==c||"__dji_cwe_measurement_window_generic"==c||"__dji_cwe_chrome_google_docs_proxy"==
c||"__dji_cwe_measurement_window"==c||"__dji_cwe_shortcuts"==c||"__dji_cwe_measurement_window_generic"==c||"none"==document.defaultView.getComputedStyle(a,null).getPropertyValue("display"))return NodeFilter.FILTER_REJECT;"SPAN"!=a.tagName&&(b+="\n");return NodeFilter.FILTER_ACCEPT},!0);c=a.nextNode();)3==c.nodeType?b+=" "+c.textContent:1==c.nodeType&&"TEXTAREA"==c.tagName&&(b+="\n"+c.value+"\n");return b};d.addEventListenerToBodyElements=function(a,b,c,e){e=d.findValidDocumentElements(null,e);for(var g=
0;g<e.length;g++)e[g].body&&e[g].body.addEventListener(a,b,c)};d.addEventListenerToDocumentElements=function(a,b,c){for(var e=d.findValidDocumentElements(),g=0;g<e.length;g++)e[g].addEventListener(a,b,c)};d.removeEventListenerFromBodyElements=function(a,b,c,e){e=d.findValidDocumentElements(null,e);for(var g=0;g<e.length;g++)try{e[g].body&&e[g].body.removeEventListener(a,b,c)}catch(f){}};d.preventInputEventsOnBodyElements=function(a,b,c,e){var g=d.isGoogleDocs();e=d.findValidIframeAndDocumentElements(null,
e);for(var f=0;f<e.length;f++){var h=e[f];h.doc.body&&(g?d.isGoogleDocsEditor(h.iframe)||d.preventInputEventsOnTree(h.doc.body,a,b,c):d.preventInputEventsOnTree(h.doc.body,a,b,c))}};d.preventInputEventsOnTree=function(a,b,c,e){if(a&&3!=a.nodeType){var g=d.isGoogleDocs(),f=null;a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,function(a){if(3==a.nodeType||"SCRIPT"==a.tagName||"NOSCRIPT"==a.tagName||g&&d.isGoogleDocsEditor(a,!0))return NodeFilter.FILTER_REJECT;a=a.id?a.id.toLowerCase():
"";return"dexcontrolscontainer"==a||"dexcontrolscontainermeasurement"==a||0==a.indexOf("__dji_cwe")||!c&&0==a.indexOf("dji-sru-")?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT},!0);var h=e||l;e=e||n;if(b)for(;f=a.nextNode();)f.addEventListener("click",e,!1),f.addEventListener("mousedown",h,!1),f.addEventListener("mouseup",e,!1),f.addEventListener("mousemove",e,!1),f.addEventListener("mouseout",e,!1),f.addEventListener("mouseover",e,!1),f.addEventListener("mousewheel",e,!1);else for(;f=a.nextNode();)try{f.removeEventListener("click",
e,!1),f.removeEventListener("mousedown",h,!1),f.removeEventListener("mouseup",e,!1),f.removeEventListener("mousemove",e,!1),f.removeEventListener("mouseout",e,!1),f.removeEventListener("mouseover",e,!1),f.removeEventListener("mousewheel",e,!1)}catch(m){}}};d.ignoreEvent=function(a){a.preventDefault();a.stopPropagation()};d.documentForElement=function(a){for(;a&&a.nodeType!=Node.DOCUMENT_NODE;)a=a.parentNode;return a};d.waitForDocumentToLoad=function(a,b){a=a||document;if("complete"===document.readyState)d.callMethod(b);
else{var c=function(){"complete"===a.readyState&&(a.removeEventListener("load",c,!0),d.callMethod(b))};a.addEventListener("load",c,!0)}};d.findValidDocumentElements=function(a,b){1==arguments.length&&"boolean"===typeof a&&(b=a,a=null);result=[];d.findValidDocumentElementsEx(a||document,result,b);return result};d.findValidDocumentElementsEx=function(a,b,c){b.push(a);a=a.getElementsByTagName("iframe");for(var e=0;e<a.length;e++){var g=a[e];d.validateIframe(g,c)&&null!==g.contentDocument&&d.findValidDocumentElementsEx(g.contentDocument,
b,c)}};d.findValidIframeElements=function(a,b){result=[];d.findValidIframeElementsEx(a||document,result,b);return result};d.findValidIframeElementsEx=function(a,b,c){a=a.getElementsByTagName("iframe");for(var e=0;e<a.length;e++){var g=a[e];d.validateIframe(g,c)&&null!==g.contentDocument&&(b.push(g),d.findValidIframeElementsEx(g.contentDocument,b,c))}};d.findValidIframeAndDocumentElements=function(a,b){result=[];d.findValidIframeAndDocumentElementsEx(a||document,result,b);return result};d.findValidIframeAndDocumentElementsEx=
function(a,b,c){a=a.getElementsByTagName("iframe");for(var e=0;e<a.length;e++){var g=a[e];d.validateIframe(g,c)&&null!==g.contentDocument&&(b.push({iframe:g,doc:g.contentDocument}),d.findValidIframeAndDocumentElementsEx(g.contentDocument,b,c))}};d.validateIframe=function(a,b){try{if(void 0===a.src||null===a.src)return!1;var c=a.getAttribute("id");if("__dji_sru_templates"==c||!b&&c&&0<=c.indexOf("dji_sru"))return!1;var c=null,d=a.src.split("/")[2];if(void 0!==d&&null!==d&&-1==d.indexOf(document.domain))return!1;
c=a.contentDocument;return null!==c&&void 0!==c}catch(g){}return!1};d.addCssToDocument=function(a,b,c){return d.addLinkToDocument(a,"stylesheet","text/css",b,c)};d.addJavascriptToDocument=function(a,b,c){return d.addLinkToDocument(a,null,"text/javascript",b,c)};d.addLinkToDocument=function(a,b,c,d,g){var f=a.createElement("link");f.href=g?d:chrome.extension.getURL(d);f.async=!0;f.rel=b;f.type=c;a.head||(b=a.createElement("head"),a.documentElement.appendChild(b));a.head.appendChild(f);return f};d.generateUUID=
function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var c=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==b?c:c&7|8).toString(16)})};d.blobToText=function(a,b){if(a){var c=new FileReader;c.onloadend=function(){b(c.result)};c.onerror=function(a){b(null)};c.readAsText(a)}else b(null)};d.htmlToAsciiTextArray=function(a,b){if(void 0===a||null===a)return null;if(0==a.length)return[];for(var c=a.length,d=Array(c),g=0;g<c;g++){var f=a.charAt(g),
h=a.charCodeAt(g);switch(h){case 9:case 160:f=" ";break;case 216:case 248:case 510:case 511:f="0";break;case 451:f="!";break;case 192:case 193:case 194:case 195:case 196:case 197:case 198:case 256:case 258:case 260:case 461:case 478:case 480:case 482:case 506:case 508:case 512:case 514:case 550:f="A";break;case 224:case 225:case 226:case 227:case 228:case 229:case 230:case 257:case 259:case 261:case 462:case 479:case 481:case 483:case 507:case 509:case 513:case 515:case 551:f="a";break;case 199:case 262:case 264:case 266:case 268:f=
"C";break;case 231:case 263:case 265:case 267:case 269:f="c";break;case 208:case 270:case 272:f="D";break;case 271:case 273:f="d";break;case 200:case 201:case 202:case 203:case 274:case 276:case 278:case 280:case 282:case 516:case 518:case 552:f="E";break;case 232:case 233:case 234:case 235:case 275:case 277:case 279:case 281:case 283:case 517:case 519:case 553:f="e";break;case 284:case 286:case 288:case 290:case 484:case 486:case 500:f="G";break;case 285:case 287:case 289:case 291:case 485:case 487:case 501:f=
"g";break;case 292:case 294:case 502:f="H";break;case 293:case 295:f="h";break;case 204:case 205:case 206:case 207:case 296:case 298:case 300:case 302:case 304:case 463:case 520:case 522:f="I";break;case 236:case 237:case 238:case 239:case 297:case 299:case 301:case 303:case 305:case 464:case 521:case 523:f="i";break;case 308:f="J";break;case 309:f="j";break;case 310:case 488:f="K";break;case 311:case 312:case 489:f="k";break;case 313:case 315:case 317:case 319:case 321:f="L";break;case 314:case 316:case 318:case 320:case 322:f=
"l";break;case 209:case 323:case 325:case 327:case 330:case 504:f="N";break;case 240:case 241:case 324:case 326:case 328:case 329:case 331:case 505:f="n";break;case 210:case 211:case 212:case 213:case 214:case 332:case 334:case 336:case 465:case 490:case 492:case 524:case 526:case 554:case 556:case 558:case 560:f="O";break;case 242:case 243:case 244:case 245:case 246:case 333:case 335:case 337:case 466:case 491:case 493:case 525:case 527:case 555:case 557:case 559:case 561:f="o";break;case 340:case 342:case 344:case 528:case 530:f=
"R";break;case 341:case 343:case 345:case 529:case 531:f="r";break;case 346:case 348:case 350:case 352:case 536:f="S";break;case 347:case 349:case 351:case 353:case 537:f="s";break;case 354:case 356:case 358:case 538:f="T";break;case 355:case 357:case 359:case 539:f="t";break;case 217:case 218:case 219:case 220:case 360:case 362:case 364:case 366:case 368:case 370:case 467:case 469:case 471:case 473:case 475:case 532:case 534:f="U";break;case 249:case 250:case 251:case 252:case 361:case 363:case 365:case 367:case 369:case 371:case 468:case 470:case 472:case 474:case 476:case 533:case 535:f=
"u";break;case 372:f="W";break;case 373:f="w";break;case 221:case 374:case 376:case 562:f="Y";break;case 253:case 254:case 255:case 375:case 563:f="y";break;case 377:case 379:case 381:case 548:f="Z";break;case 378:case 380:case 382:case 549:f="z";break;case 8211:f="-";break;case 8216:case 8217:f="'";break;case 8220:case 8221:f='"';break;case 8203:b||(f="");break;default:if(10!=h&&13!=h&&0<=h&&31>=h||127<=h)f=" "}d[g]=f}return d};d.splitInWords=function(a,b){var c=a.split(/\W/i);if(b)return c;for(var d=
[],g=0;g<c.length;g++){var f=c[g];f&&0<f.length&&d.push(f)}return d}})(window.dji.utils=window.dji.utils||{});
(function(d){function l(d,a){this.m_options=JSON.parse(JSON.stringify(d));this.m_listener=a;this.m_session=dji.utils.generateUUID();this.m_running=!1;this.m_timer=null;this.m_step=0;this.m_online=void 0;this.m_stateChanged=!1;this.m_onPerform=n.bind(this);this.m_options.frequency=this.m_options.frequency||12E4;this.m_options.useJsDapi=!!this.m_options.useJsDapi;this.m_options.timeout=this.m_options.timeout||2E3}function n(d){if(d==this.m_session){var a=this;a.m_step++;if(a.m_options.useJsDapi)jsdapi.http.sendRequest({method:"HEAD",
url:a.m_options.url||"https://www.google.com/?random="+Math.random(),timeout:a.m_options.timeout},function(b,e,g){d==a.m_session&&(b=200<=b&&300>b||304===b,e=void 0===a.m_online,a.m_stateChanged=b!==a.m_online,a.m_online=b,setTimeout(a.m_onPerform,a.m_options.frequency,a.m_session),!a.m_stateChanged||!a.m_listener||e&&a.m_online||a.m_listener(a.m_online))});else try{var b=new XMLHttpRequest;b.open("HEAD",a.m_options.url||"https://www.google.com/?random="+Math.random(),!0);b.timeout=a.m_options.timeout;
b.onreadystatechange=function(){if(d==a.m_session&&b.readyState===XMLHttpRequest.DONE&&0<b.status){var c=200<=b.status&&300>b.status||304===b.status,e=void 0===a.m_online;a.m_stateChanged=c!==a.m_online;a.m_online=c;setTimeout(a.m_onPerform,a.m_options.frequency,a.m_session);!a.m_stateChanged||!a.m_listener||e&&a.m_online||a.m_listener(a.m_online)}};b.ontimeout=b.onerror=b.onabort=function(){d==a.m_session&&(a.m_stateChanged=!1!==a.m_online,a.m_online=!1,setTimeout(a.m_onPerform,a.m_options.frequency,
a.m_session),a.m_stateChanged&&a.m_listener&&a.m_listener(a.m_online))};b.send()}catch(c){setTimeout(a.m_onPerform,a.m_options.frequency,a.m_session)}}}l.prototype.start=function(){this.m_running||(this.m_running=!0,this.m_onPerform(this.m_session))};l.prototype.stop=function(){this.m_timer&&(clearTimeout(this.m_timer),this.m_timer=null);this.m_session=dji.utils.generateUUID();this.m_running=!1;this.m_step=0;this.m_online=void 0;this.m_stateChanged=!1};l.prototype.reset=function(){this.m_online=void 0;
this.m_stateChanged=!1};d.createInternetConnectionMonitor=function(d,a){return new l(d,a)}})(window.dji.utils=window.dji.utils||{});
